// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_profile_rule.sql

package complianceruledb

import (
	"context"

	"github.com/google/uuid"
)

const insertProfileRule = `-- name: InsertProfileRule :execrows
INSERT INTO profile_rule (id, piece_profile_key, compliance_rule_key, override_severidade)
SELECT $1, pp.key, $3, $4
FROM piece_profile pp
WHERE pp.key = $2
`

type InsertProfileRuleParams struct {
	ID                 uuid.UUID `json:"id"`
	Key                string    `json:"key"`
	ComplianceRuleKey  string    `json:"compliance_rule_key"`
	OverrideSeveridade *string   `json:"override_severidade"`
}

func (q *Queries) InsertProfileRule(ctx context.Context, arg InsertProfileRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertProfileRule,
		arg.ID,
		arg.Key,
		arg.ComplianceRuleKey,
		arg.OverrideSeveridade,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
