// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_profile_rules.sql

package complianceruledb

import (
	"context"
)

const listProfileRules = `-- name: ListProfileRules :many
SELECT pr.id, pr.piece_profile_key, pr.compliance_rule_key, pr.override_severidade
FROM profile_rule pr
JOIN piece_profile pp ON pp.key = pr.piece_profile_key
WHERE pr.piece_profile_key = $1
ORDER BY pr.compliance_rule_key
`

func (q *Queries) ListProfileRules(ctx context.Context, pieceProfileKey string) ([]ProfileRule, error) {
	rows, err := q.db.Query(ctx, listProfileRules, pieceProfileKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfileRule
	for rows.Next() {
		var i ProfileRule
		if err := rows.Scan(
			&i.ID,
			&i.PieceProfileKey,
			&i.ComplianceRuleKey,
			&i.OverrideSeveridade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
