// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package complianceruledb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteProfileRule(ctx context.Context, arg DeleteProfileRuleParams) (int64, error)
	DeleteRule(ctx context.Context, key string) (int64, error)
	DeleteSectionRule(ctx context.Context, arg DeleteSectionRuleParams) (int64, error)
	GetRuleByKey(ctx context.Context, key string) (ComplianceRule, error)
	InsertProfileRule(ctx context.Context, arg InsertProfileRuleParams) (int64, error)
	InsertRule(ctx context.Context, arg InsertRuleParams) error
	InsertSectionRule(ctx context.Context, arg InsertSectionRuleParams) (int64, error)
	ListProfileRules(ctx context.Context, pieceProfileKey string) ([]ProfileRule, error)
	ListRules(ctx context.Context) ([]ComplianceRule, error)
	ListSectionRules(ctx context.Context, profileSectionID uuid.UUID) ([]SectionRule, error)
	UpdateRule(ctx context.Context, arg UpdateRuleParams) error
}

var _ Querier = (*Queries)(nil)
