// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: draft.sql

package draftdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDraftAttachment = `-- name: DeleteDraftAttachment :exec
DELETE FROM draft_attachment
WHERE id = $1 AND draft_id = $2 AND tenant_id = $3
`

type DeleteDraftAttachmentParams struct {
	ID       uuid.UUID `json:"id"`
	DraftID  uuid.UUID `json:"draft_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Hard-delete the join row. The document itself is NOT touched (ON DELETE RESTRICT
// enforces that in the FK). Scoped to (id, draft_id, tenant_id) — a miss is silently
// ignored (the caller checks rows-affected via the :exec tag; our mapper maps 0 to
// ErrAttachmentNotFound).
func (q *Queries) DeleteDraftAttachment(ctx context.Context, arg DeleteDraftAttachmentParams) error {
	_, err := q.db.Exec(ctx, deleteDraftAttachment, arg.ID, arg.DraftID, arg.TenantID)
	return err
}

const getAttachmentForUpdate = `-- name: GetAttachmentForUpdate :one
SELECT id, tenant_id, draft_id, document_id, category, position, created_at
FROM draft_attachment
WHERE id = $1 AND draft_id = $2 AND tenant_id = $3
`

type GetAttachmentForUpdateParams struct {
	ID       uuid.UUID `json:"id"`
	DraftID  uuid.UUID `json:"draft_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Load an attachment for update/delete guard: resolves (id, draft_id, tenant_id) to
// confirm it belongs to the right draft and tenant. A miss → pgx.ErrNoRows →
// ErrAttachmentNotFound (→ 404).
func (q *Queries) GetAttachmentForUpdate(ctx context.Context, arg GetAttachmentForUpdateParams) (DraftAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentForUpdate, arg.ID, arg.DraftID, arg.TenantID)
	var i DraftAttachment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DraftID,
		&i.DocumentID,
		&i.Category,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentForAttachment = `-- name: GetDocumentForAttachment :one
SELECT id, tenant_id, status, origin
FROM document
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetDocumentForAttachmentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetDocumentForAttachmentRow struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Status   string    `json:"status"`
	Origin   string    `json:"origin"`
}

// Load the minimal document fields the POST /v1/pecas/:id/anexos use case needs to
// validate before linking: status (must be UPLOADED) and origin (must be UPLOAD, never
// COURT). Scoped to (id, tenant_id) — a foreign or missing document → pgx.ErrNoRows →
// ErrDocumentNotFound (→ 404). Filters deleted_at IS NULL (a soft-deleted document
// cannot be attached).
func (q *Queries) GetDocumentForAttachment(ctx context.Context, arg GetDocumentForAttachmentParams) (GetDocumentForAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getDocumentForAttachment, arg.ID, arg.TenantID)
	var i GetDocumentForAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Status,
		&i.Origin,
	)
	return i, err
}

const getDraftAttachments = `-- name: GetDraftAttachments :many
SELECT
    da.id,
    da.document_id,
    d.title         AS name,
    d.original_filename,
    da.category,
    d.mime_type,
    d.size_bytes,
    d.status,
    da.position,
    da.created_at
FROM draft_attachment da
JOIN document d ON d.id = da.document_id
WHERE da.draft_id = $1
  AND da.tenant_id = $2
  AND d.status = 'UPLOADED'
  AND d.deleted_at IS NULL
ORDER BY da.position ASC, da.created_at ASC
`

type GetDraftAttachmentsParams struct {
	DraftID  uuid.UUID `json:"draft_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetDraftAttachmentsRow struct {
	ID               uuid.UUID          `json:"id"`
	DocumentID       uuid.UUID          `json:"document_id"`
	Name             *string            `json:"name"`
	OriginalFilename *string            `json:"original_filename"`
	Category         string             `json:"category"`
	MimeType         *string            `json:"mime_type"`
	SizeBytes        *int64             `json:"size_bytes"`
	Status           string             `json:"status"`
	Position         int32              `json:"position"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

// Read model for the attachments list embedded in GET /v1/pecas/:id. Returns only
// documents with status='UPLOADED' (a PENDING attachment is invisible — its bytes
// have not landed yet). Ordered by (position ASC, created_at ASC) for stable display.
// Scoped to (draft_id, tenant_id) — barrier 1; RLS on draft_attachment is barrier 2.
func (q *Queries) GetDraftAttachments(ctx context.Context, arg GetDraftAttachmentsParams) ([]GetDraftAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, getDraftAttachments, arg.DraftID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDraftAttachmentsRow
	for rows.Next() {
		var i GetDraftAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Name,
			&i.OriginalFilename,
			&i.Category,
			&i.MimeType,
			&i.SizeBytes,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDraftByID = `-- name: GetDraftByID :one
SELECT id, tenant_id, case_id, intimation_id,
       piece_type, title, content,
       status, saga_state,
       created_at, updated_at
FROM draft
WHERE id = $1 AND tenant_id = $2
`

type GetDraftByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetDraftByIDRow struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	CaseID       pgtype.UUID        `json:"case_id"`
	IntimationID pgtype.UUID        `json:"intimation_id"`
	PieceType    string             `json:"piece_type"`
	Title        string             `json:"title"`
	Content      *string            `json:"content"`
	Status       string             `json:"status"`
	SagaState    string             `json:"saga_state"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Load the full peça aggregate by id, filtered by tenant (barrier 1). A miss or
// foreign-tenant id yields pgx.ErrNoRows → ErrDraftNotFound (→ 404).
func (q *Queries) GetDraftByID(ctx context.Context, arg GetDraftByIDParams) (GetDraftByIDRow, error) {
	row := q.db.QueryRow(ctx, getDraftByID, arg.ID, arg.TenantID)
	var i GetDraftByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CaseID,
		&i.IntimationID,
		&i.PieceType,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.SagaState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDraftByIntimationID = `-- name: GetDraftByIntimationID :one
SELECT id, tenant_id, case_id, intimation_id,
       piece_type, title, content,
       status, saga_state,
       created_at, updated_at
FROM draft
WHERE tenant_id = $1 AND intimation_id = $2
`

type GetDraftByIntimationIDParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	IntimationID pgtype.UUID `json:"intimation_id"`
}

type GetDraftByIntimationIDRow struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	CaseID       pgtype.UUID        `json:"case_id"`
	IntimationID pgtype.UUID        `json:"intimation_id"`
	PieceType    string             `json:"piece_type"`
	Title        string             `json:"title"`
	Content      *string            `json:"content"`
	Status       string             `json:"status"`
	SagaState    string             `json:"saga_state"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Fetch the draft that already exists for the (tenant_id, intimation_id) pair —
// used by the idempotent POST path when the INSERT fails with 23505. Filters by
// tenant (barrier 1).
func (q *Queries) GetDraftByIntimationID(ctx context.Context, arg GetDraftByIntimationIDParams) (GetDraftByIntimationIDRow, error) {
	row := q.db.QueryRow(ctx, getDraftByIntimationID, arg.TenantID, arg.IntimationID)
	var i GetDraftByIntimationIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CaseID,
		&i.IntimationID,
		&i.PieceType,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.SagaState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDraftDetail = `-- name: GetDraftDetail :one
SELECT
    d.id,
    d.piece_type,
    d.title,
    d.content,
    d.status,
    d.saga_state,
    d.created_at,
    d.updated_at,

    -- intimation fields (NULL when draft has no intimation_id)
    i.id            AS intimation_id,
    i.type          AS intimation_type,
    i.content       AS intimation_content,
    i.made_available_at AS intimation_made_available_at,
    i.deadline_start_at AS intimation_deadline_start_at,

    -- process fields (via court_record, NULL when no intimation)
    cr.case_id      AS process_case_id,
    cr.id           AS process_court_record_id,
    cr.cnj_number   AS process_cnj_number,
    cr.court        AS process_court,
    cr.degree       AS process_degree,
    cr.class        AS process_class,
    cr.subject      AS process_subject,
    cr.judging_body AS process_judging_body,

    -- deadline fields (NULL when no intimation or no deadline derived yet)
    dl.id           AS deadline_id,
    dl.end_date     AS deadline_end_date,
    dl.status       AS deadline_status
FROM draft d
LEFT JOIN intimation  i  ON i.id = d.intimation_id
LEFT JOIN court_record cr ON cr.id = i.court_record_id
LEFT JOIN deadline    dl  ON dl.notification_id = i.id
WHERE d.id = $1 AND d.tenant_id = $2
`

type GetDraftDetailParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetDraftDetailRow struct {
	ID                        uuid.UUID          `json:"id"`
	PieceType                 string             `json:"piece_type"`
	Title                     string             `json:"title"`
	Content                   *string            `json:"content"`
	Status                    string             `json:"status"`
	SagaState                 string             `json:"saga_state"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	IntimationID              pgtype.UUID        `json:"intimation_id"`
	IntimationType            *string            `json:"intimation_type"`
	IntimationContent         *string            `json:"intimation_content"`
	IntimationMadeAvailableAt pgtype.Date        `json:"intimation_made_available_at"`
	IntimationDeadlineStartAt pgtype.Date        `json:"intimation_deadline_start_at"`
	ProcessCaseID             pgtype.UUID        `json:"process_case_id"`
	ProcessCourtRecordID      pgtype.UUID        `json:"process_court_record_id"`
	ProcessCnjNumber          *string            `json:"process_cnj_number"`
	ProcessCourt              *string            `json:"process_court"`
	ProcessDegree             *string            `json:"process_degree"`
	ProcessClass              *string            `json:"process_class"`
	ProcessSubject            *string            `json:"process_subject"`
	ProcessJudgingBody        *string            `json:"process_judging_body"`
	DeadlineID                pgtype.UUID        `json:"deadline_id"`
	DeadlineEndDate           pgtype.Date        `json:"deadline_end_date"`
	DeadlineStatus            *string            `json:"deadline_status"`
}

// Read model for GET /v1/pecas/:id: a JOIN over draft, intimation (optional),
// court_record (via intimation), and deadline (via intimation 1:1 UNIQUE). All
// intimation/process/deadline columns are NULLable (a draft without an intimation
// is valid — source=blank or source=processo). Filtered by (draft.id, draft.tenant_id)
// (barrier 1); RLS on draft is barrier 2. The court_record columns are read here
// without importing the acquisition slice (decisão: read the table directly).
func (q *Queries) GetDraftDetail(ctx context.Context, arg GetDraftDetailParams) (GetDraftDetailRow, error) {
	row := q.db.QueryRow(ctx, getDraftDetail, arg.ID, arg.TenantID)
	var i GetDraftDetailRow
	err := row.Scan(
		&i.ID,
		&i.PieceType,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.SagaState,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IntimationID,
		&i.IntimationType,
		&i.IntimationContent,
		&i.IntimationMadeAvailableAt,
		&i.IntimationDeadlineStartAt,
		&i.ProcessCaseID,
		&i.ProcessCourtRecordID,
		&i.ProcessCnjNumber,
		&i.ProcessCourt,
		&i.ProcessDegree,
		&i.ProcessClass,
		&i.ProcessSubject,
		&i.ProcessJudgingBody,
		&i.DeadlineID,
		&i.DeadlineEndDate,
		&i.DeadlineStatus,
	)
	return i, err
}

const getIntimationForDraft = `-- name: GetIntimationForDraft :one
SELECT
    i.id            AS intimation_id,
    cr.case_id      AS case_id,
    cr.id           AS court_record_id,
    i.type          AS intimation_type
FROM intimation i
JOIN court_record cr ON cr.id = i.court_record_id
WHERE i.id = $1 AND cr.tenant_id = $2
`

type GetIntimationForDraftParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetIntimationForDraftRow struct {
	IntimationID   uuid.UUID `json:"intimation_id"`
	CaseID         uuid.UUID `json:"case_id"`
	CourtRecordID  uuid.UUID `json:"court_record_id"`
	IntimationType *string   `json:"intimation_type"`
}

// Load the intimation context needed to build a draft from source=intimation:
// the case_id (via court_record), the court_record_id, and the type (for piece_type
// inference). Filtered by intimation.id and tenant_id (barrier 1 via court_record).
// A miss → pgx.ErrNoRows → ErrIntimationNotFound (→ 404).
func (q *Queries) GetIntimationForDraft(ctx context.Context, arg GetIntimationForDraftParams) (GetIntimationForDraftRow, error) {
	row := q.db.QueryRow(ctx, getIntimationForDraft, arg.ID, arg.TenantID)
	var i GetIntimationForDraftRow
	err := row.Scan(
		&i.IntimationID,
		&i.CaseID,
		&i.CourtRecordID,
		&i.IntimationType,
	)
	return i, err
}

const insertDraft = `-- name: InsertDraft :one

INSERT INTO draft (
    tenant_id, case_id, intimation_id,
    piece_type, title, content,
    status, saga_state,
    created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    'DRAFT', 'CREATED',
    now(), now()
)
ON CONFLICT (tenant_id, intimation_id) WHERE intimation_id IS NOT NULL DO NOTHING
RETURNING id, tenant_id, case_id, intimation_id,
          piece_type, title, content,
          status, saga_state,
          created_at, updated_at
`

type InsertDraftParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	CaseID       pgtype.UUID `json:"case_id"`
	IntimationID pgtype.UUID `json:"intimation_id"`
	PieceType    string      `json:"piece_type"`
	Title        string      `json:"title"`
	Content      *string     `json:"content"`
}

type InsertDraftRow struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	CaseID       pgtype.UUID        `json:"case_id"`
	IntimationID pgtype.UUID        `json:"intimation_id"`
	PieceType    string             `json:"piece_type"`
	Title        string             `json:"title"`
	Content      *string            `json:"content"`
	Status       string             `json:"status"`
	SagaState    string             `json:"saga_state"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// draft slice queries (peticionamento Fatia 1). Every write runs inside the use
// case's transaction so RLS scopes it to the principal's tenant (barrier 2) on top
// of the explicit tenant filter (barrier 1). Absence is a typed error at the mapper,
// never (nil, nil).
// Persist a new peça (DRAFT status, CREATED saga_state). Returns all columns so the
// handler renders the 201 response without a follow-up read. storage_key is NULL for
// Fatia 1 (content lives in the column, not in S3).
//
// ON CONFLICT DO NOTHING targets the partial unique index
// (tenant_id, intimation_id WHERE intimation_id IS NOT NULL). When the row already
// exists the RETURNING clause yields zero rows (pgx.ErrNoRows), which the repository
// maps to ErrDraftAlreadyExists so the use case can fetch the existing row for 200.
// This avoids a 23505 error that would abort the current transaction (25P02), making
// subsequent queries in the same tx impossible without a SAVEPOINT.
func (q *Queries) InsertDraft(ctx context.Context, arg InsertDraftParams) (InsertDraftRow, error) {
	row := q.db.QueryRow(ctx, insertDraft,
		arg.TenantID,
		arg.CaseID,
		arg.IntimationID,
		arg.PieceType,
		arg.Title,
		arg.Content,
	)
	var i InsertDraftRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CaseID,
		&i.IntimationID,
		&i.PieceType,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.SagaState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDraftAttachment = `-- name: InsertDraftAttachment :one

INSERT INTO draft_attachment (tenant_id, draft_id, document_id, category, position)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (draft_id, document_id) DO NOTHING
RETURNING id, tenant_id, draft_id, document_id, category, position, created_at
`

type InsertDraftAttachmentParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	DraftID    uuid.UUID `json:"draft_id"`
	DocumentID uuid.UUID `json:"document_id"`
	Category   string    `json:"category"`
	Position   int32     `json:"position"`
}

// ── draft_attachment queries (Peticionamento Fatia 2) ────────────────────────
// All writes run inside the use case's transaction (RLS barrier 2 + explicit
// tenant filter barrier 1). Absence is a typed error at the mapper, never (nil,nil).
// Link a document (origin=UPLOAD, status=UPLOADED) to a draft. The UNIQUE constraint
// (draft_id, document_id) guards against duplicates at the DB level; ON CONFLICT DO
// NOTHING maps it to pgx.ErrNoRows so the repo can return ErrAttachmentAlreadyLinked
// without a 23505 transaction abort.
func (q *Queries) InsertDraftAttachment(ctx context.Context, arg InsertDraftAttachmentParams) (DraftAttachment, error) {
	row := q.db.QueryRow(ctx, insertDraftAttachment,
		arg.TenantID,
		arg.DraftID,
		arg.DocumentID,
		arg.Category,
		arg.Position,
	)
	var i DraftAttachment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DraftID,
		&i.DocumentID,
		&i.Category,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateAttachmentCategory = `-- name: UpdateAttachmentCategory :one
UPDATE draft_attachment
SET category = $4
WHERE id = $1 AND draft_id = $2 AND tenant_id = $3
RETURNING id, tenant_id, draft_id, document_id, category, position, created_at
`

type UpdateAttachmentCategoryParams struct {
	ID       uuid.UUID `json:"id"`
	DraftID  uuid.UUID `json:"draft_id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Category string    `json:"category"`
}

// Change the category of an existing attachment, scoped to (id, draft_id, tenant_id).
// A no-match (wrong id, wrong draft, or foreign tenant) → pgx.ErrNoRows →
// ErrAttachmentNotFound (→ 404).
func (q *Queries) UpdateAttachmentCategory(ctx context.Context, arg UpdateAttachmentCategoryParams) (DraftAttachment, error) {
	row := q.db.QueryRow(ctx, updateAttachmentCategory,
		arg.ID,
		arg.DraftID,
		arg.TenantID,
		arg.Category,
	)
	var i DraftAttachment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DraftID,
		&i.DocumentID,
		&i.Category,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateDraftContent = `-- name: UpdateDraftContent :one
UPDATE draft
SET content    = $3,
    title      = CASE WHEN $4::boolean THEN $5 ELSE title END,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, title, updated_at
`

type UpdateDraftContentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Content  *string   `json:"content"`
	Column4  bool      `json:"column_4"`
	Title    string    `json:"title"`
}

type UpdateDraftContentRow struct {
	ID        uuid.UUID          `json:"id"`
	Title     string             `json:"title"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Autosave: update content (and optionally title) + bump updated_at, scoped to
// (id, tenant_id). Returns the minimal patch response fields. A no-match (wrong id
// or foreign tenant) yields pgx.ErrNoRows → ErrDraftNotFound (→ 404).
func (q *Queries) UpdateDraftContent(ctx context.Context, arg UpdateDraftContentParams) (UpdateDraftContentRow, error) {
	row := q.db.QueryRow(ctx, updateDraftContent,
		arg.ID,
		arg.TenantID,
		arg.Content,
		arg.Column4,
		arg.Title,
	)
	var i UpdateDraftContentRow
	err := row.Scan(&i.ID, &i.Title, &i.UpdatedAt)
	return i, err
}
