// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package draftdb

import (
	"context"
)

type Querier interface {
	// Load the full peça aggregate by id, filtered by tenant (barrier 1). A miss or
	// foreign-tenant id yields pgx.ErrNoRows → ErrDraftNotFound (→ 404).
	GetDraftByID(ctx context.Context, arg GetDraftByIDParams) (GetDraftByIDRow, error)
	// Fetch the draft that already exists for the (tenant_id, intimation_id) pair —
	// used by the idempotent POST path when the INSERT fails with 23505. Filters by
	// tenant (barrier 1).
	GetDraftByIntimationID(ctx context.Context, arg GetDraftByIntimationIDParams) (GetDraftByIntimationIDRow, error)
	// Read model for GET /v1/pecas/:id: a JOIN over draft, intimation (optional),
	// court_record (via intimation), and deadline (via intimation 1:1 UNIQUE). All
	// intimation/process/deadline columns are NULLable (a draft without an intimation
	// is valid — source=blank or source=processo). Filtered by (draft.id, draft.tenant_id)
	// (barrier 1); RLS on draft is barrier 2. The court_record columns are read here
	// without importing the acquisition slice (decisão: read the table directly).
	GetDraftDetail(ctx context.Context, arg GetDraftDetailParams) (GetDraftDetailRow, error)
	// Load the intimation context needed to build a draft from source=intimation:
	// the case_id (via court_record), the court_record_id, and the type (for piece_type
	// inference). Filtered by intimation.id and tenant_id (barrier 1 via court_record).
	// A miss → pgx.ErrNoRows → ErrIntimationNotFound (→ 404).
	GetIntimationForDraft(ctx context.Context, arg GetIntimationForDraftParams) (GetIntimationForDraftRow, error)
	// draft slice queries (peticionamento Fatia 1). Every write runs inside the use
	// case's transaction so RLS scopes it to the principal's tenant (barrier 2) on top
	// of the explicit tenant filter (barrier 1). Absence is a typed error at the mapper,
	// never (nil, nil).
	// Persist a new peça (DRAFT status, CREATED saga_state). Returns all columns so the
	// handler renders the 201 response without a follow-up read. storage_key is NULL for
	// Fatia 1 (content lives in the column, not in S3). ON CONFLICT on the partial unique
	// index (tenant_id, intimation_id WHERE intimation_id IS NOT NULL) is handled by the
	// use case via the pgconn 23505 code: the INSERT returns an error, the use case
	// fetches the existing row and returns 200 (idempotent).
	InsertDraft(ctx context.Context, arg InsertDraftParams) (InsertDraftRow, error)
	// Autosave: update content (and optionally title) + bump updated_at, scoped to
	// (id, tenant_id). Returns the minimal patch response fields. A no-match (wrong id
	// or foreign tenant) yields pgx.ErrNoRows → ErrDraftNotFound (→ 404).
	UpdateDraftContent(ctx context.Context, arg UpdateDraftContentParams) (UpdateDraftContentRow, error)
}

var _ Querier = (*Queries)(nil)
