// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suggested_thesis.sql

package draftdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSuggestedThesesByDraft = `-- name: DeleteSuggestedThesesByDraft :exec
DELETE FROM suggested_thesis
WHERE draft_id = $1 AND tenant_id = $2
`

type DeleteSuggestedThesesByDraftParams struct {
	DraftID  pgtype.UUID `json:"draft_id"`
	TenantID uuid.UUID   `json:"tenant_id"`
}

// Wipe a draft's suggested theses before a regenerate (POST always regenerates:
// delete + gera + persiste). Scoped by (draft_id, tenant_id).
func (q *Queries) DeleteSuggestedThesesByDraft(ctx context.Context, arg DeleteSuggestedThesesByDraftParams) error {
	_, err := q.db.Exec(ctx, deleteSuggestedThesesByDraft, arg.DraftID, arg.TenantID)
	return err
}

const deleteSuggestedThesesByIntimation = `-- name: DeleteSuggestedThesesByIntimation :exec
DELETE FROM suggested_thesis
WHERE intimation_id = $1 AND tenant_id = $2
`

type DeleteSuggestedThesesByIntimationParams struct {
	IntimationID pgtype.UUID `json:"intimation_id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
}

// Wipe an intimation's suggested theses before a regenerate (POST /intimacoes/:id/theses
// always regenerates). Scoped by (intimation_id, tenant_id).
func (q *Queries) DeleteSuggestedThesesByIntimation(ctx context.Context, arg DeleteSuggestedThesesByIntimationParams) error {
	_, err := q.db.Exec(ctx, deleteSuggestedThesesByIntimation, arg.IntimationID, arg.TenantID)
	return err
}

const insertSuggestedThesis = `-- name: InsertSuggestedThesis :one

INSERT INTO suggested_thesis (
    tenant_id, draft_id, intimation_id,
    label, confidence, reference, foundation, evidence,
    source_ref, source_document_id, source_page, source_excerpt, source_label,
    grounded, state, position,
    created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13,
    $14, $15, $16,
    now(), now()
)
RETURNING id, tenant_id, draft_id, label, confidence, reference, foundation, evidence, source_ref, source_document_id, source_page, source_excerpt, source_label, grounded, state, position, created_at, updated_at, intimation_id
`

type InsertSuggestedThesisParams struct {
	TenantID         uuid.UUID   `json:"tenant_id"`
	DraftID          pgtype.UUID `json:"draft_id"`
	IntimationID     pgtype.UUID `json:"intimation_id"`
	Label            string      `json:"label"`
	Confidence       string      `json:"confidence"`
	Reference        string      `json:"reference"`
	Foundation       string      `json:"foundation"`
	Evidence         []string    `json:"evidence"`
	SourceRef        int32       `json:"source_ref"`
	SourceDocumentID pgtype.UUID `json:"source_document_id"`
	SourcePage       int32       `json:"source_page"`
	SourceExcerpt    string      `json:"source_excerpt"`
	SourceLabel      string      `json:"source_label"`
	Grounded         bool        `json:"grounded"`
	State            string      `json:"state"`
	Position         int32       `json:"position"`
}

// suggested_thesis queries (Sugerir Teses persistido, C1). Draft-scoped. Every
// write runs inside the use case's transaction so RLS scopes it to the principal's
// tenant (barrier 2) on top of the explicit tenant_id filter (barrier 1).
// Persist one generated thesis. label/confidence/reference/foundation/evidence and
// the source_* fields mirror the in-memory Thesis produced by SuggestTheses (RAG+LLM);
// state/position are assigned by the persistence use case (initial state = pre-seleção
// do ancorado/alta confiança). C2: draft_id E intimation_id são nullable (o repo passa
// um preenchido e o outro NULL); o CHECK suggested_thesis_scope_chk garante EXATAMENTE
// UM não-nulo na borda do banco.
func (q *Queries) InsertSuggestedThesis(ctx context.Context, arg InsertSuggestedThesisParams) (SuggestedThesis, error) {
	row := q.db.QueryRow(ctx, insertSuggestedThesis,
		arg.TenantID,
		arg.DraftID,
		arg.IntimationID,
		arg.Label,
		arg.Confidence,
		arg.Reference,
		arg.Foundation,
		arg.Evidence,
		arg.SourceRef,
		arg.SourceDocumentID,
		arg.SourcePage,
		arg.SourceExcerpt,
		arg.SourceLabel,
		arg.Grounded,
		arg.State,
		arg.Position,
	)
	var i SuggestedThesis
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DraftID,
		&i.Label,
		&i.Confidence,
		&i.Reference,
		&i.Foundation,
		&i.Evidence,
		&i.SourceRef,
		&i.SourceDocumentID,
		&i.SourcePage,
		&i.SourceExcerpt,
		&i.SourceLabel,
		&i.Grounded,
		&i.State,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IntimationID,
	)
	return i, err
}

const listSuggestedThesesByDraft = `-- name: ListSuggestedThesesByDraft :many
SELECT id, tenant_id, draft_id, label, confidence, reference, foundation, evidence, source_ref, source_document_id, source_page, source_excerpt, source_label, grounded, state, position, created_at, updated_at, intimation_id FROM suggested_thesis
WHERE draft_id = $1 AND tenant_id = $2
ORDER BY position, created_at
`

type ListSuggestedThesesByDraftParams struct {
	DraftID  pgtype.UUID `json:"draft_id"`
	TenantID uuid.UUID   `json:"tenant_id"`
}

// The persisted list for GET /v1/pecas/:id/theses. Ordered deterministically by the
// position assigned at generation (sortTheses), created_at as tiebreaker.
func (q *Queries) ListSuggestedThesesByDraft(ctx context.Context, arg ListSuggestedThesesByDraftParams) ([]SuggestedThesis, error) {
	rows, err := q.db.Query(ctx, listSuggestedThesesByDraft, arg.DraftID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestedThesis
	for rows.Next() {
		var i SuggestedThesis
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DraftID,
			&i.Label,
			&i.Confidence,
			&i.Reference,
			&i.Foundation,
			&i.Evidence,
			&i.SourceRef,
			&i.SourceDocumentID,
			&i.SourcePage,
			&i.SourceExcerpt,
			&i.SourceLabel,
			&i.Grounded,
			&i.State,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IntimationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuggestedThesesByIntimation = `-- name: ListSuggestedThesesByIntimation :many
SELECT id, tenant_id, draft_id, label, confidence, reference, foundation, evidence, source_ref, source_document_id, source_page, source_excerpt, source_label, grounded, state, position, created_at, updated_at, intimation_id FROM suggested_thesis
WHERE intimation_id = $1 AND tenant_id = $2
ORDER BY position, created_at
`

type ListSuggestedThesesByIntimationParams struct {
	IntimationID pgtype.UUID `json:"intimation_id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
}

// The persisted list for GET /v1/intimacoes/:id/theses (partida). Same shape/order as
// the draft-scoped list; scoped by (intimation_id, tenant_id).
func (q *Queries) ListSuggestedThesesByIntimation(ctx context.Context, arg ListSuggestedThesesByIntimationParams) ([]SuggestedThesis, error) {
	rows, err := q.db.Query(ctx, listSuggestedThesesByIntimation, arg.IntimationID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SuggestedThesis
	for rows.Next() {
		var i SuggestedThesis
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DraftID,
			&i.Label,
			&i.Confidence,
			&i.Reference,
			&i.Foundation,
			&i.Evidence,
			&i.SourceRef,
			&i.SourceDocumentID,
			&i.SourcePage,
			&i.SourceExcerpt,
			&i.SourceLabel,
			&i.Grounded,
			&i.State,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IntimationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSuggestedThesisState = `-- name: UpdateSuggestedThesisState :one
UPDATE suggested_thesis
SET state = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, draft_id, label, confidence, reference, foundation, evidence, source_ref, source_document_id, source_page, source_excerpt, source_label, grounded, state, position, created_at, updated_at, intimation_id
`

type UpdateSuggestedThesisStateParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	State    string    `json:"state"`
}

// Flip the selection state (off|pending_add|included|pending_remove). Scoped by
// (id, tenant_id) — RLS + explicit filter. Zero rows (unknown id / foreign tenant)
// yields pgx.ErrNoRows, mapped to ErrThesisNotFound (→ 404).
func (q *Queries) UpdateSuggestedThesisState(ctx context.Context, arg UpdateSuggestedThesisStateParams) (SuggestedThesis, error) {
	row := q.db.QueryRow(ctx, updateSuggestedThesisState, arg.ID, arg.TenantID, arg.State)
	var i SuggestedThesis
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DraftID,
		&i.Label,
		&i.Confidence,
		&i.Reference,
		&i.Foundation,
		&i.Evidence,
		&i.SourceRef,
		&i.SourceDocumentID,
		&i.SourcePage,
		&i.SourceExcerpt,
		&i.SourceLabel,
		&i.Grounded,
		&i.State,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IntimationID,
	)
	return i, err
}
