// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actionitem.sql

package actionitemdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmActionItem = `-- name: ConfirmActionItem :one
UPDATE action_item
SET tipo_status = 'confiavel', updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND tipo_status = 'a_confirmar' AND status <> 'DISCARDED'
RETURNING id, tenant_id, intimation_id, court_record_id, tipo, gera_peca, piece_profile_key,
    tipo_origem, tipo_status, deadline_id, confianca, status, task_id, created_at, updated_at,
    title, description
`

type ConfirmActionItemParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// The guarded UPDATE behind POST /v1/action-items/:id/confirmar: tipo_status a_confirmar →
// confiável. Guarded by `tipo_status = 'a_confirmar' AND status <> 'DISCARDED'` so a racing
// descartar (or a second confirmar) cannot double-apply the transition — the concurrency
// floor, mirroring deadline's guarded MarkTaskStatus. Zero rows means the use case's pre-read
// raced with a concurrent write; the use case classifies that as ErrActionItemConflict.
func (q *Queries) ConfirmActionItem(ctx context.Context, arg ConfirmActionItemParams) (ActionItem, error) {
	row := q.db.QueryRow(ctx, confirmActionItem, arg.ID, arg.TenantID)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IntimationID,
		&i.CourtRecordID,
		&i.Tipo,
		&i.GeraPeca,
		&i.PieceProfileKey,
		&i.TipoOrigem,
		&i.TipoStatus,
		&i.DeadlineID,
		&i.Confianca,
		&i.Status,
		&i.TaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const deleteReplaceableActionItems = `-- name: DeleteReplaceableActionItems :exec
DELETE FROM action_item
WHERE tenant_id = $1 AND intimation_id = $2
  AND task_id IS NULL AND status = 'SUGGESTED' AND tipo_status = 'a_confirmar'
`

type DeleteReplaceableActionItemsParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	IntimationID uuid.UUID `json:"intimation_id"`
}

// The listener's guard aditivo (OnIntimationAnalyzed, docs handoff §"Guard obrigatório"):
// clears ONLY the items a re-analysis is allowed to replace — SUGGESTED, a_confirmar, and
// not yet bound to a task. A confiável (declarado/manual) or already-task-bound item is
// NEVER touched here; the fresh candidates are inserted right after in the same tx.
func (q *Queries) DeleteReplaceableActionItems(ctx context.Context, arg DeleteReplaceableActionItemsParams) error {
	_, err := q.db.Exec(ctx, deleteReplaceableActionItems, arg.TenantID, arg.IntimationID)
	return err
}

const discardActionItem = `-- name: DiscardActionItem :one
UPDATE action_item
SET status = 'DISCARDED', updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND status <> 'DISCARDED'
RETURNING id, tenant_id, intimation_id, court_record_id, tipo, gera_peca, piece_profile_key,
    tipo_origem, tipo_status, deadline_id, confianca, status, task_id, created_at, updated_at,
    title, description
`

type DiscardActionItemParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// The guarded UPDATE behind POST /v1/action-items/:id/descartar: status → DISCARDED.
// Guarded by `status <> 'DISCARDED'` — the concurrency floor, same shape as ConfirmActionItem.
func (q *Queries) DiscardActionItem(ctx context.Context, arg DiscardActionItemParams) (ActionItem, error) {
	row := q.db.QueryRow(ctx, discardActionItem, arg.ID, arg.TenantID)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IntimationID,
		&i.CourtRecordID,
		&i.Tipo,
		&i.GeraPeca,
		&i.PieceProfileKey,
		&i.TipoOrigem,
		&i.TipoStatus,
		&i.DeadlineID,
		&i.Confianca,
		&i.Status,
		&i.TaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const existsActionItemByTipo = `-- name: ExistsActionItemByTipo :one
SELECT EXISTS (
    SELECT 1 FROM action_item
    WHERE tenant_id = $1 AND intimation_id = $2 AND tipo = $3
)
`

type ExistsActionItemByTipoParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	IntimationID uuid.UUID `json:"intimation_id"`
	Tipo         string    `json:"tipo"`
}

// Dedup guard for the confiável (declarado/manual) candidates the delete above never
// clears: without it, re-running "Analisar" on an intimação whose teor keeps declaring the
// same providência would insert a duplicate row every time. Scoped by (tenant, intimation,
// tipo) — DELIBERATELY NOT by tipo_origem: a providência is unique PER TIPO for the user, so
// a re-analysis that reclassifies the same tipo under a different origem (declarado ⇄ ia)
// must NOT mint a second visible row. The surviving item (a declarado/task-bound one the
// delete never clears) wins; the fresh candidate of that tipo is skipped.
func (q *Queries) ExistsActionItemByTipo(ctx context.Context, arg ExistsActionItemByTipoParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsActionItemByTipo, arg.TenantID, arg.IntimationID, arg.Tipo)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getActionItem = `-- name: GetActionItem :one
SELECT id, tenant_id, intimation_id, court_record_id, tipo, gera_peca, piece_profile_key,
    tipo_origem, tipo_status, deadline_id, confianca, status, task_id, created_at, updated_at,
    title, description
FROM action_item
WHERE id = $1 AND tenant_id = $2
`

type GetActionItemParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// One action_item by id, scoped to tenantID (barrier 1). A miss/foreign row → pgx.ErrNoRows
// → the repo's typed ErrActionItemNotFound, never (nil, nil). Backs both confirmar/descartar's
// pre-read (to classify idempotent-no-op vs terminal-conflict vs proceed) and any future
// direct lookup.
func (q *Queries) GetActionItem(ctx context.Context, arg GetActionItemParams) (ActionItem, error) {
	row := q.db.QueryRow(ctx, getActionItem, arg.ID, arg.TenantID)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IntimationID,
		&i.CourtRecordID,
		&i.Tipo,
		&i.GeraPeca,
		&i.PieceProfileKey,
		&i.TipoOrigem,
		&i.TipoStatus,
		&i.DeadlineID,
		&i.Confianca,
		&i.Status,
		&i.TaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const hasFiledDraftForActionItem = `-- name: HasFiledDraftForActionItem :one
SELECT EXISTS (
    SELECT 1
    FROM task t
    JOIN draft d ON d.task_id = t.id AND d.superseded_at IS NULL
    WHERE t.action_item_id = $1 AND t.tenant_id = $2 AND d.filed_at IS NOT NULL
)
`

type HasFiledDraftForActionItemParams struct {
	ActionItemID pgtype.UUID `json:"action_item_id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
}

// Fatia 5 (docs §7 questão 4) guard for POST /v1/action-items/:id/reclassificar: once the
// providência's peça has been FILED (protocolada), the providência is frozen — reclassifying
// now would orphan a filed document with no paper trail of why the tipo changed. Cross-slice
// JOIN (task/draft are owned by internal/deadline and internal/draft respectively) — never a
// Go import, same pattern internal/draft's GetActionItemForTask already uses in reverse.
// superseded_at IS NULL scopes to the VIGENTE draft only: a task can carry a superseded +
// filed draft from a PRIOR reclassify round, which must never block a new one.
func (q *Queries) HasFiledDraftForActionItem(ctx context.Context, arg HasFiledDraftForActionItemParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasFiledDraftForActionItem, arg.ActionItemID, arg.TenantID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertActionItem = `-- name: InsertActionItem :one

INSERT INTO action_item (
    id, tenant_id, intimation_id, court_record_id, title, description, tipo, gera_peca,
    piece_profile_key, tipo_origem, tipo_status, deadline_id, confianca, status,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, tenant_id, intimation_id, court_record_id, tipo, gera_peca, piece_profile_key,
    tipo_origem, tipo_status, deadline_id, confianca, status, task_id, created_at, updated_at,
    title, description
`

type InsertActionItemParams struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	IntimationID    uuid.UUID          `json:"intimation_id"`
	CourtRecordID   pgtype.UUID        `json:"court_record_id"`
	Title           *string            `json:"title"`
	Description     *string            `json:"description"`
	Tipo            string             `json:"tipo"`
	GeraPeca        bool               `json:"gera_peca"`
	PieceProfileKey *string            `json:"piece_profile_key"`
	TipoOrigem      string             `json:"tipo_origem"`
	TipoStatus      string             `json:"tipo_status"`
	DeadlineID      pgtype.UUID        `json:"deadline_id"`
	Confianca       *float64           `json:"confianca"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// action_item queries (docs/erd-costura-providencia-tarefa-peca.md §2/§3). Every :one query
// below projects the FULL, same-order action_item column list so sqlc reuses one row shape
// (actionitemdb.ActionItem) across Insert/Get/Confirm/Discard — mapper.go's fromRow covers
// them all.
// Materializes one providência candidate (the listener's OnIntimationAnalyzed, one row per
// candidate in the event payload). task_id is never set here — a future fatia's deadline
// listener binds it once the item is confiável and turned into work.
func (q *Queries) InsertActionItem(ctx context.Context, arg InsertActionItemParams) (ActionItem, error) {
	row := q.db.QueryRow(ctx, insertActionItem,
		arg.ID,
		arg.TenantID,
		arg.IntimationID,
		arg.CourtRecordID,
		arg.Title,
		arg.Description,
		arg.Tipo,
		arg.GeraPeca,
		arg.PieceProfileKey,
		arg.TipoOrigem,
		arg.TipoStatus,
		arg.DeadlineID,
		arg.Confianca,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IntimationID,
		&i.CourtRecordID,
		&i.Tipo,
		&i.GeraPeca,
		&i.PieceProfileKey,
		&i.TipoOrigem,
		&i.TipoStatus,
		&i.DeadlineID,
		&i.Confianca,
		&i.Status,
		&i.TaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const linkActionItemTask = `-- name: LinkActionItemTask :one
UPDATE action_item
SET task_id = $3, status = 'CONFIRMED', updated_at = now()
WHERE id = $1 AND tenant_id = $2 AND task_id IS NULL
RETURNING id, tenant_id, intimation_id, court_record_id, tipo, gera_peca, piece_profile_key,
    tipo_origem, tipo_status, deadline_id, confianca, status, task_id, created_at, updated_at,
    title, description
`

type LinkActionItemTaskParams struct {
	ID       uuid.UUID   `json:"id"`
	TenantID uuid.UUID   `json:"tenant_id"`
	TaskID   pgtype.UUID `json:"task_id"`
}

// The reverse pointer of the providência→tarefa loop (docs §2/§6, fatia 3): once deadline's
// listener creates the task for a confiável action_item and announces task.created (carrying
// action_item_id), this UPDATE writes task_id + flips status → CONFIRMED. Guarded by
// task_id IS NULL: a redelivered task.created (past the consumer dedup, belt-and-suspenders)
// or a missing/foreign id both yield ZERO rows here, mapped by the repo to the SAME
// ErrActionItemNotFound GetActionItem uses — the use case treats either as a safe no-op,
// never overwriting an already-bound task_id.
func (q *Queries) LinkActionItemTask(ctx context.Context, arg LinkActionItemTaskParams) (ActionItem, error) {
	row := q.db.QueryRow(ctx, linkActionItemTask, arg.ID, arg.TenantID, arg.TaskID)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IntimationID,
		&i.CourtRecordID,
		&i.Tipo,
		&i.GeraPeca,
		&i.PieceProfileKey,
		&i.TipoOrigem,
		&i.TipoStatus,
		&i.DeadlineID,
		&i.Confianca,
		&i.Status,
		&i.TaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
	)
	return i, err
}

const reclassifyActionItem = `-- name: ReclassifyActionItem :one
UPDATE action_item
SET piece_profile_key = $3,
    tipo               = $4,
    tipo_origem        = 'manual',
    tipo_status        = 'confiavel',
    gera_peca          = true,
    confianca          = NULL,
    updated_at         = now()
WHERE id = $1 AND tenant_id = $2 AND status <> 'DISCARDED'
RETURNING id, tenant_id, intimation_id, court_record_id, tipo, gera_peca, piece_profile_key,
    tipo_origem, tipo_status, deadline_id, confianca, status, task_id, created_at, updated_at,
    title, description
`

type ReclassifyActionItemParams struct {
	ID              uuid.UUID `json:"id"`
	TenantID        uuid.UUID `json:"tenant_id"`
	PieceProfileKey *string   `json:"piece_profile_key"`
	Tipo            string    `json:"tipo"`
}

// The guarded UPDATE behind POST /v1/action-items/:id/reclassificar (fatia 5, docs §7
// questão 4): overrides tipo/piece_profile_key with tipo_origem='manual'/
// tipo_status='confiavel' (the same override precedence §3's motor already uses) and FORCES
// gera_peca=true — this endpoint only covers "ainda gera peça, tipo diferente"; converting to
// ciência is a future fatia's scope. confianca is reset to NULL: migration 0086's CHECK
// (tipo_origem = 'ia' OR confianca IS NULL) would otherwise reject overriding an
// ia-classified item's tipo_origem away from 'ia' while its old confidence score lingers.
// Guarded by `status <> 'DISCARDED'` — mirrors ConfirmActionItem/DiscardActionItem's
// concurrency floor: zero rows means a concurrent descartar won the race between the use
// case's pre-read and this UPDATE.
func (q *Queries) ReclassifyActionItem(ctx context.Context, arg ReclassifyActionItemParams) (ActionItem, error) {
	row := q.db.QueryRow(ctx, reclassifyActionItem,
		arg.ID,
		arg.TenantID,
		arg.PieceProfileKey,
		arg.Tipo,
	)
	var i ActionItem
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IntimationID,
		&i.CourtRecordID,
		&i.Tipo,
		&i.GeraPeca,
		&i.PieceProfileKey,
		&i.TipoOrigem,
		&i.TipoStatus,
		&i.DeadlineID,
		&i.Confianca,
		&i.Status,
		&i.TaskID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
	)
	return i, err
}
