// Package draft is the peticionamento Fatia 1 slice: creating and autosaving a
// peça (rascunho/draft). The advogado clicks "Peticionar" on an intimação (or
// opens a blank/processo draft), and this slice persists the initial context so
// the editor can open with pre-filled metadata and autosave.
//
// Scope: POST /v1/pecas (create), GET /v1/pecas/:id (read model), PATCH /v1/pecas/:id
// (autosave). Attachments (F2), AI review (F3), and signing/protocol (F4) are out of
// scope for this fatia.
//
// entity.go holds only the aggregate and its value types — it imports no repository,
// handler, or lib (the slice's inward dependency rule).
package draft

import "strings"

import "time"

// Draft is a peça (minuta) in its DRAFT lifecycle state. It is 1:1 with an intimação
// when source=intimation (enforced by the partial unique index); drafts from
// source=processo or source=blank have no intimação.
type Draft struct {
	ID           string
	TenantID     string
	CaseID       string // empty when source=blank and no case resolved yet
	IntimationID string // empty for blank/processo drafts
	PieceType    string
	Title        string
	Content      string // empty until autosave — plain text serialization (dual-write with StructuredContent)
	Status       string
	SagaState    string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	// CreatedBy é o app_user.id do advogado que clicou "Redigir peça". Persistido
	// no INSERT (migration 0063) e usado pelo read model da lista pra mostrar
	// avatar/nome no card. Vazio pra peças criadas antes da migration.
	CreatedBy string

	// ── Costura Providência↔Tarefa↔Minuta (migration 0088) ────────────────────

	// TaskID is the task this draft was created FROM (task-sourced Create,
	// docs/erd-costura-providencia-tarefa-peca.md §2/§3). Empty for every
	// pre-existing path (source=intimation/processo/blank) — those never set it.
	TaskID string
	// PieceProfileKey is the structured catalog key (piece_profile.key) the
	// providência behind TaskID named — the draft INHERITS it, never re-chooses
	// (§3). Empty when the draft has no task_id, or when the providência's
	// piece_profile_key itself was empty (gera_peca=false, ciência).
	PieceProfileKey string

	// FilingNumber é o número/protocolo do tribunal (migration 0060), gravado
	// via MarkFiled quando o advogado marca a peça como protocolada. Vazio =
	// pré-protocolo OU protocolado sem número informado.
	FilingNumber string

	// SupersededAt (fatia 5, docs §7 questão 4 — "reclassificação depois de gerada a
	// peça"): quando a providência de origem é reclassificada DEPOIS de a peça já
	// existir, esta peça é marcada superseded (nunca editada/apagada — "descartar e
	// recomeçar", a decisão do Architect). nil para toda peça vigente (a esmagadora
	// maioria).
	SupersededAt *time.Time
	// SupersededByDraftID aponta a peça NOVA que substituiu esta. Vazio até o
	// backfill de Create (populateFromTask) rodar — há uma janela curta entre a
	// providência ser reclassificada e a peça nova existir, em que SupersededAt já
	// está setado mas SupersededByDraftID ainda não.
	SupersededByDraftID string

	// ── Generation params (Fatia 5 — teses/tom/instruções) ────────────────────
	// Chosen on POST /v1/pecas/:id/generate and persisted on the row (not on the
	// draft.generation_requested event) so the async worker rereads them here.

	// Tone is the closed-set writing register for Gerar. Defaults to
	// "tecnico" (the DB column default — identical wording to the
	// pre-Fatia-5 prompt).
	Tone string
	// Instructions is free-text advogado guidance for Gerar, capped at 2000
	// runes at the edge. Empty when the advogado provided none.
	Instructions string
	// SelectedTheses are the tese labels (plain strings, not structured
	// citations) the advogado picked from /theses to steer Gerar. Empty when
	// none were selected.
	SelectedTheses []string

	// ── Estrutura em blocos (Peça v2 — migration 0056) ────────────────────────
	// StructuredContent is the block-structured version of the draft (preamble +
	// sections). Nil for drafts that haven't been generated by the Fatia B
	// pipeline nor patched with structured content yet — the read model
	// parses Content on-the-fly and (best-effort) writes back.
	StructuredContent *StructuredContent
	// Authorship marks whether the peça is still under the assistant workflow
	// ("assistant" — Iterar tab shown) or the advogado has taken over and only
	// wants proactive review suggestions ("human_taken" — Revisão tab shown).
	// One-way today; flipping back is not modeled.
	Authorship string
}

// AuthorshipAssistant / AuthorshipHumanTaken are the closed-set values for
// Draft.Authorship (Peça v2). Match the CHECK constraint in migration 0056.
const (
	AuthorshipAssistant  = "assistant"
	AuthorshipHumanTaken = "human_taken"
)

// StructuredContent is the block-structured shape of a peça: a preamble
// (endereçamento + qualificação) followed by N sections identified by their
// Roman numeral. Persisted as jsonb (draft.structured_content) via the
// column added in migration 0056; the front-end consumes it directly to
// render section cards, chips, and per-section iteration/review targets.
//
// Kept as pointer on Draft so a nil value means "not populated yet" (falls
// back to parsing Content) vs "populated but empty" (a truly empty peça,
// which today isn't a real state).
type StructuredContent struct {
	Preamble StructuredPreamble  `json:"preamble"`
	Sections []StructuredSection `json:"sections"`
}

// StructuredPreamble is the pre-section block of the peça: the endereçamento,
// process reference line, and qualificação paragraphs — anything before the
// first Roman-numbered section heading.
type StructuredPreamble struct {
	Paragraphs []string `json:"paragraphs"`
}

// StructuredSection is one Roman-numbered section of the peça. ID is derived
// from the title (slug) — used by the FE chips and by the iterate endpoint's
// scope.section_id. ShortTitle is the title minus the leading article
// ("Dos fatos" → "Fatos") for chip display.
type StructuredSection struct {
	ID         string   `json:"id"`
	Roman      string   `json:"roman"`
	Title      string   `json:"title"`
	ShortTitle string   `json:"short_title"`
	Paragraphs []string `json:"paragraphs"`
}

// Providence is one task derived from the peça's intimation, surfaced in the
// FE sidebar (bulleted list "PROVIDÊNCIAS"). Empty for drafts without an
// intimation. Source is the closed set {AI, RULE, MANUAL} from the task table.
type Providence struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	Kind   string `json:"kind"`   // suggested action label ("peça", "juntada"…)
	Source string `json:"source"` // "AI" | "RULE" | "MANUAL"
	Status string `json:"status"` // "OPEN" | "DONE"
}

// PatchResult is the thin response the autosave PATCH returns: only the fields that
// changed, so the client does not have to reload the full draft.
type PatchResult struct {
	ID        string
	Title     string
	UpdatedAt time.Time
}

// IntimationContext is the data the use case reads from the intimation row when
// source=intimation, to infer piece_type, resolve case_id/court_record_id, and
// compose the AI generation prompt with real process metadata.
type IntimationContext struct {
	IntimationID  string
	CaseID        string
	CourtRecordID string
	// Type is the raw DJEN type: CITACAO, INTIMACAO, COMUNICACAO, etc.
	Type string

	// Fields below are used by the AI generation prompt (buildDraftContext).
	// They mirror the columns available via GetDraftDetail's JOIN on court_record
	// and deadline — reusing the same sources, loading them together for the
	// generation path so no second query is needed.

	// Content is the full text of the intimation (teor) — the richest context
	// signal for the AI prompt.
	Content string
	// CNJNumber is the process number in CNJ format (e.g. 0000001-23.2026.8.26.0001).
	CNJNumber string
	// Court is the tribunal sigla (e.g. TJSP, TRT2).
	Court string
	// Degree is the grau (G1, G2, JE, SUPERIOR…).
	Degree string
	// Class is the classe/rito processual.
	Class string
	// Subject is the assunto.
	Subject string
	// JudgingBody is the órgão julgador / vara.
	JudgingBody string
	// DeadlineEndDate is the prazo end date formatted as "2006-01-02" (DateOnly),
	// or empty string when no deadline has been derived for this intimation yet.
	DeadlineEndDate string
	// Recipients is the raw jsonb from intimation.recipients ([]djenRecipient shape).
	// Parsed by the mapper to resolve the signing lawyer (matched=true recipient).
	Recipients []byte
}

// ActionItemForTask is the data the task-sourced Create flow reads from the
// task→action_item join (docs/erd-costura-providencia-tarefa-peca.md §3) when
// POST /v1/pecas carries a task_id: the providência's piece_profile_key (the
// peça TYPE, inherited — never re-chosen) plus the intimation/case context
// needed to populate the draft the same way the source=intimation path does.
type ActionItemForTask struct {
	IntimationID string
	// CaseID is "" when the providência's court_record has no case link.
	CaseID string
	// PieceProfileKey is "" when the providência doesn't generate a peça
	// (gera_peca=false, ciência) — Create falls back to inferPieceType.
	PieceProfileKey string
}

// GenerationProfile is the piece_profile + its ordered sections + the
// base_skeleton slots, loaded by the generation pipeline (PART B) to steer the
// draft_minuta prompt from the CATALOG instead of the fixed Fatos/Direito/Pedidos
// trio. Empty (nil Sections) when the draft has no piece_profile_key or the key
// is unknown to the catalog — the generation then falls back to the generic
// structure. GLOBAL catalog (migration 0085 — no tenant_id).
type GenerationProfile struct {
	Key      string
	Nome     string
	Polo     string
	Slots    []string // base_skeleton moldura order: enderecamento, preambulo, miolo, pedidos, fecho
	Sections []ProfileSectionInfo
}

// ProfileSectionInfo is one profile_section row (the MIOLO structure of a peça
// type), ordered by Ordem. Obrigatoria is the raw enum "sim"|"nao"|"condicional";
// AceitaTeses marks the sections where selected theses go.
type ProfileSectionInfo struct {
	Key         string
	Titulo      string
	Ordem       int
	Obrigatoria string // "sim" | "nao" | "condicional"
	Origem      string // "moldura" | "argumentativa"
	AceitaTeses bool
}

// PartyCounselInfo is one advogado aggregated under a party. OAB and UF are the
// stable identity (as stored by the DJEN parser); Name may be empty when absent.
type PartyCounselInfo struct {
	Name string
	OAB  string
	UF   string
}

// PartyInfo is one party of the process with its aggregated counsels.
// Role is the raw DB value (PLAINTIFF, DEFENDANT, THIRD_PARTY). Counsel is the
// short one-line label used by the AI prompt (first counsel formatted as
// "Name (OAB/UF nº oab)"); Counsels is the full list surfaced by the read model
// so the FE sidebar can render every advogado.
type PartyInfo struct {
	Role     string
	Name     string
	// IsClient is TRUE when one of this party's advogados carries an OAB the
	// tenant watches (the escritório represents this party). Read model only —
	// the FE uses it to pick THE client instead of guessing by role. FALSE when
	// the tenant watches no OAB.
	IsClient bool
	Counsel  string             // first counsel formatted; "" when absent (AI prompt only)
	Counsels []PartyCounselInfo // full list; empty slice (never nil) when absent
}

// SigningLawyer is the OAB-matched advogado from intimation.recipients — the first
// recipient flagged matched=true (our OAB, the signing lawyer for the peça).
// All fields are empty strings when no matched recipient exists.
type SigningLawyer struct {
	Name string
	OAB  string
	UF   string
}

// PieceType closed set — the only values the edge accepts and the DB stores.
const (
	PieceTypeDefense   = "DEFENSE"
	PieceTypeComplaint = "COMPLAINT"
	PieceTypeAppeal    = "APPEAL"
	PieceTypeMotion    = "MOTION"
	PieceTypeOther     = "OTHER"
)

// validPieceTypes is the lookup used by validation.
var validPieceTypes = map[string]bool{
	PieceTypeDefense:   true,
	PieceTypeComplaint: true,
	PieceTypeAppeal:    true,
	PieceTypeMotion:    true,
	PieceTypeOther:     true,
}

// pieceTypeLabelPT maps the closed piece_type set to a human-readable label —
// espelha o dicionário do FE (pecas-list-page.tsx) pra o BE conseguir montar
// o título default sem exigir uma passada extra no cliente.
var pieceTypeLabelPT = map[string]string{
	PieceTypeDefense:   "Defesa",
	PieceTypeComplaint: "Petição inicial",
	PieceTypeAppeal:    "Recurso",
	PieceTypeMotion:    "Petição",
	PieceTypeOther:     "Peça",
}

// defaultDraftTitle monta o título fallback pra draft.title quando o caller
// não passa nada. Retorna "<Tipo> · <CNJ>" quando o CNJ é conhecido, senão
// só "<Tipo>". Usado pra evitar rows com title vazio na lista.
func defaultDraftTitle(pieceType, cnj string) string {
	label := pieceTypeLabelPT[pieceType]
	if label == "" {
		label = "Peça"
	}
	if cnj != "" {
		return label + " · " + cnj
	}
	return label
}

// ── Generation params (Fatia 5 — teses/tom/instruções) ──────────────────────

// Tone closed set — the only values POST /v1/pecas/:id/generate accepts for
// the `tone` field. Mirrors the DB CHECK (draft_tone_check). ToneTecnico
// is the default (server-side, when the caller omits or sends "").
// Migração 0055 encurtou os rótulos (antes: tecnico-formal / direto-assertivo /
// conciliador-institucional) pra bater com o mockup Claude Design.
const (
	ToneTecnico  = "tecnico"
	ToneObjetivo = "objetivo"
	ToneEnfatico = "enfatico"
)

// validTones is the lookup used by validation.
var validTones = map[string]bool{
	ToneTecnico:  true,
	ToneObjetivo: true,
	ToneEnfatico: true,
}

// Thesis is one AI-suggested legal thesis for POST /v1/pecas/:id/theses. Unlike
// a Finding/Citation, Reference is a plain string — jurisprudência or a legal
// dispositivo is not a chunk anchored in the case corpus, so it carries no
// document_id/page/quote.
//
// Evidence carrega trechos LITERAIS do teor/chunks que sustentam a tese —
// serve pra justificar a confidence pro advogado (a "prova" por trás do
// rótulo alta/media/baixa) e pra reduzir alucinação (o LLM é forçado a citar
// o que leu, não inventar). Vazio = tese sem base literal no contexto (o
// prompt permite quando é doutrina/dispositivo puro, mas força confidence
// baixa nesse caso).
type Thesis struct {
	Label      string   `json:"label"`
	Confidence string   `json:"confidence"` // alta|media|baixa
	Reference  string   `json:"reference"`  // jurisprudência ou dispositivo legal, texto livre
	Foundation string   `json:"foundation"`
	Evidence   []string `json:"evidence"`

	// SourceRef is the LLM-cited chunk number (1..N of "Trechos relevantes dos
	// autos" in the prompt) whose literal text sustains this thesis; 0 means the
	// thesis is grounded only in the teor da intimação or in doctrine (no chunk).
	// Part of the LLM contract — resolveThesisSource turns it into the Source*
	// fields below by an EXACT lookup (hits[SourceRef-1]), not a substring guess.
	SourceRef int `json:"source_ref"`

	// Source* attribute the thesis back to the AUTOS document its evidence came
	// from — resolved by resolveThesisSource from SourceRef (exact lookup into the
	// RAG chunk hits), NOT emitted by the LLM (json:"-"). Empty when SourceRef==0
	// or out of range (grounded only in the teor or doctrinal); the FE then falls
	// back to the teor. This is what surfaces "esta tese se apoia na Petição
	// inicial · pág. 3".
	SourceDocumentID string `json:"-"`
	SourceLabel      string `json:"-"`
	SourceExcerpt    string `json:"-"`
	SourcePage       int    `json:"-"`

	// Grounded is computed by resolveThesisSource: true when a piece of Evidence
	// is a verified literal substring of the cited chunk (SourceRef≥1) OR of the
	// teor (SourceRef==0). false = evidence didn't match the cited source (likely
	// wrong ref) or matched nothing at all (likely hallucinated). Wire: json
	// "grounded" via thesisResponse. NOT the LLM contract (json:"-").
	Grounded bool `json:"-"`
}

// ThesisConfidence closed set.
const (
	ThesisConfidenceAlta  = "alta"
	ThesisConfidenceMedia = "media"
	ThesisConfidenceBaixa = "baixa"
)

// SuggestedThesis is a Thesis PERSISTED against a draft (Sugerir Teses persistido,
// C1). It carries everything the in-memory Thesis carries (label/confidence/
// reference/foundation/evidence + the resolved Source*/Grounded fields) plus the
// persistence-only concerns the FE (pecas-v2) needs to select and keep the
// advogado's choice across revisits: a stable ID, a selection State, and the
// deterministic Position assigned at generation. Unlike Thesis (an LLM contract),
// its Source* fields ARE wired to the FE (via suggestedThesisResponse).
//
// C2 will generalize this to intimation-scope (the partida flow, /pecas/nova with
// no draft yet) by adding an IntimationID and relaxing DraftID — the shape here is
// deliberately a superset of Thesis so that extension is additive.
type SuggestedThesis struct {
	ID string
	// DraftID and IntimationID are mutually exclusive — EXACTLY ONE is set (DB CHECK
	// suggested_thesis_scope_chk, migration 0093). Draft-scoped (construção) vs.
	// intimation-scoped (partida, /pecas/nova antes do draft existir).
	DraftID      string
	IntimationID string

	Label      string
	Confidence string
	Reference  string
	Foundation string
	Evidence   []string

	SourceRef        int
	SourceDocumentID string
	SourcePage       int
	SourceExcerpt    string
	SourceLabel      string
	Grounded         bool

	State    string
	Position int
}

// ThesisState closed set — the selection state machine for a persisted suggested
// thesis. off = not selected; pending_add = pre-selected/queued to include;
// included = part of the draft's thesis set; pending_remove = queued to drop. The
// DB CHECK (migration 0092) mirrors this; ValidThesisState guards the app boundary.
const (
	ThesisStateOff           = "off"
	ThesisStatePendingAdd    = "pending_add"
	ThesisStateIncluded      = "included"
	ThesisStatePendingRemove = "pending_remove"
)

// ValidThesisState reports whether s is a member of the closed ThesisState set.
func ValidThesisState(s string) bool {
	switch s {
	case ThesisStateOff, ThesisStatePendingAdd, ThesisStateIncluded, ThesisStatePendingRemove:
		return true
	default:
		return false
	}
}

// initialThesisState is the pre-selection rule (produto): only the anchored or
// high-confidence theses start queued for inclusion (pending_add); everything else
// starts off. Grounded == true (evidence verified against the cited source) OR
// confidence == "alta" pre-selects.
func initialThesisState(grounded bool, confidence string) string {
	if grounded || confidence == ThesisConfidenceAlta {
		return ThesisStatePendingAdd
	}
	return ThesisStateOff
}

// ── Attachment (Fatia 2) ──────────────────────────────────────────────────────

// Attachment is the join between a draft and an uploaded document. It represents
// one exhibit the advogado has attached to the peça. The document itself lives in
// the document slice; this entity owns only the link metadata (category, position).
type Attachment struct {
	ID         string
	TenantID   string
	DraftID    string
	DocumentID string
	Name       string // document.title, falling back to original_filename
	Category   AttachmentCategory
	MimeType   string
	SizeBytes  int64
	Status     string // mirrors document.status (always UPLOADED in the read model)
	Position   int
	CreatedAt  time.Time
}

// AttachmentCategory is the closed set of labels the advogado can assign to an
// attachment. The same set is enforced by the DB CHECK constraint.
type AttachmentCategory string

const (
	CategoryProcuracao                 AttachmentCategory = "Procuração"
	CategoryComprovante                AttachmentCategory = "Comprovante de endereço"
	CategoryContrato                   AttachmentCategory = "Contrato"
	CategoryProvasDocumentais          AttachmentCategory = "Provas documentais"
	CategoryDeclaracaoHipossuficiencia AttachmentCategory = "Declaração de hipossuficiência"
	CategoryOutro                      AttachmentCategory = "Outro"
)

// validAttachmentCategories is the lookup for validation (mirrors the DB CHECK).
var validAttachmentCategories = map[AttachmentCategory]bool{
	CategoryProcuracao:                 true,
	CategoryComprovante:                true,
	CategoryContrato:                   true,
	CategoryProvasDocumentais:          true,
	CategoryDeclaracaoHipossuficiencia: true,
	CategoryOutro:                      true,
}

// IsValidCategory reports whether cat is a member of the closed set.
func IsValidCategory(cat AttachmentCategory) bool {
	return validAttachmentCategories[cat]
}

// documentForAttachment is the minimal document state the attachment use case loads
// before linking. It carries only the fields needed for the guard checks; the full
// document entity lives in the document slice (imported by the read query via JOIN,
// never via Go import). This is an internal type — not exported.
type documentForAttachment struct {
	ID       string
	TenantID string
	Status   string
	Origin   string
}

// documentStatus mirrors the document status constants used in validation —
// kept as local constants so the draft slice never imports the document slice.
const (
	documentStatusUploaded = "UPLOADED"
	documentOriginUpload   = "UPLOAD"
)

// ── Status constants (Fatia 4 — peticionamento) ─────────────────────────────

// Status is the milestone lifecycle of the peça. It is distinct from saga_state
// (which tracks the async AI generation pipeline). The CHECK constraint on
// draft.status enforces the closed set at the DB level.
const (
	StatusDraft    = "DRAFT"
	StatusReviewed = "REVIEWED"
	StatusSigned   = "SIGNED"
)

// validDraftStatuses is the lookup used by validation.
var validDraftStatuses = map[string]bool{
	StatusDraft:    true,
	StatusReviewed: true,
	StatusSigned:   true,
}

// ── Saga state constants (Fatia 3) ───────────────────────────────────────────

// The saga_state column on draft tracks the AI generation lifecycle. No DB CHECK is
// added (the init migration has no CHECK on saga_state), so the enforcement is in the
// application layer (use case guard + handler guard).
const (
	SagaStateCreated    = "CREATED"
	SagaStateExtracting = "EXTRACTING"
	// SagaStateDrafted is set after Gerar completes: the draft has content but no
	// AI review yet. The advogado can then trigger Revisar to produce suggestions.
	SagaStateDrafted  = "DRAFTED"
	SagaStateReviewed = "REVIEWED"
	SagaStateFiled    = "FILED"
	SagaStateFailed   = "FAILED"
)

// ── Review (AI parecer) ────────────────────────────────────────────────────

// Review is one AI-generated review for a draft. Multiple reviews may exist (one per
// generation attempt). The read model exposes only the LATEST (by generated_at DESC).
type Review struct {
	ID           string
	DraftID      string
	Findings     []Finding
	Coverage     Coverage
	ModelVersion string
	RulesVersion string
	Status       string // COMPLETED | FAILED
	GeneratedAt  time.Time
	CreatedAt    time.Time
}

// ReviewStatus closed set.
const (
	ReviewStatusCompleted = "COMPLETED"
	ReviewStatusFailed    = "FAILED"
)

// Finding is one AI suggestion mapped to an exact substring of draft.content.
// category drives citation requirements (Argumento/Coerência → citation required).
type Finding struct {
	N           int       `json:"n"`
	Category    string    `json:"category"`
	Original    string    `json:"original"`
	Replacement string    `json:"replacement"`
	Problem     string    `json:"problem"`
	Description string    `json:"description"`
	Citation    *Citation `json:"citation,omitempty"`
}

// Citation anchors a finding to a specific chunk from the case corpus.
type Citation struct {
	DocumentID string `json:"document_id"`
	Page       int    `json:"page"`
	Quote      string `json:"quote"`
}

// Coverage summarizes the grounding and filtering results of one generation run.
type Coverage struct {
	Grounded           bool     `json:"grounded"`
	ChunksUsed         int      `json:"chunks_used"`
	SuggestionsTotal   int      `json:"suggestions_total"`
	SuggestionsDropped int      `json:"suggestions_dropped"`
	DocumentsCited     []string `json:"documents_cited"`
	// Error is non-empty only for FAILED reviews — the human-readable reason.
	Error string `json:"error,omitempty"`
}

// FindingCategory is the closed set of suggestion categories.
const (
	CategoryClareza   = "Clareza"
	CategoryArgumento = "Argumento"
	CategoryCoerencia = "Coerência"
	CategoryEstilo    = "Estilo"
)

// citationRequired reports whether a finding of the given category must include a citation
// (true for Argumento and Coerência — the factual categories that require grounding in the
// case corpus). Clareza and Estilo are stylistic; citation is optional.
func citationRequired(category string) bool {
	return category == CategoryArgumento || category == CategoryCoerencia
}

// ── Chat (Fatia 3b) ───────────────────────────────────────────────────────────

// ChatMessage is one turn in the multi-turn grounded chat thread for a draft. Each
// call to AnswerQuestion appends two rows: one role='user' and one role='assistant'.
// The thread is scoped to a draft; isolation is via JOIN draft.tenant_id (same
// pattern as review — no tenant_id column, no RLS on this table; barrier-1 is the
// enforced guard).
type ChatMessage struct {
	ID           string
	DraftID      string
	Role         string // "user" | "assistant"
	Content      string
	Citations    []Citation
	Grounded     bool
	ModelVersion string // non-empty only for role="assistant"
	CreatedAt    time.Time
}

// ChatRole closed set.
const (
	ChatRoleUser      = "user"
	ChatRoleAssistant = "assistant"
)

// inferPieceType classifies the peça type when the client omits piece_type. It is
// the SINGLE source of truth for creation-time inference and is CONTENT-FIRST: the
// real signal lives in the teor da intimação (the DJEN type alone is ambiguous — the
// same "INTIMACAO" covers a defense, a manifestation, or a recursal window). It uses
// the type + class + subject + the HTML-stripped teor, is high-precision (conservative
// keyword match), and falls back to OTHER rather than mislabel. The generation LLM
// still adapts the actual peça to the teor; this drives the UI label and prompt hint.
//
// Precedence (most specific first):
//   - APPEAL  — a decision was rendered and a recursal window opened
//   - DEFENSE — cited to defend, or embargos/impugnação (execução/cumprimento)
//   - MOTION  — ordered to manifest/say/indicate (manifestação incidental)
//   - DEFENSE — fallback: an INTIMACAO with no content signal (historical default)
//   - OTHER   — no signal and not an INTIMACAO/CITACAO
//
// Note: the class "Execução" alone does NOT imply DEFENSE — the recipient may be the
// exequente ordered to indicate assets (→ MOTION). Only the content disambiguates.
func inferPieceType(it *IntimationContext) string {
	if it == nil {
		return PieceTypeOther
	}
	blob := strings.ToLower(strings.Join(
		[]string{it.Type, it.Class, it.Subject, stripHTML(it.Content)}, " "))

	switch {
	case containsAny(blob, "sentença", "acórdão", "recurso inominado", "prazo recursal",
		"para recorrer", "interpor recurso", "apelaç", "julgo procedente", "julgo improcedente"):
		return PieceTypeAppeal
	case it.Type == "CITACAO",
		containsAny(blob, "conteste", "contestação", "apresentar defesa", "oferecer defesa",
			"embargos à execução", "embargos do executado", "impugnação ao cumprimento"):
		return PieceTypeDefense
	case containsAny(blob, "manifeste-se", "manifestar-se", "manifestação", "diga sobre",
		"indique bens", "indicar bens", "requeira o que"):
		return PieceTypeMotion
	case it.Type == "INTIMACAO":
		// Fallback: an INTIMACAO with no recognized content signal defaults to DEFENSE
		// (the historical default) — better a sane hint than OTHER when the teor is
		// thin/empty (scraping gap). Content signals above still win (APPEAL/MOTION).
		return PieceTypeDefense
	default:
		return PieceTypeOther
	}
}

// containsAny reports whether s contains any of subs (all expected pre-lowercased).
func containsAny(s string, subs ...string) bool {
	for _, sub := range subs {
		if strings.Contains(s, sub) {
			return true
		}
	}
	return false
}

// pieceTypeByProfileKey is a LOCAL, hardcoded copy of the v1 piece_profile catalog
// (migration 0085, docs/erd-tipos-de-peca.md §6) mapping each known catalog key to
// the draft.piece_type (the closed set above) it corresponds to. Copied — not a
// query against piece_profile — for the same reason internal/actionitem/entity.go's
// knownPieceProfileKeys is local: this slice never imports actionitem/pieceprofile
// (slices never import another slice's domain), and the piece_profile FK is the
// real source of truth at insert time. Extend this map when the catalog grows
// (docs/erd-tipos-de-peca.md §6) — divergence here only falls back to
// inferPieceType, it never breaks the FK.
var pieceTypeByProfileKey = map[string]string{
	"peticao_inicial": PieceTypeComplaint,
	"contestacao":     PieceTypeDefense,
	"apelacao":        PieceTypeAppeal,
}

// pieceTypeFromProfileKey resolves the draft.piece_type the task-sourced Create
// flow should use for a given piece_profile_key — the providência's TYPE,
// INHERITED, never re-chosen (docs/erd-costura-providencia-tarefa-peca.md §3). ok
// is false when key is not in the local map (empty key — gera_peca=false — or a
// catalog key this slice doesn't know about yet); the caller falls back to
// inferPieceType in that case.
func pieceTypeFromProfileKey(key string) (pieceType string, ok bool) {
	pieceType, ok = pieceTypeByProfileKey[key]
	return pieceType, ok
}

// defaultProfileByPieceType is the reverse of pieceTypeByProfileKey: the catalog
// key a source=intimation draft should default to for a given draft.piece_type,
// used by Create's PART A fallback when the intimation has no peça-generating
// action_item that already chose a key. MOTION/OTHER map to no profile ("") —
// they fall back to the generic (non-profile) generation structure. Same local-
// copy rationale as pieceTypeByProfileKey (this slice never imports the catalog).
var defaultProfileByPieceType = map[string]string{
	PieceTypeDefense:   "contestacao",
	PieceTypeComplaint: "peticao_inicial",
	PieceTypeAppeal:    "apelacao",
}

// defaultProfileForPieceType resolves the catalog piece_profile_key a draft of the
// given piece_type defaults to when no action_item already picked one (PART A
// fallback). Returns "" for types with no catalog mapping (MOTION, OTHER, or any
// unknown value) — the draft then carries no profile and the generation renders the
// generic Fatos/Direito/Pedidos structure.
func defaultProfileForPieceType(pieceType string) string {
	return defaultProfileByPieceType[pieceType]
}

// ── Petition (Fatia 4 — peticionamento) ─────────────────────────────────────

// Petition is a signed, filed peça. It is immutable after creation. No tenant_id
// directly — isolation is via the draft FK (JOIN draft.tenant_id).
type Petition struct {
	ID             string
	DraftID        string
	CourtRecordID  string
	FiledAt        time.Time
	Receipt        map[string]any
	ObservedResult string // empty until observed
}

// ObservedResult closed set — the outcome the advogado records after the petition
// is filed.
const (
	ObservedResultOK          = "OK"
	ObservedResultAmendment   = "AMENDMENT"
	ObservedResultNotAdmitted = "NOT_ADMITTED"
	ObservedResultUntimely    = "UNTIMELY"
)

// validObservedResults is the lookup used by validation.
var validObservedResults = map[string]bool{
	ObservedResultOK:          true,
	ObservedResultAmendment:   true,
	ObservedResultNotAdmitted: true,
	ObservedResultUntimely:    true,
}

// ── Coverage summary (Fatia 4 — list read model) ────────────────────────────

// CoverageSummary is the trimmed review snapshot exposed in list endpoints.
// It comes from the most recent review for a draft.
type CoverageSummary struct {
	Grounded         bool `json:"grounded"`
	ChunksUsed       int  `json:"chunks_used"`
	SuggestionsTotal int  `json:"suggestions_total"`
}

// ── List read models (Fatia 4) ──────────────────────────────────────────────

// DraftListItem is one row in the paginated list of peças. It carries the
// fields the client needs for the list card — not the full aggregate.
type DraftListItem struct {
	ID              string
	PieceType       string
	Title           string
	Status          string
	SagaState       string
	CoverageSummary *CoverageSummary
	// Workflow timestamps — o FE deriva o step visível (Rascunho, Aguardando
	// assinatura, Aguardando protocolo, Protocolada) a partir do combo dos 3.
	SentToSigningAt *time.Time
	SignedAt        *time.Time
	FiledAt         *time.Time
	ObservedResult  *string
	CreatedAt       time.Time
	// Contexto do processo — pra mostrar CNJ no card sem 2ª chamada.
	CNJNumber string
	// Nome do autor da peça (join com app_user via created_by). Vazio pra
	// peças pré-migration 0063 ou quando o usuário foi removido do escritório.
	ResponsibleName string
	// Prazo da intimação de origem (join com deadline via notification_id) —
	// alimenta chips "Prazo em atraso"/"Prazo hoje" e o rótulo colorido no
	// card. Ambos nil quando não há deadline derivado.
	DeadlineEndDate  *time.Time
	DeadlineDaysLeft *int32
}

// DraftListResult is a page of peças plus whether a further page exists. Total
// is a separate COUNT(*) matching the exact same WHERE as the list query (no
// filtered-vs-tenant-wide distinction — single number, mirrors deadline's
// PrazosByProcessoResult).
type DraftListResult struct {
	Items   []DraftListItem
	HasMore bool
	Total   int64
}
