package draft

import (
	"time"

	"github.com/jusassessoria/platform/internal/draft/draftdb"
)

// DraftDetailView is the read model for GET /v1/pecas/:id. It is a dedicated
// projection from the JOIN query — not the aggregate mounted in Go — so the handler
// never builds the aggregated entity for a read. All nested structs are nil when the
// draft has no intimation.
type DraftDetailView struct {
	ID        string
	PieceType string
	Title     string
	Content   string
	Status    string
	SagaState string
	CreatedAt time.Time
	UpdatedAt time.Time

	// StructuredContent is the block-structured version of the peça (Peça v2,
	// migration 0056). Non-nil for drafts generated by the Fatia B pipeline or
	// backfilled by the lazy parser; nil for empty drafts (no content yet).
	// The FE consumes this directly to render section cards.
	StructuredContent *StructuredContent
	// ContentHtml carrega a peça em HTML rico do editor Tiptap (Fase B).
	// Nil para peças legacy ou recém-geradas (structured_content ainda é a
	// fonte). Quando não-nil, source-of-truth pro renderer PDF (Fase C).
	ContentHtml *string
	// Authorship is "assistant" (default, FE shows Iterar tab) or "human_taken"
	// (advogado assumiu autoria, FE shows Revisão tab). See migration 0056.
	Authorship string

	// Workflow timestamps (0060) — cada fato datado; a UI deriva o step atual:
	//   sent_to_signing_at IS NULL                             → Construção
	//   sent_to_signing_at ≠ NULL, signed_at IS NULL           → Assinatura
	//   signed_at ≠ NULL, filed_at IS NULL                     → Protocolo
	//   filed_at ≠ NULL                                        → Concluído
	SentToSigningAt *time.Time
	SignedAt        *time.Time
	FiledAt         *time.Time
	FilingNumber    string // número/protocolo do tribunal (opcional; input manual)
	// SignedPDFKey é o storage key interno do PDF assinado (Fatia 2b — 0061).
	// O handler o converte em signed_pdf_url (presigned GET) antes de responder;
	// o cliente nunca vê o key cru. Vazio antes de assinar.
	SignedPDFKey string

	// Intimation is nil for blank/processo drafts.
	Intimation *IntimationView
	// Process is nil when no intimation (and therefore no court_record) is linked.
	Process *ProcessView
	// Deadline is nil when no deadline has been derived for the intimation yet.
	Deadline *DeadlineView
	// Attachments is the ordered list of uploaded documents linked to this draft.
	// Empty slice (never nil) when no attachments exist.
	Attachments []Attachment

	// Providences is the list of tasks linked to the draft's intimation, shown
	// in the FE sidebar (Peça v2). Empty slice for drafts without an intimation
	// or with no linked tasks.
	Providences []Providence

	// Parties is the list of parties (autor / réu / terceiro) of the peça's case
	// with their aggregated counsels, shown in the FE sidebar (Peça v2 — bloco
	// PARTES). Empty slice for drafts without a process (blank drafts) or when
	// the case genuinely has no party materialized yet.
	Parties []PartyInfo

	// Review is the latest AI-generated review for this draft, or nil when no
	// generation has been run yet (saga_state == CREATED or EXTRACTING with no
	// prior attempt).
	Review *Review
}

// IntimationView is the context the editor shows alongside the draft text.
type IntimationView struct {
	ID              string
	Type            string
	Content         string
	MadeAvailableAt time.Time
	DeadlineStartAt time.Time
}

// ProcessView is the processo context — from court_record — shown in the editor
// sidebar. Plaintiffs/Defendants feed the "Partes" block of the peça's Contexto
// panel (read directly from party + court_record, no acquisition import — same
// decision as the court_record columns).
type ProcessView struct {
	CaseID        string
	CourtRecordID string
	CNJNumber     string
	Court         string
	Degree        string
	Class         string
	Subject       string
	JudgingBody   string
	// Plaintiffs (autor/polo ativo) and Defendants (réu/polo passivo) are the party
	// names for the case, never nil (empty slice when none). A litisconsórcio yields
	// multiple names.
	Plaintiffs []string
	Defendants []string
}

// DeadlineView is the prazo context shown in the editor header bar. DaysLeft is
// computed at query time from end_date; the handler derives it for the response.
type DeadlineView struct {
	ID      string
	EndDate time.Time
	Status  string
}

// detailViewFromRow maps the GetDraftDetail row to the read model. All nested
// structs are populated only when their anchor id is non-NULL (the LEFT JOIN may
// yield NULLs for a blank/processo draft).
func detailViewFromRow(r draftdb.GetDraftDetailRow) *DraftDetailView {
	view := &DraftDetailView{
		ID:                r.ID.String(),
		PieceType:         r.PieceType,
		Title:             r.Title,
		Content:           derefString(r.Content),
		Status:            r.Status,
		SagaState:         r.SagaState,
		CreatedAt:         timestamptzToTime(r.CreatedAt),
		UpdatedAt:         timestamptzToTime(r.UpdatedAt),
		StructuredContent: structuredContentFromJSON(r.StructuredContent),
		ContentHtml:       r.ContentHtml,
		Authorship:        r.Authorship,
		Attachments:       []Attachment{}, // never nil — serializes as [] not null
		Providences:       []Providence{}, // never nil
		Parties:           []PartyInfo{},  // never nil
		SentToSigningAt:   pgTimestamptzPtr(r.SentToSigningAt),
		SignedAt:          pgTimestamptzPtr(r.SignedAt),
		FiledAt:           pgTimestamptzPtr(r.FiledAt),
		FilingNumber:      derefString(r.FilingNumber),
		SignedPDFKey:      derefString(r.SignedPdfKey),
	}

	// Intimation — only when the draft has an intimation_id (LEFT JOIN yields a
	// valid UUID when present).
	if r.IntimationID.Valid {
		view.Intimation = &IntimationView{
			ID:              pgUUIDToString(r.IntimationID),
			Type:            derefString(r.IntimationType),
			Content:         derefString(r.IntimationContent),
			MadeAvailableAt: pgDateToTime(r.IntimationMadeAvailableAt),
			DeadlineStartAt: pgDateToTime(r.IntimationDeadlineStartAt),
		}
	}

	// Process — only when a court_record was joined (requires intimation).
	if r.ProcessCourtRecordID.Valid {
		view.Process = &ProcessView{
			CaseID:        pgUUIDToString(r.ProcessCaseID),
			CourtRecordID: pgUUIDToString(r.ProcessCourtRecordID),
			CNJNumber:     derefString(r.ProcessCnjNumber),
			Court:         derefString(r.ProcessCourt),
			Degree:        derefString(r.ProcessDegree),
			Class:         derefString(r.ProcessClass),
			Subject:       derefString(r.ProcessSubject),
			JudgingBody:   derefString(r.ProcessJudgingBody),
			Plaintiffs:    nonNilStrings(r.ProcessPlaintiffs),
			Defendants:    nonNilStrings(r.ProcessDefendants),
		}
	}

	// Deadline — only when one has been derived for this intimation.
	if r.DeadlineID.Valid {
		view.Deadline = &DeadlineView{
			ID:      pgUUIDToString(r.DeadlineID),
			EndDate: pgDateToTime(r.DeadlineEndDate),
			Status:  derefString(r.DeadlineStatus),
		}
	}

	return view
}
