// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: court.sql

package courtdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCourtConnectionByID = `-- name: GetCourtConnectionByID :one
SELECT id, tenant_id, app_user_id, court, system, authentication_method, credential_ref, certificate_ref, mfa_seed_ref, session_ref, status, last_authenticated_at, error, created_at FROM court_connection
WHERE id = $1 AND tenant_id = $2
`

type GetCourtConnectionByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetCourtConnectionByID(ctx context.Context, arg GetCourtConnectionByIDParams) (CourtConnection, error) {
	row := q.db.QueryRow(ctx, getCourtConnectionByID, arg.ID, arg.TenantID)
	var i CourtConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AppUserID,
		&i.Court,
		&i.System,
		&i.AuthenticationMethod,
		&i.CredentialRef,
		&i.CertificateRef,
		&i.MfaSeedRef,
		&i.SessionRef,
		&i.Status,
		&i.LastAuthenticatedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantSecretByID = `-- name: GetTenantSecretByID :one
SELECT id, tenant_id, ciphertext, nonce, wrapped_dek, dek_nonce, created_at, updated_at FROM tenant_secret
WHERE id = $1 AND tenant_id = $2
`

type GetTenantSecretByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetTenantSecretByID(ctx context.Context, arg GetTenantSecretByIDParams) (TenantSecret, error) {
	row := q.db.QueryRow(ctx, getTenantSecretByID, arg.ID, arg.TenantID)
	var i TenantSecret
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Ciphertext,
		&i.Nonce,
		&i.WrappedDek,
		&i.DekNonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCourtConnection = `-- name: InsertCourtConnection :one
INSERT INTO court_connection (
  tenant_id, app_user_id, court, system, authentication_method,
  credential_ref, certificate_ref, status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, created_at
`

type InsertCourtConnectionParams struct {
	TenantID             uuid.UUID   `json:"tenant_id"`
	AppUserID            uuid.UUID   `json:"app_user_id"`
	Court                string      `json:"court"`
	System               string      `json:"system"`
	AuthenticationMethod string      `json:"authentication_method"`
	CredentialRef        pgtype.UUID `json:"credential_ref"`
	CertificateRef       pgtype.UUID `json:"certificate_ref"`
	Status               string      `json:"status"`
}

type InsertCourtConnectionRow struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertCourtConnection(ctx context.Context, arg InsertCourtConnectionParams) (InsertCourtConnectionRow, error) {
	row := q.db.QueryRow(ctx, insertCourtConnection,
		arg.TenantID,
		arg.AppUserID,
		arg.Court,
		arg.System,
		arg.AuthenticationMethod,
		arg.CredentialRef,
		arg.CertificateRef,
		arg.Status,
	)
	var i InsertCourtConnectionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertTenantSecret = `-- name: InsertTenantSecret :one
INSERT INTO tenant_secret (tenant_id, ciphertext, nonce, wrapped_dek, dek_nonce)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertTenantSecretParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	Ciphertext []byte    `json:"ciphertext"`
	Nonce      []byte    `json:"nonce"`
	WrappedDek []byte    `json:"wrapped_dek"`
	DekNonce   []byte    `json:"dek_nonce"`
}

func (q *Queries) InsertTenantSecret(ctx context.Context, arg InsertTenantSecretParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTenantSecret,
		arg.TenantID,
		arg.Ciphertext,
		arg.Nonce,
		arg.WrappedDek,
		arg.DekNonce,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listCourtConnectionsByTenant = `-- name: ListCourtConnectionsByTenant :many
SELECT id, tenant_id, app_user_id, court, system, authentication_method, credential_ref, certificate_ref, mfa_seed_ref, session_ref, status, last_authenticated_at, error, created_at FROM court_connection
WHERE tenant_id = $1
ORDER BY created_at
`

func (q *Queries) ListCourtConnectionsByTenant(ctx context.Context, tenantID uuid.UUID) ([]CourtConnection, error) {
	rows, err := q.db.Query(ctx, listCourtConnectionsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourtConnection
	for rows.Next() {
		var i CourtConnection
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AppUserID,
			&i.Court,
			&i.System,
			&i.AuthenticationMethod,
			&i.CredentialRef,
			&i.CertificateRef,
			&i.MfaSeedRef,
			&i.SessionRef,
			&i.Status,
			&i.LastAuthenticatedAt,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourtConnectionMFASeedRef = `-- name: UpdateCourtConnectionMFASeedRef :one
UPDATE court_connection
SET mfa_seed_ref = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id
`

type UpdateCourtConnectionMFASeedRefParams struct {
	ID         uuid.UUID   `json:"id"`
	TenantID   uuid.UUID   `json:"tenant_id"`
	MfaSeedRef pgtype.UUID `json:"mfa_seed_ref"`
}

func (q *Queries) UpdateCourtConnectionMFASeedRef(ctx context.Context, arg UpdateCourtConnectionMFASeedRefParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateCourtConnectionMFASeedRef, arg.ID, arg.TenantID, arg.MfaSeedRef)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateCourtConnectionStatus = `-- name: UpdateCourtConnectionStatus :one
UPDATE court_connection
SET status = $3,
    last_authenticated_at = $4,
    error = $5
WHERE id = $1 AND tenant_id = $2
RETURNING id
`

type UpdateCourtConnectionStatusParams struct {
	ID                  uuid.UUID          `json:"id"`
	TenantID            uuid.UUID          `json:"tenant_id"`
	Status              string             `json:"status"`
	LastAuthenticatedAt pgtype.Timestamptz `json:"last_authenticated_at"`
	Error               []byte             `json:"error"`
}

func (q *Queries) UpdateCourtConnectionStatus(ctx context.Context, arg UpdateCourtConnectionStatusParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateCourtConnectionStatus,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.LastAuthenticatedAt,
		arg.Error,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
