// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package courtdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetCourtConnectionByID(ctx context.Context, arg GetCourtConnectionByIDParams) (CourtConnection, error)
	GetTenantSecretByID(ctx context.Context, arg GetTenantSecretByIDParams) (TenantSecret, error)
	InsertCourtConnection(ctx context.Context, arg InsertCourtConnectionParams) (InsertCourtConnectionRow, error)
	InsertTenantSecret(ctx context.Context, arg InsertTenantSecretParams) (uuid.UUID, error)
	ListCourtConnectionsByTenant(ctx context.Context, tenantID uuid.UUID) ([]CourtConnection, error)
	UpdateCourtConnectionMFASeedRef(ctx context.Context, arg UpdateCourtConnectionMFASeedRefParams) (uuid.UUID, error)
	UpdateCourtConnectionStatus(ctx context.Context, arg UpdateCourtConnectionStatusParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
