// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deadline.sql

package deadlinedb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmDeadline = `-- name: ConfirmDeadline :one
UPDATE deadline
SET status           = 'OPEN',
    kind             = $3,
    days             = $4,
    counting         = $5,
    doubled          = $6,
    doubled_reason   = $7,
    end_date         = $8,
    holidays_applied = $9,
    confirmed_by     = $10,
    confirmed_at     = $11
WHERE notification_id = $1 AND tenant_id = $2
RETURNING id, court_record_id
`

type ConfirmDeadlineParams struct {
	NotificationID  uuid.UUID          `json:"notification_id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	Kind            *string            `json:"kind"`
	Days            int32              `json:"days"`
	Counting        string             `json:"counting"`
	Doubled         bool               `json:"doubled"`
	DoubledReason   *string            `json:"doubled_reason"`
	EndDate         pgtype.Date        `json:"end_date"`
	HolidaysApplied []byte             `json:"holidays_applied"`
	ConfirmedBy     pgtype.UUID        `json:"confirmed_by"`
	ConfirmedAt     pgtype.Timestamptz `json:"confirmed_at"`
}

type ConfirmDeadlineRow struct {
	ID            uuid.UUID `json:"id"`
	CourtRecordID uuid.UUID `json:"court_record_id"`
}

// The F2 confirmation (§9: "Aprovar tudo" grava o deadline PENDING→OPEN recalculado).
// Flips the prazo to OPEN with the human-approved {kind, days, counting, doubled,
// doubled_reason} and the RECOMPUTED {end_date, holidays_applied}, stamping who/when
// (confirmed_by/at). Keyed by the 1:1 notification_id and scoped to tenant_id (barrier
// 1). IDEMPOTENT on the deadline: re-confirming the same intimação re-UPDATEs the one row
// (the 1:1 notification_id) — it never opens a second prazo. source/start_date/
// rules_version are LEFT AS-IS: source keeps its provenance (RULE/AI), start_date is the
// fixed anchor, and rules_version still records which rule set first derived the prazo
// even when the human overrode the days. A no-match (no prazo for the intimação) yields
// NO row → pgx.ErrNoRows → ErrDeadlineNotFound at the mapper. $1 = intimation_id, $2 =
// tenant_id, then the confirmed fields.
func (q *Queries) ConfirmDeadline(ctx context.Context, arg ConfirmDeadlineParams) (ConfirmDeadlineRow, error) {
	row := q.db.QueryRow(ctx, confirmDeadline,
		arg.NotificationID,
		arg.TenantID,
		arg.Kind,
		arg.Days,
		arg.Counting,
		arg.Doubled,
		arg.DoubledReason,
		arg.EndDate,
		arg.HolidaysApplied,
		arg.ConfirmedBy,
		arg.ConfirmedAt,
	)
	var i ConfirmDeadlineRow
	err := row.Scan(&i.ID, &i.CourtRecordID)
	return i, err
}

const deleteTasksByDeadline = `-- name: DeleteTasksByDeadline :exec
DELETE FROM task
WHERE deadline_id = $1 AND tenant_id = $2
`

type DeleteTasksByDeadlineParams struct {
	DeadlineID pgtype.UUID `json:"deadline_id"`
	TenantID   uuid.UUID   `json:"tenant_id"`
}

// Drop every task of a confirmed prazo, the REPLACE step of the F2 confirm (§9: the
// confirm is an "upsert idempotente por intimation_id"). Confirm runs this in the SAME tx
// right after ConfirmDeadline and BEFORE re-inserting the submitted tasks, so re-confirming
// the same intimação leaves EXACTLY the last submit's set instead of accumulating +N rows
// each call. Scoped to tenant_id (barrier 1, on top of RLS barrier 2). A first confirm (no
// prior tasks) deletes nothing — a clean no-op, never an error. $1 = deadline_id, $2 =
// tenant_id, both from the confirm tx (the id ConfirmDeadline returned + the principal).
func (q *Queries) DeleteTasksByDeadline(ctx context.Context, arg DeleteTasksByDeadlineParams) error {
	_, err := q.db.Exec(ctx, deleteTasksByDeadline, arg.DeadlineID, arg.TenantID)
	return err
}

const getCourtRecordClass = `-- name: GetCourtRecordClass :one

SELECT class
FROM court_record
WHERE id = $1 AND tenant_id = $2
`

type GetCourtRecordClassParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// deadline slice queries (the prazos CREATION path). Every write and read runs inside
// the use case's transaction so RLS scopes it to the event's tenant (barrier 2) on top
// of the explicit tenant filter (barrier 1). Absence is a typed error at the mapper,
// never (nil, nil).
// Read the rito signal (class) for the record the intimação hangs on — the one
// cross-table read the derivation needs (decisão P1: read the table, never import the
// acquisition package). A missing record → pgx.ErrNoRows → typed not-found at the
// mapper. class itself may be NULL (mapped to "").
// tenant_id is filtered explicitly (barrier 1) even though RLS (barrier 2) already
// scopes the tx: a NULL app.tenant_id or an RLS regression would otherwise let a read
// cross tenants. $2 = tenant_id, from the trusted event payload (never the body).
func (q *Queries) GetCourtRecordClass(ctx context.Context, arg GetCourtRecordClassParams) (*string, error) {
	row := q.db.QueryRow(ctx, getCourtRecordClass, arg.ID, arg.TenantID)
	var class *string
	err := row.Scan(&class)
	return class, err
}

const getCourtRecordCourt = `-- name: GetCourtRecordCourt :one
SELECT court
FROM court_record
WHERE id = $1 AND tenant_id = $2
`

type GetCourtRecordCourtParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Read the court sigla for the record the prazo hangs on — the confirmation recompute
// derives the UF from it (pkg/tribunal.UF) for the state-holiday calendar lookup, the
// confirm-path counterpart of GetCourtRecordClass. Scoped to tenant_id (barrier 1). A
// missing record → pgx.ErrNoRows → typed not-found at the mapper. court is NOT NULL.
// $1 = id, $2 = tenant_id, both from the trusted principal's request context.
func (q *Queries) GetCourtRecordCourt(ctx context.Context, arg GetCourtRecordCourtParams) (string, error) {
	row := q.db.QueryRow(ctx, getCourtRecordCourt, arg.ID, arg.TenantID)
	var court string
	err := row.Scan(&court)
	return court, err
}

const getDeadlineForAdjust = `-- name: GetDeadlineForAdjust :one
SELECT id, court_record_id, start_date, status, kind, days, counting, doubled, doubled_reason
FROM deadline
WHERE id = $1 AND tenant_id = $2
`

type GetDeadlineForAdjustParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetDeadlineForAdjustRow struct {
	ID            uuid.UUID   `json:"id"`
	CourtRecordID uuid.UUID   `json:"court_record_id"`
	StartDate     pgtype.Date `json:"start_date"`
	Status        string      `json:"status"`
	Kind          *string     `json:"kind"`
	Days          int32       `json:"days"`
	Counting      string      `json:"counting"`
	Doubled       bool        `json:"doubled"`
	DoubledReason *string     `json:"doubled_reason"`
}

// Load a prazo's FULL adjustable state — the F2 ajuste manual (§9: PATCH /v1/prazos/:id)
// reads it BEFORE the recompute: start_date is the fixed anchor the calendar re-counts
// from, court_record_id feeds the court lookup (recompute UF), and the CURRENT
// {kind, days, counting, doubled, doubled_reason} are the base the partial patch is applied
// over (a field absent from the body keeps its stored value). status gates the ajuste (only
// a PENDING/OPEN prazo is adjustable). Keyed by id and scoped to tenant_id (barrier 1, on top
// of RLS barrier 2). A missing id in the tenant → pgx.ErrNoRows → typed ErrDeadlineNotFound at
// the mapper (→ 404), never (nil, nil). $1 = id, $2 = tenant_id (from the principal).
func (q *Queries) GetDeadlineForAdjust(ctx context.Context, arg GetDeadlineForAdjustParams) (GetDeadlineForAdjustRow, error) {
	row := q.db.QueryRow(ctx, getDeadlineForAdjust, arg.ID, arg.TenantID)
	var i GetDeadlineForAdjustRow
	err := row.Scan(
		&i.ID,
		&i.CourtRecordID,
		&i.StartDate,
		&i.Status,
		&i.Kind,
		&i.Days,
		&i.Counting,
		&i.Doubled,
		&i.DoubledReason,
	)
	return i, err
}

const getDeadlineForCheck = `-- name: GetDeadlineForCheck :one
SELECT id, status, end_date, court_record_id, kind, counting
FROM deadline
WHERE id = $1 AND tenant_id = $2
`

type GetDeadlineForCheckParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetDeadlineForCheckRow struct {
	ID            uuid.UUID   `json:"id"`
	Status        string      `json:"status"`
	EndDate       pgtype.Date `json:"end_date"`
	CourtRecordID uuid.UUID   `json:"court_record_id"`
	Kind          *string     `json:"kind"`
	Counting      string      `json:"counting"`
}

// Re-read a prazo at a scheduled mark's fire time (deadline.reminder_check): the CURRENT
// status the fire handler branches on, plus the end_date and the context (kind, counting,
// court_record_id) a lembrete or MISSED fact may carry. Keyed by id and scoped to tenant_id
// (barrier 1, on top of RLS barrier 2). A missing id in the tenant → pgx.ErrNoRows → typed
// ErrDeadlineNotFound at the mapper, never (nil, nil). $1 = id, $2 = tenant_id, both from
// the trusted scheduled-event payload.
func (q *Queries) GetDeadlineForCheck(ctx context.Context, arg GetDeadlineForCheckParams) (GetDeadlineForCheckRow, error) {
	row := q.db.QueryRow(ctx, getDeadlineForCheck, arg.ID, arg.TenantID)
	var i GetDeadlineForCheckRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.EndDate,
		&i.CourtRecordID,
		&i.Kind,
		&i.Counting,
	)
	return i, err
}

const getDeadlineForConfirm = `-- name: GetDeadlineForConfirm :one
SELECT id, court_record_id, start_date
FROM deadline
WHERE notification_id = $1 AND tenant_id = $2
`

type GetDeadlineForConfirmParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	TenantID       uuid.UUID `json:"tenant_id"`
}

type GetDeadlineForConfirmRow struct {
	ID            uuid.UUID   `json:"id"`
	CourtRecordID uuid.UUID   `json:"court_record_id"`
	StartDate     pgtype.Date `json:"start_date"`
}

// Load a PENDING prazo's confirmation anchor — the F2 "Aprovar tudo" (§9) reads it
// BEFORE the recompute: start_date is the fixed anchor of the calendar math (=
// intimation.deadline_start_at, already persisted at derivation), court_record_id feeds
// both the court lookup (for the recompute UF) and the inserted tasks. Keyed by the 1:1
// notification_id (=intimation id) and scoped to tenant_id (barrier 1, on top of RLS
// barrier 2). A missing prazo → pgx.ErrNoRows → typed ErrDeadlineNotFound at the mapper,
// never (nil, nil): confirming an intimação with no derived prazo is a 404 at the edge.
// $1 = intimation_id (the notification_id column), $2 = tenant_id (from the principal).
func (q *Queries) GetDeadlineForConfirm(ctx context.Context, arg GetDeadlineForConfirmParams) (GetDeadlineForConfirmRow, error) {
	row := q.db.QueryRow(ctx, getDeadlineForConfirm, arg.NotificationID, arg.TenantID)
	var i GetDeadlineForConfirmRow
	err := row.Scan(&i.ID, &i.CourtRecordID, &i.StartDate)
	return i, err
}

const insertDeadline = `-- name: InsertDeadline :one
INSERT INTO deadline (
    tenant_id, court_record_id, notification_id,
    start_date, end_date, days, counting, doubled, doubled_reason,
    holidays_applied, status, source, kind, rules_version
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14
)
ON CONFLICT (notification_id) DO NOTHING
RETURNING id
`

type InsertDeadlineParams struct {
	TenantID        uuid.UUID   `json:"tenant_id"`
	CourtRecordID   uuid.UUID   `json:"court_record_id"`
	NotificationID  uuid.UUID   `json:"notification_id"`
	StartDate       pgtype.Date `json:"start_date"`
	EndDate         pgtype.Date `json:"end_date"`
	Days            int32       `json:"days"`
	Counting        string      `json:"counting"`
	Doubled         bool        `json:"doubled"`
	DoubledReason   *string     `json:"doubled_reason"`
	HolidaysApplied []byte      `json:"holidays_applied"`
	Status          string      `json:"status"`
	Source          string      `json:"source"`
	Kind            *string     `json:"kind"`
	RulesVersion    string      `json:"rules_version"`
}

// Persist the derived prazo, BORN PENDING (status), source RULE. Idempotent on the 1:1
// notification_id (UNIQUE): ON CONFLICT DO NOTHING yields NO row on a re-derivation, so
// the mapper reads pgx.ErrNoRows as "already exists" (ErrDeadlineExists) instead of
// poisoning the tx with a constraint error. confirmed_by/at stay NULL (no human aval
// yet — that is the F2 slice). Returns the DB-assigned id; the repo maps the rest from
// the input entity.
func (q *Queries) InsertDeadline(ctx context.Context, arg InsertDeadlineParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertDeadline,
		arg.TenantID,
		arg.CourtRecordID,
		arg.NotificationID,
		arg.StartDate,
		arg.EndDate,
		arg.Days,
		arg.Counting,
		arg.Doubled,
		arg.DoubledReason,
		arg.HolidaysApplied,
		arg.Status,
		arg.Source,
		arg.Kind,
		arg.RulesVersion,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertTask = `-- name: InsertTask :one
INSERT INTO task (
    tenant_id, court_record_id, deadline_id, intimation_id,
    title, description, kind, due_date, status, source, assignee_user_id, created_by
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id
`

type InsertTaskParams struct {
	TenantID       uuid.UUID   `json:"tenant_id"`
	CourtRecordID  pgtype.UUID `json:"court_record_id"`
	DeadlineID     pgtype.UUID `json:"deadline_id"`
	IntimationID   pgtype.UUID `json:"intimation_id"`
	Title          string      `json:"title"`
	Description    *string     `json:"description"`
	Kind           *string     `json:"kind"`
	DueDate        pgtype.Date `json:"due_date"`
	Status         string      `json:"status"`
	Source         string      `json:"source"`
	AssigneeUserID pgtype.UUID `json:"assignee_user_id"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

// Persist one F2 action item (§4: 1 legal prazo → N tasks, gravadas na MESMA tx do
// confirm). Born status='OPEN', source='MANUAL' (a human created it at confirmation —
// AI-suggested tasks are a later slice). All FKs but tenant_id are nullable per the 0024
// schema, but confirm always fills court_record_id/deadline_id/intimation_id/created_by
// (the prazo's context); assignee_user_id/due_date/description/kind are optional. Returns
// the DB-assigned id so task.created commits with it in the SAME tx. $1.. are the columns.
func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTask,
		arg.TenantID,
		arg.CourtRecordID,
		arg.DeadlineID,
		arg.IntimationID,
		arg.Title,
		arg.Description,
		arg.Kind,
		arg.DueDate,
		arg.Status,
		arg.Source,
		arg.AssigneeUserID,
		arg.CreatedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markDeadlineStatus = `-- name: MarkDeadlineStatus :one
UPDATE deadline
SET status = $1
WHERE id = $2 AND tenant_id = $3 AND status = $4
RETURNING id
`

type MarkDeadlineStatusParams struct {
	NewStatus     string    `json:"new_status"`
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	CurrentStatus string    `json:"current_status"`
}

// Manual lifecycle transition of a prazo (§9: POST /v1/prazos/:id/met | .../missed → marca
// cumprido/perdido). Flips status from current_status to new_status, keyed by id and scoped
// to tenant_id (barrier 1). The `status = current_status` guard makes the flip SAFE and
// IDEMPOTENT under concurrency: the caller pre-checks the transition (loading the prazo for a
// distinct not-found vs invalid-transition error), and this guard defends the write against a
// racing flip — a no-match (already transitioned) → pgx.ErrNoRows → typed not-found at the
// mapper. On a hit it returns the id so deadline.met/deadline.missed commits in the SAME tx.
func (q *Queries) MarkDeadlineStatus(ctx context.Context, arg MarkDeadlineStatusParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, markDeadlineStatus,
		arg.NewStatus,
		arg.ID,
		arg.TenantID,
		arg.CurrentStatus,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markMissed = `-- name: MarkMissed :one
UPDATE deadline
SET status = 'MISSED'
WHERE id = $1 AND tenant_id = $2 AND status = 'OPEN' AND end_date < CURRENT_DATE
RETURNING id
`

type MarkMissedParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Auto-mark a prazo MISSED at the D+1 carência (deadline.missed_check fire path). Scoped to
// tenant_id (barrier 1). The `status = 'OPEN' AND end_date < CURRENT_DATE` guard makes the
// flip SAFE and IDEMPOTENT (decisão travada: MISSED auto D+1 SÓ em OPEN — nunca perder um
// PENDING não confirmado): a redelivery, a PENDING/terminal prazo, or one not yet overdue
// updates NO row → pgx.ErrNoRows → typed not-found at the mapper, the use case's no-op
// (never a phantom deadline.missed). On a hit it returns the id so deadline.missed commits
// in the SAME tx. $1 = id, $2 = tenant_id, both from the trusted scheduled-event payload.
func (q *Queries) MarkMissed(ctx context.Context, arg MarkMissedParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, markMissed, arg.ID, arg.TenantID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const resolveDeadlineRule = `-- name: ResolveDeadlineRule :one
SELECT rules_version, kind, days, counting, doubled
FROM deadline_rule
WHERE rules_version = $1
  AND active
  AND (intimation_type = $2 OR intimation_type = '*')
  AND (court_prefix IS NULL OR $3 LIKE court_prefix || '%')
ORDER BY (intimation_type = $2) DESC,
         (court_prefix IS NOT NULL) DESC,
         length(coalesce(court_prefix, '')) DESC,
         priority DESC
LIMIT 1
`

type ResolveDeadlineRuleParams struct {
	RulesVersion   string  `json:"rules_version"`
	IntimationType string  `json:"intimation_type"`
	CourtPrefix    *string `json:"court_prefix"`
}

type ResolveDeadlineRuleRow struct {
	RulesVersion string `json:"rules_version"`
	Kind         string `json:"kind"`
	Days         int32  `json:"days"`
	Counting     string `json:"counting"`
	Doubled      bool   `json:"doubled"`
}

// Resolve the conservative rule for (intimation_type, court) in a rules version. The
// resolution lives HERE, in SQL (decisão travada, erd-prazos.md §8/§11): the most
// SPECIFIC active match wins, falling back to the '*' catch-all — so an unknown type
// still yields the safe GENERICO rule. Ordering, most specific first:
//  1. an exact intimation_type beats the '*' catch-all;
//  2. a court-specific rule (court_prefix set) beats an any-court rule;
//  3. a longer court_prefix is more specific than a shorter one;
//  4. finally, higher priority wins.
//
// $1 = rules_version, $2 = intimation_type, $3 = court. A court_prefix matches when the
// court sigla starts with it ($3 LIKE prefix || '%'); a NULL prefix matches any court.
func (q *Queries) ResolveDeadlineRule(ctx context.Context, arg ResolveDeadlineRuleParams) (ResolveDeadlineRuleRow, error) {
	row := q.db.QueryRow(ctx, resolveDeadlineRule, arg.RulesVersion, arg.IntimationType, arg.CourtPrefix)
	var i ResolveDeadlineRuleRow
	err := row.Scan(
		&i.RulesVersion,
		&i.Kind,
		&i.Days,
		&i.Counting,
		&i.Doubled,
	)
	return i, err
}

const revokeDeadlineByIntimation = `-- name: RevokeDeadlineByIntimation :one
UPDATE deadline
SET status = 'CANCELLED'
WHERE notification_id = $1 AND tenant_id = $2 AND status <> 'CANCELLED'
RETURNING id, court_record_id
`

type RevokeDeadlineByIntimationParams struct {
	NotificationID uuid.UUID `json:"notification_id"`
	TenantID       uuid.UUID `json:"tenant_id"`
}

type RevokeDeadlineByIntimationRow struct {
	ID            uuid.UUID `json:"id"`
	CourtRecordID uuid.UUID `json:"court_record_id"`
}

// Revoke (CANCEL) the prazo derived from an intimação the DJEN retracted (erd-prazos.md
// §7/§11: uma intimação retificada vira prazo-fantasma → deadline.revoked). Keyed by the
// 1:1 notification_id (=intimation id) and scoped to tenant_id (barrier 1, on top of RLS
// barrier 2). The `status <> 'CANCELLED'` guard makes the revoke IDEMPOTENT: a redelivery
// past the dedup — or a cancel that lands before any prazo exists, or on an already
// CANCELLED one — updates NO row → pgx.ErrNoRows → typed not-found at the mapper, the use
// case's safe no-op (never a phantom revoked). On a hit it returns the revoked id (+ the
// record it hung on) so deadline.revoked commits in the SAME tx. $1 = intimation_id (the
// notification_id column), $2 = tenant_id, both from the trusted event payload.
func (q *Queries) RevokeDeadlineByIntimation(ctx context.Context, arg RevokeDeadlineByIntimationParams) (RevokeDeadlineByIntimationRow, error) {
	row := q.db.QueryRow(ctx, revokeDeadlineByIntimation, arg.NotificationID, arg.TenantID)
	var i RevokeDeadlineByIntimationRow
	err := row.Scan(&i.ID, &i.CourtRecordID)
	return i, err
}

const updateDeadlineAdjust = `-- name: UpdateDeadlineAdjust :one
UPDATE deadline
SET kind             = $3,
    days             = $4,
    counting         = $5,
    doubled          = $6,
    doubled_reason   = $7,
    end_date         = $8,
    holidays_applied = $9
WHERE id = $1 AND tenant_id = $2
RETURNING id, court_record_id
`

type UpdateDeadlineAdjustParams struct {
	ID              uuid.UUID   `json:"id"`
	TenantID        uuid.UUID   `json:"tenant_id"`
	Kind            *string     `json:"kind"`
	Days            int32       `json:"days"`
	Counting        string      `json:"counting"`
	Doubled         bool        `json:"doubled"`
	DoubledReason   *string     `json:"doubled_reason"`
	EndDate         pgtype.Date `json:"end_date"`
	HolidaysApplied []byte      `json:"holidays_applied"`
}

type UpdateDeadlineAdjustRow struct {
	ID            uuid.UUID `json:"id"`
	CourtRecordID uuid.UUID `json:"court_record_id"`
}

// Ajuste manual do prazo legal (§9: PATCH /v1/prazos/:id → recalcula datas). Writes the
// patched {kind, days, counting, doubled, doubled_reason} and the RECOMPUTED {end_date,
// holidays_applied} (from the fixed start_date), keyed by id and scoped to tenant_id (barrier
// 1). status is LEFT AS-IS: the ajuste never changes the lifecycle (a PENDING stays PENDING, an
// OPEN stays OPEN — the use case already refused a terminal prazo); source/start_date/
// rules_version/confirmed_* are untouched (the anchor and provenance persist). A no-match (the
// row vanished mid-tx) → pgx.ErrNoRows → ErrDeadlineNotFound at the mapper. Returns the prazo id
// and the record it hangs on. $1 = id, $2 = tenant_id, then the patched fields.
func (q *Queries) UpdateDeadlineAdjust(ctx context.Context, arg UpdateDeadlineAdjustParams) (UpdateDeadlineAdjustRow, error) {
	row := q.db.QueryRow(ctx, updateDeadlineAdjust,
		arg.ID,
		arg.TenantID,
		arg.Kind,
		arg.Days,
		arg.Counting,
		arg.Doubled,
		arg.DoubledReason,
		arg.EndDate,
		arg.HolidaysApplied,
	)
	var i UpdateDeadlineAdjustRow
	err := row.Scan(&i.ID, &i.CourtRecordID)
	return i, err
}
