// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package deadlinedb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// The filtered "X" of the agenda's "X de Y" counter: how many prazos match the active
	// @status / end_date window. Called only when a filter is present; the unfiltered "Y"
	// reuses CountPrazosByTenant.
	CountPrazos(ctx context.Context, arg CountPrazosParams) (int64, error)
	// The "X de Y" total for the Prazos tab: how many prazos the process holds. Same
	// tenant + court_record scoping as the list.
	CountPrazosByProcesso(ctx context.Context, arg CountPrazosByProcessoParams) (int64, error)
	// The tenant-wide "Y" of the agenda counter: every prazo the tenant holds, regardless
	// of any filter.
	CountPrazosByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	// deadline slice queries (the prazos CREATION path). Every write and read runs inside
	// the use case's transaction so RLS scopes it to the event's tenant (barrier 2) on top
	// of the explicit tenant filter (barrier 1). Absence is a typed error at the mapper,
	// never (nil, nil).
	// Read the rito signal (class) for the record the intimação hangs on — the one
	// cross-table read the derivation needs (decisão P1: read the table, never import the
	// acquisition package). A missing record → pgx.ErrNoRows → typed not-found at the
	// mapper. class itself may be NULL (mapped to "").
	// tenant_id is filtered explicitly (barrier 1) even though RLS (barrier 2) already
	// scopes the tx: a NULL app.tenant_id or an RLS regression would otherwise let a read
	// cross tenants. $2 = tenant_id, from the trusted event payload (never the body).
	GetCourtRecordClass(ctx context.Context, arg GetCourtRecordClassParams) (*string, error)
	// Re-read a prazo at a scheduled mark's fire time (deadline.reminder_check): the CURRENT
	// status the fire handler branches on, plus the end_date and the context (kind, counting,
	// court_record_id) a lembrete or MISSED fact may carry. Keyed by id and scoped to tenant_id
	// (barrier 1, on top of RLS barrier 2). A missing id in the tenant → pgx.ErrNoRows → typed
	// ErrDeadlineNotFound at the mapper, never (nil, nil). $1 = id, $2 = tenant_id, both from
	// the trusted scheduled-event payload.
	GetDeadlineForCheck(ctx context.Context, arg GetDeadlineForCheckParams) (GetDeadlineForCheckRow, error)
	// The audit/detail view of one prazo (GET /v1/prazos/:id): every field the "por quê"
	// popover needs — the full holidays_applied, the rules_version that derived the days,
	// the origin intimation_id, and start/end/days/counting/doubled. Tenant-scoped (barrier
	// 1): a foreign id resolves to no row → pgx.ErrNoRows → typed ErrDeadlineNotFound (404)
	// at the repo, never (nil, nil).
	GetPrazo(ctx context.Context, arg GetPrazoParams) (GetPrazoRow, error)
	// Persist the derived prazo, BORN PENDING (status), source RULE. Idempotent on the 1:1
	// notification_id (UNIQUE): ON CONFLICT DO NOTHING yields NO row on a re-derivation, so
	// the mapper reads pgx.ErrNoRows as "already exists" (ErrDeadlineExists) instead of
	// poisoning the tx with a constraint error. confirmed_by/at stay NULL (no human aval
	// yet — that is the F2 slice). Returns the DB-assigned id; the repo maps the rest from
	// the input entity.
	InsertDeadline(ctx context.Context, arg InsertDeadlineParams) (uuid.UUID, error)
	// The global agenda (GET /v1/prazos): the tenant's prazos, soonest vencimento first,
	// with the process context (cnj_number/court) joined in. Optional filters: @status ('' =
	// all) and an end_date window [@from_date, @to_date] (NULL = open bound). Ascending
	// keyset on (end_date, id); the first page passes the min sentinel ('0001-01-01',
	// zero-uuid).
	ListPrazos(ctx context.Context, arg ListPrazosParams) ([]ListPrazosRow, error)
	// read-model queries (deadline slice) — the prazos SCREEN reads, kept OFF the write
	// path (docs: "leitura de tela usa read model, DTO por query dedicada"). Each is
	// tenant-scoped (barrier 1: an explicit tenant_id filter from the trusted principal,
	// never the body) and, where paginated, keyset-paginated on a stable (end_date, id)
	// pair — ascending, since a prazo agenda reads soonest-first. The caller passes a
	// sentinel cursor for the first page, so there is no conditional WHERE. days_left is
	// computed here as calendar days to end_date ((end_date - CURRENT_DATE)::int); the
	// urgency styling (gold < 3 dias) is the FE's call, not the read model's.
	// The Prazos tab of one process (GET /v1/processos/:id/prazos): the deadlines anchored
	// on the court_record, soonest vencimento first. @court_record_id is the court_record
	// id (the same id /processos returns). notification_id is the FK to intimation (the
	// historic column name, migration 0006) — the read model exposes it as intimation_id.
	// confirmed collapses confirmed_by IS NOT NULL to a bool (was the prazo human-approved).
	ListPrazosByProcesso(ctx context.Context, arg ListPrazosByProcessoParams) ([]ListPrazosByProcessoRow, error)
	// Auto-mark a prazo MISSED at the D+1 carência (deadline.missed_check fire path). Scoped to
	// tenant_id (barrier 1). The `status = 'OPEN' AND end_date < CURRENT_DATE` guard makes the
	// flip SAFE and IDEMPOTENT (decisão travada: MISSED auto D+1 SÓ em OPEN — nunca perder um
	// PENDING não confirmado): a redelivery, a PENDING/terminal prazo, or one not yet overdue
	// updates NO row → pgx.ErrNoRows → typed not-found at the mapper, the use case's no-op
	// (never a phantom deadline.missed). On a hit it returns the id so deadline.missed commits
	// in the SAME tx. $1 = id, $2 = tenant_id, both from the trusted scheduled-event payload.
	MarkMissed(ctx context.Context, arg MarkMissedParams) (uuid.UUID, error)
	// Resolve the conservative rule for (intimation_type, court) in a rules version. The
	// resolution lives HERE, in SQL (decisão travada, erd-prazos.md §8/§11): the most
	// SPECIFIC active match wins, falling back to the '*' catch-all — so an unknown type
	// still yields the safe GENERICO rule. Ordering, most specific first:
	//   1. an exact intimation_type beats the '*' catch-all;
	//   2. a court-specific rule (court_prefix set) beats an any-court rule;
	//   3. a longer court_prefix is more specific than a shorter one;
	//   4. finally, higher priority wins.
	// $1 = rules_version, $2 = intimation_type, $3 = court. A court_prefix matches when the
	// court sigla starts with it ($3 LIKE prefix || '%'); a NULL prefix matches any court.
	ResolveDeadlineRule(ctx context.Context, arg ResolveDeadlineRuleParams) (ResolveDeadlineRuleRow, error)
	// Revoke (CANCEL) the prazo derived from an intimação the DJEN retracted (erd-prazos.md
	// §7/§11: uma intimação retificada vira prazo-fantasma → deadline.revoked). Keyed by the
	// 1:1 notification_id (=intimation id) and scoped to tenant_id (barrier 1, on top of RLS
	// barrier 2). The `status <> 'CANCELLED'` guard makes the revoke IDEMPOTENT: a redelivery
	// past the dedup — or a cancel that lands before any prazo exists, or on an already
	// CANCELLED one — updates NO row → pgx.ErrNoRows → typed not-found at the mapper, the use
	// case's safe no-op (never a phantom revoked). On a hit it returns the revoked id (+ the
	// record it hung on) so deadline.revoked commits in the SAME tx. $1 = intimation_id (the
	// notification_id column), $2 = tenant_id, both from the trusted event payload.
	RevokeDeadlineByIntimation(ctx context.Context, arg RevokeDeadlineByIntimationParams) (RevokeDeadlineByIntimationRow, error)
}

var _ Querier = (*Queries)(nil)
