// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read.sql

package deadlinedb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPrazos = `-- name: CountPrazos :one
SELECT count(*) FROM deadline d
WHERE d.tenant_id = $1::uuid
  AND ($2::text = '' OR d.status = $2::text)
  AND ($3::date IS NULL OR d.end_date >= $3::date)
  AND ($4::date IS NULL OR d.end_date <= $4::date)
`

type CountPrazosParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Status   string      `json:"status"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

// The filtered "X" of the agenda's "X de Y" counter: how many prazos match the active
// @status / end_date window. Called only when a filter is present; the unfiltered "Y"
// reuses CountPrazosByTenant.
func (q *Queries) CountPrazos(ctx context.Context, arg CountPrazosParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPrazos,
		arg.TenantID,
		arg.Status,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPrazosByProcesso = `-- name: CountPrazosByProcesso :one
SELECT count(*) FROM deadline d
WHERE d.court_record_id = $1::uuid
  AND d.tenant_id = $2::uuid
`

type CountPrazosByProcessoParams struct {
	CourtRecordID uuid.UUID `json:"court_record_id"`
	TenantID      uuid.UUID `json:"tenant_id"`
}

// The "X de Y" total for the Prazos tab: how many prazos the process holds. Same
// tenant + court_record scoping as the list.
func (q *Queries) CountPrazosByProcesso(ctx context.Context, arg CountPrazosByProcessoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPrazosByProcesso, arg.CourtRecordID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPrazosByTenant = `-- name: CountPrazosByTenant :one
SELECT count(*) FROM deadline WHERE tenant_id = $1::uuid
`

// The tenant-wide "Y" of the agenda counter: every prazo the tenant holds, regardless
// of any filter.
func (q *Queries) CountPrazosByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPrazosByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPrazo = `-- name: GetPrazo :one
SELECT d.id, d.court_record_id, d.kind, d.start_date, d.end_date,
       (d.end_date - CURRENT_DATE)::int AS days_left,
       d.days, d.counting, d.doubled, d.doubled_reason, d.status, d.source,
       d.holidays_applied, d.notification_id, d.rules_version,
       (d.confirmed_by IS NOT NULL) AS confirmed
FROM deadline d
WHERE d.id = $1::uuid AND d.tenant_id = $2::uuid
`

type GetPrazoParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetPrazoRow struct {
	ID              uuid.UUID   `json:"id"`
	CourtRecordID   uuid.UUID   `json:"court_record_id"`
	Kind            *string     `json:"kind"`
	StartDate       pgtype.Date `json:"start_date"`
	EndDate         pgtype.Date `json:"end_date"`
	DaysLeft        int32       `json:"days_left"`
	Days            int32       `json:"days"`
	Counting        string      `json:"counting"`
	Doubled         bool        `json:"doubled"`
	DoubledReason   *string     `json:"doubled_reason"`
	Status          string      `json:"status"`
	Source          string      `json:"source"`
	HolidaysApplied []byte      `json:"holidays_applied"`
	NotificationID  uuid.UUID   `json:"notification_id"`
	RulesVersion    string      `json:"rules_version"`
	Confirmed       interface{} `json:"confirmed"`
}

// The audit/detail view of one prazo (GET /v1/prazos/:id): every field the "por quê"
// popover needs — the full holidays_applied, the rules_version that derived the days,
// the origin intimation_id, and start/end/days/counting/doubled. Tenant-scoped (barrier
// 1): a foreign id resolves to no row → pgx.ErrNoRows → typed ErrDeadlineNotFound (404)
// at the repo, never (nil, nil).
func (q *Queries) GetPrazo(ctx context.Context, arg GetPrazoParams) (GetPrazoRow, error) {
	row := q.db.QueryRow(ctx, getPrazo, arg.ID, arg.TenantID)
	var i GetPrazoRow
	err := row.Scan(
		&i.ID,
		&i.CourtRecordID,
		&i.Kind,
		&i.StartDate,
		&i.EndDate,
		&i.DaysLeft,
		&i.Days,
		&i.Counting,
		&i.Doubled,
		&i.DoubledReason,
		&i.Status,
		&i.Source,
		&i.HolidaysApplied,
		&i.NotificationID,
		&i.RulesVersion,
		&i.Confirmed,
	)
	return i, err
}

const listPrazos = `-- name: ListPrazos :many
SELECT d.id, d.kind, d.end_date,
       (d.end_date - CURRENT_DATE)::int AS days_left,
       d.counting, d.doubled, d.doubled_reason, d.status,
       d.holidays_applied, d.notification_id,
       (d.confirmed_by IS NOT NULL) AS confirmed,
       d.court_record_id, cr.cnj_number, cr.court
FROM deadline d
JOIN court_record cr ON cr.id = d.court_record_id
WHERE d.tenant_id = $1::uuid
  AND ($2::text = '' OR d.status = $2::text)
  AND ($3::date IS NULL OR d.end_date >= $3::date)
  AND ($4::date IS NULL OR d.end_date <= $4::date)
  AND (d.end_date, d.id) > ($5::date, $6::uuid)
ORDER BY d.end_date ASC, d.id ASC
LIMIT $7
`

type ListPrazosParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	Status    string      `json:"status"`
	FromDate  pgtype.Date `json:"from_date"`
	ToDate    pgtype.Date `json:"to_date"`
	LastEnd   pgtype.Date `json:"last_end"`
	LastID    uuid.UUID   `json:"last_id"`
	PageLimit int32       `json:"page_limit"`
}

type ListPrazosRow struct {
	ID              uuid.UUID   `json:"id"`
	Kind            *string     `json:"kind"`
	EndDate         pgtype.Date `json:"end_date"`
	DaysLeft        int32       `json:"days_left"`
	Counting        string      `json:"counting"`
	Doubled         bool        `json:"doubled"`
	DoubledReason   *string     `json:"doubled_reason"`
	Status          string      `json:"status"`
	HolidaysApplied []byte      `json:"holidays_applied"`
	NotificationID  uuid.UUID   `json:"notification_id"`
	Confirmed       interface{} `json:"confirmed"`
	CourtRecordID   uuid.UUID   `json:"court_record_id"`
	CnjNumber       string      `json:"cnj_number"`
	Court           string      `json:"court"`
}

// The global agenda (GET /v1/prazos): the tenant's prazos, soonest vencimento first,
// with the process context (cnj_number/court) joined in. Optional filters: @status (” =
// all) and an end_date window [@from_date, @to_date] (NULL = open bound). Ascending
// keyset on (end_date, id); the first page passes the min sentinel ('0001-01-01',
// zero-uuid).
func (q *Queries) ListPrazos(ctx context.Context, arg ListPrazosParams) ([]ListPrazosRow, error) {
	rows, err := q.db.Query(ctx, listPrazos,
		arg.TenantID,
		arg.Status,
		arg.FromDate,
		arg.ToDate,
		arg.LastEnd,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrazosRow
	for rows.Next() {
		var i ListPrazosRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.EndDate,
			&i.DaysLeft,
			&i.Counting,
			&i.Doubled,
			&i.DoubledReason,
			&i.Status,
			&i.HolidaysApplied,
			&i.NotificationID,
			&i.Confirmed,
			&i.CourtRecordID,
			&i.CnjNumber,
			&i.Court,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrazosByProcesso = `-- name: ListPrazosByProcesso :many

SELECT d.id, d.kind, d.end_date,
       (d.end_date - CURRENT_DATE)::int AS days_left,
       d.counting, d.doubled, d.doubled_reason, d.status,
       d.holidays_applied, d.notification_id,
       (d.confirmed_by IS NOT NULL) AS confirmed
FROM deadline d
WHERE d.court_record_id = $1::uuid
  AND d.tenant_id = $2::uuid
  AND (d.end_date, d.id) > ($3::date, $4::uuid)
ORDER BY d.end_date ASC, d.id ASC
LIMIT $5
`

type ListPrazosByProcessoParams struct {
	CourtRecordID uuid.UUID   `json:"court_record_id"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	LastEnd       pgtype.Date `json:"last_end"`
	LastID        uuid.UUID   `json:"last_id"`
	PageLimit     int32       `json:"page_limit"`
}

type ListPrazosByProcessoRow struct {
	ID              uuid.UUID   `json:"id"`
	Kind            *string     `json:"kind"`
	EndDate         pgtype.Date `json:"end_date"`
	DaysLeft        int32       `json:"days_left"`
	Counting        string      `json:"counting"`
	Doubled         bool        `json:"doubled"`
	DoubledReason   *string     `json:"doubled_reason"`
	Status          string      `json:"status"`
	HolidaysApplied []byte      `json:"holidays_applied"`
	NotificationID  uuid.UUID   `json:"notification_id"`
	Confirmed       interface{} `json:"confirmed"`
}

// read-model queries (deadline slice) — the prazos SCREEN reads, kept OFF the write
// path (docs: "leitura de tela usa read model, DTO por query dedicada"). Each is
// tenant-scoped (barrier 1: an explicit tenant_id filter from the trusted principal,
// never the body) and, where paginated, keyset-paginated on a stable (end_date, id)
// pair — ascending, since a prazo agenda reads soonest-first. The caller passes a
// sentinel cursor for the first page, so there is no conditional WHERE. days_left is
// computed here as calendar days to end_date ((end_date - CURRENT_DATE)::int); the
// urgency styling (gold < 3 dias) is the FE's call, not the read model's.
// The Prazos tab of one process (GET /v1/processos/:id/prazos): the deadlines anchored
// on the court_record, soonest vencimento first. @court_record_id is the court_record
// id (the same id /processos returns). notification_id is the FK to intimation (the
// historic column name, migration 0006) — the read model exposes it as intimation_id.
// confirmed collapses confirmed_by IS NOT NULL to a bool (was the prazo human-approved).
func (q *Queries) ListPrazosByProcesso(ctx context.Context, arg ListPrazosByProcessoParams) ([]ListPrazosByProcessoRow, error) {
	rows, err := q.db.Query(ctx, listPrazosByProcesso,
		arg.CourtRecordID,
		arg.TenantID,
		arg.LastEnd,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrazosByProcessoRow
	for rows.Next() {
		var i ListPrazosByProcessoRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.EndDate,
			&i.DaysLeft,
			&i.Counting,
			&i.Doubled,
			&i.DoubledReason,
			&i.Status,
			&i.HolidaysApplied,
			&i.NotificationID,
			&i.Confirmed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
