// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read.sql

package deadlinedb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPrazos = `-- name: CountPrazos :one
SELECT count(*) FROM deadline d
JOIN court_record cr ON cr.id = d.court_record_id
WHERE d.tenant_id = $1::uuid
  AND ($2::text = '' OR d.status = $2::text)
  AND ($3::text = '' OR d.kind = $3::text)
  AND ($4::text = '' OR cr.court = $4::text)
  AND ($5::date IS NULL OR d.end_date >= $5::date)
  AND ($6::date IS NULL OR d.end_date <= $6::date)
`

type CountPrazosParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Status   string      `json:"status"`
	Kind     string      `json:"kind"`
	Court    string      `json:"court"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

// The filtered "X" of the agenda's "X de Y" counter: how many prazos match the active
// @status / @kind / @court / end_date window. Called only when a filter is present; the
// unfiltered "Y" reuses CountPrazosByTenant. The court filter needs the same court_record
// join as the list, so it never multiplies rows (the join key is the record id).
func (q *Queries) CountPrazos(ctx context.Context, arg CountPrazosParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPrazos,
		arg.TenantID,
		arg.Status,
		arg.Kind,
		arg.Court,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPrazosByProcesso = `-- name: CountPrazosByProcesso :one
SELECT count(*) FROM deadline d
WHERE d.court_record_id = $1::uuid
  AND d.tenant_id = $2::uuid
`

type CountPrazosByProcessoParams struct {
	CourtRecordID uuid.UUID `json:"court_record_id"`
	TenantID      uuid.UUID `json:"tenant_id"`
}

// The "X de Y" total for the Prazos tab: how many prazos the process holds. Same
// tenant + court_record scoping as the list.
func (q *Queries) CountPrazosByProcesso(ctx context.Context, arg CountPrazosByProcessoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPrazosByProcesso, arg.CourtRecordID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPrazosByTenant = `-- name: CountPrazosByTenant :one
SELECT count(*) FROM deadline WHERE tenant_id = $1::uuid
`

// The tenant-wide "Y" of the agenda counter: every prazo the tenant holds, regardless
// of any filter.
func (q *Queries) CountPrazosByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPrazosByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasks = `-- name: CountTasks :one
SELECT count(*) FROM task t
WHERE t.tenant_id = $1::uuid
  AND t.status <> 'DISMISSED'
  AND ($2::text = '' OR t.status = $2::text)
  AND ($3::uuid IS NULL OR t.assignee_user_id = $3::uuid)
  AND ($4::text = '' OR t.source = $4::text)
  AND ($5::uuid IS NULL OR t.intimation_id = $5::uuid)
  AND ($6::date IS NULL OR t.due_date >= $6::date)
  AND ($7::date IS NULL OR t.due_date <= $7::date)
`

type CountTasksParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	Status       string      `json:"status"`
	AssigneeID   pgtype.UUID `json:"assignee_id"`
	Source       string      `json:"source"`
	IntimationID pgtype.UUID `json:"intimation_id"`
	FromDate     pgtype.Date `json:"from_date"`
	ToDate       pgtype.Date `json:"to_date"`
}

// The filtered "X" of the task agenda's "X de Y" counter: how many tasks match the active
// @status / @assignee_id / @source / @intimation_id / window. Called only when a filter
// is present; the unfiltered "Y" reuses CountTasksByTenant. DISMISSED is always excluded,
// mirroring ListTasks (the agenda never shows dismissed tasks) — so this stays consistent
// with the list's row count even when @status='DISMISSED' is passed explicitly: both then
// resolve to zero instead of a non-empty total_count against an empty data page.
func (q *Queries) CountTasks(ctx context.Context, arg CountTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks,
		arg.TenantID,
		arg.Status,
		arg.AssigneeID,
		arg.Source,
		arg.IntimationID,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksByProcesso = `-- name: CountTasksByProcesso :one
SELECT count(*) FROM task t
WHERE t.court_record_id = $1::uuid
  AND t.tenant_id = $2::uuid
`

type CountTasksByProcessoParams struct {
	CourtRecordID uuid.UUID `json:"court_record_id"`
	TenantID      uuid.UUID `json:"tenant_id"`
}

// The "X de Y" total for the Tasks tab: how many tasks the process holds. Same tenant +
// court_record scoping as the list.
func (q *Queries) CountTasksByProcesso(ctx context.Context, arg CountTasksByProcessoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksByProcesso, arg.CourtRecordID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksByTenant = `-- name: CountTasksByTenant :one
SELECT count(*) FROM task WHERE tenant_id = $1::uuid AND status <> 'DISMISSED'
`

// The tenant-wide "Y" of the task agenda counter: every task the tenant holds, regardless of
// any filter. DISMISSED is always excluded (mirrors ListTasks — the agenda never shows
// dismissed tasks, filtered or not), so this stays consistent with the list even on an
// unfiltered GET /v1/tasks.
func (q *Queries) CountTasksByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPrazo = `-- name: GetPrazo :one
SELECT d.id, d.court_record_id, d.kind, d.start_date, d.end_date,
       (d.end_date - CURRENT_DATE)::int AS days_left,
       d.days, d.counting, d.doubled, d.doubled_reason, d.status, d.source,
       d.holidays_applied, d.notification_id, d.rules_version,
       (d.confirmed_by IS NOT NULL) AS confirmed,
       d.anchor_event, d.legal_citation, d.manual_extra_days,
       d.confirmed_by, d.confirmed_at,
       au.name AS confirmed_by_name,
       d.origem, d.selo, d.confirmacao_exigida,
       COALESCE(d.prazo_interno, d.end_date) AS prazo_interno,
       cm.id AS calc_memory_id, cm.prazo_base, cm.prazo_base_fonte, cm.termo_inicial_regra,
       cm.dias_uteis, cm.dobra_motivo, cm.tabela_legal_ref, cm.ia_tipo_inferido, cm.ia_confianca,
       cm.calendar_provider_version,
       cv.data_declarada, cv.data_calculada, cv.dif_dias, cv.resultado, cv.causa_provavel,
       cv.decisao, cv.decidido_por
FROM deadline d
LEFT JOIN app_user au ON au.id = d.confirmed_by
LEFT JOIN calc_memory cm ON cm.deadline_id = d.id
LEFT JOIN cross_validation cv ON cv.deadline_id = d.id
WHERE d.id = $1::uuid AND d.tenant_id = $2::uuid
`

type GetPrazoParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetPrazoRow struct {
	ID                      uuid.UUID          `json:"id"`
	CourtRecordID           uuid.UUID          `json:"court_record_id"`
	Kind                    *string            `json:"kind"`
	StartDate               pgtype.Date        `json:"start_date"`
	EndDate                 pgtype.Date        `json:"end_date"`
	DaysLeft                int32              `json:"days_left"`
	Days                    int32              `json:"days"`
	Counting                string             `json:"counting"`
	Doubled                 bool               `json:"doubled"`
	DoubledReason           *string            `json:"doubled_reason"`
	Status                  string             `json:"status"`
	Source                  string             `json:"source"`
	HolidaysApplied         []byte             `json:"holidays_applied"`
	NotificationID          uuid.UUID          `json:"notification_id"`
	RulesVersion            string             `json:"rules_version"`
	Confirmed               interface{}        `json:"confirmed"`
	AnchorEvent             string             `json:"anchor_event"`
	LegalCitation           *string            `json:"legal_citation"`
	ManualExtraDays         int32              `json:"manual_extra_days"`
	ConfirmedBy             pgtype.UUID        `json:"confirmed_by"`
	ConfirmedAt             pgtype.Timestamptz `json:"confirmed_at"`
	ConfirmedByName         *string            `json:"confirmed_by_name"`
	Origem                  *string            `json:"origem"`
	Selo                    *string            `json:"selo"`
	ConfirmacaoExigida      *bool              `json:"confirmacao_exigida"`
	PrazoInterno            pgtype.Date        `json:"prazo_interno"`
	CalcMemoryID            pgtype.UUID        `json:"calc_memory_id"`
	PrazoBase               *string            `json:"prazo_base"`
	PrazoBaseFonte          *string            `json:"prazo_base_fonte"`
	TermoInicialRegra       *string            `json:"termo_inicial_regra"`
	DiasUteis               *bool              `json:"dias_uteis"`
	DobraMotivo             *string            `json:"dobra_motivo"`
	TabelaLegalRef          *string            `json:"tabela_legal_ref"`
	IaTipoInferido          *string            `json:"ia_tipo_inferido"`
	IaConfianca             *float64           `json:"ia_confianca"`
	CalendarProviderVersion *string            `json:"calendar_provider_version"`
	DataDeclarada           pgtype.Date        `json:"data_declarada"`
	DataCalculada           pgtype.Date        `json:"data_calculada"`
	DifDias                 *int32             `json:"dif_dias"`
	Resultado               *string            `json:"resultado"`
	CausaProvavel           *string            `json:"causa_provavel"`
	Decisao                 *string            `json:"decisao"`
	DecididoPor             pgtype.UUID        `json:"decidido_por"`
}

// The audit/detail view of one prazo (GET /v1/prazos/:id): every field the "por quê"
// popover needs — the full holidays_applied, the rules_version that derived the days,
// the origin intimation_id, and start/end/days/counting/doubled. V1 adds the full memória de
// cálculo: origem/selo/confirmacao_exigida off the deadline row, prazo_interno (the internal
// safety buffer, COALESCEd to end_date for a pré-migration row that never had it recomputed),
// and the 1:1 calc_memory +
// cross_validation LEFT JOINed in (a pre-V1 or not-yet-derived prazo has neither row, so every
// cm./cv. column comes back NULL — the mapper degrades to nil, never an error). applied_holiday
// is 1:N so it is NOT joined here (would multiply the deadline row); ListAppliedHolidaysByCalc
// Memory reads it separately, keyed by calc_memory_id, only when cm.id is present. Tenant-scoped
// (barrier 1): a foreign id resolves to no row → pgx.ErrNoRows → typed ErrDeadlineNotFound (404)
// at the repo, never (nil, nil).
func (q *Queries) GetPrazo(ctx context.Context, arg GetPrazoParams) (GetPrazoRow, error) {
	row := q.db.QueryRow(ctx, getPrazo, arg.ID, arg.TenantID)
	var i GetPrazoRow
	err := row.Scan(
		&i.ID,
		&i.CourtRecordID,
		&i.Kind,
		&i.StartDate,
		&i.EndDate,
		&i.DaysLeft,
		&i.Days,
		&i.Counting,
		&i.Doubled,
		&i.DoubledReason,
		&i.Status,
		&i.Source,
		&i.HolidaysApplied,
		&i.NotificationID,
		&i.RulesVersion,
		&i.Confirmed,
		&i.AnchorEvent,
		&i.LegalCitation,
		&i.ManualExtraDays,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.ConfirmedByName,
		&i.Origem,
		&i.Selo,
		&i.ConfirmacaoExigida,
		&i.PrazoInterno,
		&i.CalcMemoryID,
		&i.PrazoBase,
		&i.PrazoBaseFonte,
		&i.TermoInicialRegra,
		&i.DiasUteis,
		&i.DobraMotivo,
		&i.TabelaLegalRef,
		&i.IaTipoInferido,
		&i.IaConfianca,
		&i.CalendarProviderVersion,
		&i.DataDeclarada,
		&i.DataCalculada,
		&i.DifDias,
		&i.Resultado,
		&i.CausaProvavel,
		&i.Decisao,
		&i.DecididoPor,
	)
	return i, err
}

const getPrazoSuggestContext = `-- name: GetPrazoSuggestContext :one
SELECT d.kind, d.days, d.counting, d.notification_id,
       cr.court, cr.degree, cr.class, cr.subject,
       i.type AS intimation_type,
       LEFT(i.content, 4000) AS intimation_text,
       d.ai_summary, d.ai_recommendation, d.ai_summary_generated_at
FROM deadline d
JOIN court_record cr ON cr.id = d.court_record_id
JOIN intimation i ON i.id = d.notification_id
WHERE d.id = $1::uuid AND d.tenant_id = $2::uuid
`

type GetPrazoSuggestContextParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetPrazoSuggestContextRow struct {
	Kind                 *string            `json:"kind"`
	Days                 int32              `json:"days"`
	Counting             string             `json:"counting"`
	NotificationID       uuid.UUID          `json:"notification_id"`
	Court                string             `json:"court"`
	Degree               string             `json:"degree"`
	Class                *string            `json:"class"`
	Subject              *string            `json:"subject"`
	IntimationType       *string            `json:"intimation_type"`
	IntimationText       string             `json:"intimation_text"`
	AiSummary            *string            `json:"ai_summary"`
	AiRecommendation     *string            `json:"ai_recommendation"`
	AiSummaryGeneratedAt pgtype.Timestamptz `json:"ai_summary_generated_at"`
}

// The advisory CASE CONTEXT for one prazo — the input the AI "intimação → tarefas sugeridas"
// read (suggest.go) feeds the versioned meta-prompt with. This is NOT a screen DTO (it never
// serializes to the FE): it is an internal read that gathers, in one tenant-scoped hop, the
// prazo's own signals (kind/days/counting) PLUS the richer context the composer specializes on —
// the process's court/degree/class/subject (court_record) and the origin intimação's type + teor
// (intimation). deadline.notification_id is NOT NULL (every prazo is born from an intimação), so
// both JOINs are inner. The teor is truncated to a bound so a long (often HTML) intimação never
// blows the prompt or the transfer — LEFT counts characters, so the cut is rune-safe. Also carries
// the PERSISTED ai_summary/ai_recommendation/ai_summary_generated_at (migration 0036, sync-on-
// first-GET: NULL until the first successful LLM call, frozen thereafter) so the suggester can
// serve the cached summary/recommendation instead of asking the model again. Tenant-scoped
// (barrier 1): a foreign or unknown id yields no row → typed ErrDeadlineNotFound (404) at the
// repo, never (nil, nil).
func (q *Queries) GetPrazoSuggestContext(ctx context.Context, arg GetPrazoSuggestContextParams) (GetPrazoSuggestContextRow, error) {
	row := q.db.QueryRow(ctx, getPrazoSuggestContext, arg.ID, arg.TenantID)
	var i GetPrazoSuggestContextRow
	err := row.Scan(
		&i.Kind,
		&i.Days,
		&i.Counting,
		&i.NotificationID,
		&i.Court,
		&i.Degree,
		&i.Class,
		&i.Subject,
		&i.IntimationType,
		&i.IntimationText,
		&i.AiSummary,
		&i.AiRecommendation,
		&i.AiSummaryGeneratedAt,
	)
	return i, err
}

const getPrazosSummary = `-- name: GetPrazosSummary :one

SELECT
  count(*)::bigint AS total,
  count(*) FILTER (
    WHERE d.status IN ('OPEN', 'PENDING') AND (d.end_date - CURRENT_DATE) <= 1
  )::bigint AS criticos,
  count(*) FILTER (
    WHERE d.status IN ('OPEN', 'PENDING') AND (d.end_date - CURRENT_DATE) BETWEEN 0 AND 3
  )::bigint AS vencendo,
  count(*) FILTER (WHERE d.status IN ('OPEN', 'PENDING'))::bigint AS abertos,
  count(*) FILTER (
    WHERE d.status IN ('OPEN', 'PENDING') AND d.start_date > CURRENT_DATE
  )::bigint AS futuros,
  count(*) FILTER (
    WHERE d.status = 'MISSED'
       OR (d.status IN ('OPEN', 'PENDING') AND (d.end_date - CURRENT_DATE) < 0)
  )::bigint AS vencidos,
  count(*) FILTER (WHERE d.status = 'MET')::bigint AS cumpridos
FROM deadline d
WHERE d.tenant_id = $1::uuid
`

type GetPrazosSummaryRow struct {
	Total     int64 `json:"total"`
	Criticos  int64 `json:"criticos"`
	Vencendo  int64 `json:"vencendo"`
	Abertos   int64 `json:"abertos"`
	Futuros   int64 `json:"futuros"`
	Vencidos  int64 `json:"vencidos"`
	Cumpridos int64 `json:"cumpridos"`
}

// ── KPI summaries (GET /v1/prazos/summary, GET /v1/tasks/summary) ────────────
// Single-object read models for the Tarefas/Prazos cockpit KPIs, aggregated per tenant. Both
// follow the intimacoes/summary precedent (0030): one query, count(*) FILTER per bucket, no
// pagination. The buckets' semantics are documented at the read.go DTOs.
// The prazos KPI counts, derived from deadline.status + days_left ((end_date - CURRENT_DATE)),
// scoped to tenant_id (barrier 1). The buckets (thresholds documented at PrazosSummary in
// read.go): criticos = OPEN/PENDING with days_left <= 1; vencendo = OPEN/PENDING with days_left
// in 0..3; abertos = every OPEN/PENDING; futuros = OPEN/PENDING starting in the future
// (start_date > today); vencidos = MISSED or an OPEN/PENDING already past (days_left < 0);
// cumpridos = MET. CANCELLED is counted only in total. $1 = tenant_id.
func (q *Queries) GetPrazosSummary(ctx context.Context, tenantID uuid.UUID) (GetPrazosSummaryRow, error) {
	row := q.db.QueryRow(ctx, getPrazosSummary, tenantID)
	var i GetPrazosSummaryRow
	err := row.Scan(
		&i.Total,
		&i.Criticos,
		&i.Vencendo,
		&i.Abertos,
		&i.Futuros,
		&i.Vencidos,
		&i.Cumpridos,
	)
	return i, err
}

const getTaskDetail = `-- name: GetTaskDetail :one

SELECT t.id, t.title, t.description, t.kind, t.priority, t.due_date,
       t.status, t.source, t.assignee_user_id, t.deadline_id, t.intimation_id,
       t.court_record_id, t.completed_at
FROM task t
WHERE t.id = $1::uuid AND t.tenant_id = $2::uuid
`

type GetTaskDetailParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetTaskDetailRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	Kind           *string            `json:"kind"`
	Priority       *string            `json:"priority"`
	DueDate        pgtype.Date        `json:"due_date"`
	Status         string             `json:"status"`
	Source         string             `json:"source"`
	AssigneeUserID pgtype.UUID        `json:"assignee_user_id"`
	DeadlineID     pgtype.UUID        `json:"deadline_id"`
	IntimationID   pgtype.UUID        `json:"intimation_id"`
	CourtRecordID  pgtype.UUID        `json:"court_record_id"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

// ── task detail + checklist (GET /v1/tasks/:id) ─────────────────────────────
// The task detail screen (docs/erd-prazos.md, a Tarefa aberta): the task's own fields + its
// ordered checklist + the {done, total} progress the derived display_status reads. All
// tenant-scoped (barrier 1). display_status is DERIVED in Go (read.go), not here — the SQL
// returns the raw ingredients (status, due_date, and the progress counts).
// The task's own fields for the detail view, keyed by id and scoped to tenant_id (barrier 1).
// A miss (foreign/unknown id) → pgx.ErrNoRows → typed ErrTaskNotFound (→ 404) at the mapper,
// never (nil, nil). The checklist + progress are separate queries (a task with no items still
// resolves). $1 = id, $2 = tenant_id.
func (q *Queries) GetTaskDetail(ctx context.Context, arg GetTaskDetailParams) (GetTaskDetailRow, error) {
	row := q.db.QueryRow(ctx, getTaskDetail, arg.ID, arg.TenantID)
	var i GetTaskDetailRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Kind,
		&i.Priority,
		&i.DueDate,
		&i.Status,
		&i.Source,
		&i.AssigneeUserID,
		&i.DeadlineID,
		&i.IntimationID,
		&i.CourtRecordID,
		&i.CompletedAt,
	)
	return i, err
}

const getTaskItemProgress = `-- name: GetTaskItemProgress :one
SELECT count(*) FILTER (WHERE done)::bigint AS done,
       count(*)::bigint                     AS total
FROM task_item
WHERE task_id = $1::uuid AND tenant_id = $2::uuid
`

type GetTaskItemProgressParams struct {
	TaskID   uuid.UUID `json:"task_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetTaskItemProgressRow struct {
	Done  int64 `json:"done"`
	Total int64 `json:"total"`
}

// The {done, total} progress of one task's checklist (the detail view's progress bar + the
// Em execução signal for display_status). Scoped to (task_id, tenant_id) (barrier 1). An empty
// checklist yields {0, 0}. $1 = task_id, $2 = tenant_id.
func (q *Queries) GetTaskItemProgress(ctx context.Context, arg GetTaskItemProgressParams) (GetTaskItemProgressRow, error) {
	row := q.db.QueryRow(ctx, getTaskItemProgress, arg.TaskID, arg.TenantID)
	var i GetTaskItemProgressRow
	err := row.Scan(&i.Done, &i.Total)
	return i, err
}

const getTasksSummary = `-- name: GetTasksSummary :one
SELECT
  count(*) FILTER (WHERE t.status = 'DONE')::bigint AS concluidas,
  count(*) FILTER (
    WHERE t.status = 'OPEN' AND t.due_date IS NOT NULL AND t.due_date < CURRENT_DATE
  )::bigint AS atrasadas,
  count(*) FILTER (
    WHERE t.status = 'OPEN'
      AND NOT (t.due_date IS NOT NULL AND t.due_date < CURRENT_DATE)
      AND p.done_items > 0
  )::bigint AS em_execucao,
  count(*) FILTER (
    WHERE t.status = 'OPEN'
      AND NOT (t.due_date IS NOT NULL AND t.due_date < CURRENT_DATE)
      AND p.done_items = 0
  )::bigint AS abertas
FROM task t
LEFT JOIN LATERAL (
  SELECT count(*) FILTER (WHERE ti.done) AS done_items
  FROM task_item ti
  WHERE ti.task_id = t.id AND ti.tenant_id = t.tenant_id
) p ON true
WHERE t.tenant_id = $1::uuid
`

type GetTasksSummaryRow struct {
	Concluidas int64 `json:"concluidas"`
	Atrasadas  int64 `json:"atrasadas"`
	EmExecucao int64 `json:"em_execucao"`
	Abertas    int64 `json:"abertas"`
}

// The tasks KPI counts, derived from the SAME display_status logic the detail/list views use,
// scoped to tenant_id (barrier 1). em_execucao needs the checklist progress, so a LEFT JOIN
// LATERAL folds each task's done-item count in. Buckets (DISMISSED excluded, mirrors the derived
// display_status): concluidas = DONE; atrasadas = OPEN with due_date < today; em_execucao = OPEN,
// not yet due, with at least one done item; abertas = OPEN, not yet due, no done item. $1 = tenant_id.
func (q *Queries) GetTasksSummary(ctx context.Context, tenantID uuid.UUID) (GetTasksSummaryRow, error) {
	row := q.db.QueryRow(ctx, getTasksSummary, tenantID)
	var i GetTasksSummaryRow
	err := row.Scan(
		&i.Concluidas,
		&i.Atrasadas,
		&i.EmExecucao,
		&i.Abertas,
	)
	return i, err
}

const listAppliedHolidaysByCalcMemory = `-- name: ListAppliedHolidaysByCalcMemory :many
SELECT id, data, nome, ambito, comarca
FROM applied_holiday
WHERE calc_memory_id = $1 AND tenant_id = $2
ORDER BY data ASC
`

type ListAppliedHolidaysByCalcMemoryParams struct {
	CalcMemoryID uuid.UUID `json:"calc_memory_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
}

type ListAppliedHolidaysByCalcMemoryRow struct {
	ID      uuid.UUID   `json:"id"`
	Data    pgtype.Date `json:"data"`
	Nome    *string     `json:"nome"`
	Ambito  *string     `json:"ambito"`
	Comarca *string     `json:"comarca"`
}

// The 1:N feriados snapshot applied to one calc_memory (GET /v1/prazos/:id memória de
// cálculo). Kept as a companion query to GetPrazo (not joined there) so a prazo with N applied
// holidays never multiplies the deadline row. Scoped to tenant_id (barrier 1, on top of RLS
// barrier 2). No holidays applied (a dias corridos calc, or a short prazo that skipped none)
// yields an empty slice, never an error. $1 = calc_memory_id, $2 = tenant_id.
func (q *Queries) ListAppliedHolidaysByCalcMemory(ctx context.Context, arg ListAppliedHolidaysByCalcMemoryParams) ([]ListAppliedHolidaysByCalcMemoryRow, error) {
	rows, err := q.db.Query(ctx, listAppliedHolidaysByCalcMemory, arg.CalcMemoryID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppliedHolidaysByCalcMemoryRow
	for rows.Next() {
		var i ListAppliedHolidaysByCalcMemoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Data,
			&i.Nome,
			&i.Ambito,
			&i.Comarca,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrazoCourts = `-- name: ListPrazoCourts :many
SELECT court
FROM (
  SELECT DISTINCT cr.court
  FROM deadline d
  JOIN court_record cr ON cr.id = d.court_record_id
  WHERE d.tenant_id = $1::uuid
    AND cr.court <> ''
) courts
ORDER BY LOWER(court) ASC
`

// Selectable ?court values for the prazos agenda: the distinct courts of the tenant's
// intimated court records (the same join the list uses), ordered by name
// (case-insensitive). Same DISTINCT-inner / ORDER BY-outer shape as ListPrazoKinds.
func (q *Queries) ListPrazoCourts(ctx context.Context, tenantID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPrazoCourts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var court string
		if err := rows.Scan(&court); err != nil {
			return nil, err
		}
		items = append(items, court)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrazoKinds = `-- name: ListPrazoKinds :many

SELECT kind
FROM (
  SELECT DISTINCT d.kind
  FROM deadline d
  WHERE d.tenant_id = $1::uuid
    AND d.kind <> ''
) kinds
ORDER BY LOWER(kind) ASC
`

// ── filter options (the envelope's selectable sets) ──────────────────────────
// Distinct-value reads that back the prazos/tasks agenda envelopes' filter chips.
// Each is tenant-scoped (barrier 1) and mirrors the list's own predicates, so the
// options reflect what the list can actually show. Empty values are skipped in Go.
// Selectable ?kind values for the prazos agenda: the distinct kinds of the tenant's
// prazos, ordered by name (case-insensitive). The DISTINCT lives in the inner query —
// a bare SELECT DISTINCT with ORDER BY on an expression not in the select list is
// rejected by Postgres — and the outer layer orders without re-distincting.
func (q *Queries) ListPrazoKinds(ctx context.Context, tenantID uuid.UUID) ([]*string, error) {
	rows, err := q.db.Query(ctx, listPrazoKinds, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var kind *string
		if err := rows.Scan(&kind); err != nil {
			return nil, err
		}
		items = append(items, kind)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrazos = `-- name: ListPrazos :many
SELECT d.id, d.kind, d.end_date,
       (d.end_date - CURRENT_DATE)::int AS days_left,
       d.counting, d.doubled, d.doubled_reason, d.status,
       d.holidays_applied, d.notification_id,
       (d.confirmed_by IS NOT NULL) AS confirmed,
       d.court_record_id, cr.cnj_number, cr.court
FROM deadline d
JOIN court_record cr ON cr.id = d.court_record_id
WHERE d.tenant_id = $1::uuid
  AND ($2::text = '' OR d.status = $2::text)
  AND ($3::text = '' OR d.kind = $3::text)
  AND ($4::text = '' OR cr.court = $4::text)
  AND ($5::date IS NULL OR d.end_date >= $5::date)
  AND ($6::date IS NULL OR d.end_date <= $6::date)
  AND (d.end_date, d.id) > ($7::date, $8::uuid)
ORDER BY d.end_date ASC, d.id ASC
LIMIT $9
`

type ListPrazosParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	Status    string      `json:"status"`
	Kind      string      `json:"kind"`
	Court     string      `json:"court"`
	FromDate  pgtype.Date `json:"from_date"`
	ToDate    pgtype.Date `json:"to_date"`
	LastEnd   pgtype.Date `json:"last_end"`
	LastID    uuid.UUID   `json:"last_id"`
	PageLimit int32       `json:"page_limit"`
}

type ListPrazosRow struct {
	ID              uuid.UUID   `json:"id"`
	Kind            *string     `json:"kind"`
	EndDate         pgtype.Date `json:"end_date"`
	DaysLeft        int32       `json:"days_left"`
	Counting        string      `json:"counting"`
	Doubled         bool        `json:"doubled"`
	DoubledReason   *string     `json:"doubled_reason"`
	Status          string      `json:"status"`
	HolidaysApplied []byte      `json:"holidays_applied"`
	NotificationID  uuid.UUID   `json:"notification_id"`
	Confirmed       interface{} `json:"confirmed"`
	CourtRecordID   uuid.UUID   `json:"court_record_id"`
	CnjNumber       string      `json:"cnj_number"`
	Court           string      `json:"court"`
}

// The global agenda (GET /v1/prazos): the tenant's prazos, soonest vencimento first,
// with the process context (cnj_number/court) joined in. Optional filters: @status (” =
// all), @kind (” = all), @court (” = all), and an end_date window [@from_date, @to_date]
// (NULL = open bound). Ascending keyset on (end_date, id); the first page passes the min
// sentinel ('0001-01-01', zero-uuid).
func (q *Queries) ListPrazos(ctx context.Context, arg ListPrazosParams) ([]ListPrazosRow, error) {
	rows, err := q.db.Query(ctx, listPrazos,
		arg.TenantID,
		arg.Status,
		arg.Kind,
		arg.Court,
		arg.FromDate,
		arg.ToDate,
		arg.LastEnd,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrazosRow
	for rows.Next() {
		var i ListPrazosRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.EndDate,
			&i.DaysLeft,
			&i.Counting,
			&i.Doubled,
			&i.DoubledReason,
			&i.Status,
			&i.HolidaysApplied,
			&i.NotificationID,
			&i.Confirmed,
			&i.CourtRecordID,
			&i.CnjNumber,
			&i.Court,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrazosByIntimacao = `-- name: ListPrazosByIntimacao :many
SELECT d.id, d.kind, d.end_date,
       (d.end_date - CURRENT_DATE)::int AS days_left,
       d.counting, d.doubled, d.doubled_reason, d.status,
       d.holidays_applied, d.notification_id,
       (d.confirmed_by IS NOT NULL) AS confirmed,
       d.court_record_id, cr.cnj_number, cr.court
FROM deadline d
JOIN court_record cr ON cr.id = d.court_record_id
WHERE d.tenant_id = $1::uuid
  AND d.notification_id = $2::uuid
ORDER BY d.end_date ASC, d.id ASC
`

type ListPrazosByIntimacaoParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	IntimationID uuid.UUID `json:"intimation_id"`
}

type ListPrazosByIntimacaoRow struct {
	ID              uuid.UUID   `json:"id"`
	Kind            *string     `json:"kind"`
	EndDate         pgtype.Date `json:"end_date"`
	DaysLeft        int32       `json:"days_left"`
	Counting        string      `json:"counting"`
	Doubled         bool        `json:"doubled"`
	DoubledReason   *string     `json:"doubled_reason"`
	Status          string      `json:"status"`
	HolidaysApplied []byte      `json:"holidays_applied"`
	NotificationID  uuid.UUID   `json:"notification_id"`
	Confirmed       interface{} `json:"confirmed"`
	CourtRecordID   uuid.UUID   `json:"court_record_id"`
	CnjNumber       string      `json:"cnj_number"`
	Court           string      `json:"court"`
}

// The prazo of ONE intimação (GET /v1/prazos?intimation_id=...): the F2 screen opens
// from an intimação and needs its derived prazo. The deadline is 1:1 with the intimação
// by notification_id (UNIQUE, migration 0006 column name), so this returns 0 or 1 rows.
// SAME projection as ListPrazos (the agenda row shape, with the cnj/court context from
// the join) so the handler can reuse the AgendaPrazoView envelope unchanged. Scoped to
// tenant_id (barrier 1, from the principal — never the query): a foreign tenant sees no
// prazo. No keyset/window filters here — the 1:1 lookup is already a single row.
func (q *Queries) ListPrazosByIntimacao(ctx context.Context, arg ListPrazosByIntimacaoParams) ([]ListPrazosByIntimacaoRow, error) {
	rows, err := q.db.Query(ctx, listPrazosByIntimacao, arg.TenantID, arg.IntimationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrazosByIntimacaoRow
	for rows.Next() {
		var i ListPrazosByIntimacaoRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.EndDate,
			&i.DaysLeft,
			&i.Counting,
			&i.Doubled,
			&i.DoubledReason,
			&i.Status,
			&i.HolidaysApplied,
			&i.NotificationID,
			&i.Confirmed,
			&i.CourtRecordID,
			&i.CnjNumber,
			&i.Court,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrazosByProcesso = `-- name: ListPrazosByProcesso :many

SELECT d.id, d.kind, d.end_date,
       (d.end_date - CURRENT_DATE)::int AS days_left,
       d.counting, d.doubled, d.doubled_reason, d.status,
       d.holidays_applied, d.notification_id,
       (d.confirmed_by IS NOT NULL) AS confirmed
FROM deadline d
WHERE d.court_record_id = $1::uuid
  AND d.tenant_id = $2::uuid
  AND (d.end_date, d.id) > ($3::date, $4::uuid)
ORDER BY d.end_date ASC, d.id ASC
LIMIT $5
`

type ListPrazosByProcessoParams struct {
	CourtRecordID uuid.UUID   `json:"court_record_id"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	LastEnd       pgtype.Date `json:"last_end"`
	LastID        uuid.UUID   `json:"last_id"`
	PageLimit     int32       `json:"page_limit"`
}

type ListPrazosByProcessoRow struct {
	ID              uuid.UUID   `json:"id"`
	Kind            *string     `json:"kind"`
	EndDate         pgtype.Date `json:"end_date"`
	DaysLeft        int32       `json:"days_left"`
	Counting        string      `json:"counting"`
	Doubled         bool        `json:"doubled"`
	DoubledReason   *string     `json:"doubled_reason"`
	Status          string      `json:"status"`
	HolidaysApplied []byte      `json:"holidays_applied"`
	NotificationID  uuid.UUID   `json:"notification_id"`
	Confirmed       interface{} `json:"confirmed"`
}

// read-model queries (deadline slice) — the prazos SCREEN reads, kept OFF the write
// path (docs: "leitura de tela usa read model, DTO por query dedicada"). Each is
// tenant-scoped (barrier 1: an explicit tenant_id filter from the trusted principal,
// never the body) and, where paginated, keyset-paginated on a stable (end_date, id)
// pair — ascending, since a prazo agenda reads soonest-first. The caller passes a
// sentinel cursor for the first page, so there is no conditional WHERE. days_left is
// computed here as calendar days to end_date ((end_date - CURRENT_DATE)::int); the
// urgency styling (gold < 3 dias) is the FE's call, not the read model's.
// The Prazos tab of one process (GET /v1/processos/:id/prazos): the deadlines anchored
// on the court_record, soonest vencimento first. @court_record_id is the court_record
// id (the same id /processos returns). notification_id is the FK to intimation (the
// historic column name, migration 0006) — the read model exposes it as intimation_id.
// confirmed collapses confirmed_by IS NOT NULL to a bool (was the prazo human-approved).
func (q *Queries) ListPrazosByProcesso(ctx context.Context, arg ListPrazosByProcessoParams) ([]ListPrazosByProcessoRow, error) {
	rows, err := q.db.Query(ctx, listPrazosByProcesso,
		arg.CourtRecordID,
		arg.TenantID,
		arg.LastEnd,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrazosByProcessoRow
	for rows.Next() {
		var i ListPrazosByProcessoRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.EndDate,
			&i.DaysLeft,
			&i.Counting,
			&i.Doubled,
			&i.DoubledReason,
			&i.Status,
			&i.HolidaysApplied,
			&i.NotificationID,
			&i.Confirmed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskActivity = `-- name: ListTaskActivity :many
SELECT a.id, a.actor_user_id, COALESCE(au.name, '')::text AS actor_name,
       a.event_type, a.from_value, a.to_value, a.created_at
FROM task_activity a
LEFT JOIN app_user au ON au.id = a.actor_user_id
WHERE a.task_id = $1::uuid AND a.tenant_id = $2::uuid
ORDER BY a.created_at DESC, a.id DESC
`

type ListTaskActivityParams struct {
	TaskID   uuid.UUID `json:"task_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type ListTaskActivityRow struct {
	ID          uuid.UUID          `json:"id"`
	ActorUserID uuid.UUID          `json:"actor_user_id"`
	ActorName   string             `json:"actor_name"`
	EventType   string             `json:"event_type"`
	FromValue   *string            `json:"from_value"`
	ToValue     *string            `json:"to_value"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// One task's audit log, NEWEST-first (the detail view reads most-recent-first). $1 = task_id, $2 =
// tenant_id. An empty log is 0 rows (never an error). The actor is resolved to a name for display;
// from_value/to_value are the field change's before/after (NULL for create/lifecycle/comment).
func (q *Queries) ListTaskActivity(ctx context.Context, arg ListTaskActivityParams) ([]ListTaskActivityRow, error) {
	rows, err := q.db.Query(ctx, listTaskActivity, arg.TaskID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskActivityRow
	for rows.Next() {
		var i ListTaskActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorName,
			&i.EventType,
			&i.FromValue,
			&i.ToValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAssignees = `-- name: ListTaskAssignees :many
SELECT assignee_user_id, name
FROM (
  SELECT DISTINCT t.assignee_user_id, COALESCE(au.name, '') AS name
  FROM task t
  LEFT JOIN app_user au ON au.id = t.assignee_user_id
  WHERE t.tenant_id = $1::uuid
    AND t.assignee_user_id IS NOT NULL
) assignees
ORDER BY LOWER(name) ASC
`

type ListTaskAssigneesRow struct {
	AssigneeUserID pgtype.UUID `json:"assignee_user_id"`
	Name           string      `json:"name"`
}

// Selectable ?assignee values for the task agenda ("meus prazos"): the distinct
// responsáveis of the tenant's tasks, deduped by id, ordered by name (case-insensitive).
// The LEFT JOIN app_user resolves a name when the id is a known user (the column is a bare
// uuid with no FK); an unknown id yields an empty name — the FE labels it "ID sem nome".
// Same DISTINCT-inner / ORDER BY-outer shape as ListPrazoKinds (Postgres rejects a bare
// DISTINCT with ORDER BY on an expression outside the select list).
func (q *Queries) ListTaskAssignees(ctx context.Context, tenantID uuid.UUID) ([]ListTaskAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listTaskAssignees, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskAssigneesRow
	for rows.Next() {
		var i ListTaskAssigneesRow
		if err := rows.Scan(&i.AssigneeUserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskComments = `-- name: ListTaskComments :many

SELECT c.id, c.author_user_id, COALESCE(au.name, '')::text AS author_name, c.body, c.created_at
FROM task_comment c
LEFT JOIN app_user au ON au.id = c.author_user_id
WHERE c.task_id = $1::uuid AND c.tenant_id = $2::uuid
ORDER BY c.created_at ASC, c.id ASC
`

type ListTaskCommentsParams struct {
	TaskID   uuid.UUID `json:"task_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type ListTaskCommentsRow struct {
	ID           uuid.UUID          `json:"id"`
	AuthorUserID uuid.UUID          `json:"author_user_id"`
	AuthorName   string             `json:"author_name"`
	Body         string             `json:"body"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// ── task detail: comments + activity (GET /v1/tasks/:id/comments|activity) ────
// The Tarefa detail's Comentários and Atividade tabs. Both resolve the writer/actor to a name
// via LEFT JOIN app_user (the *_user_id columns are bare uuids with no FK, like assignee_user_id)
// so the FE renders "Fulano" not a uuid; an unknown id yields "" (the FE labels it). Both are
// scoped to (task_id, tenant_id) (barrier 1, on top of RLS barrier 2).
// One task's discussion thread, OLDEST-first (the detail view reads top-to-bottom). $1 = task_id,
// $2 = tenant_id. An empty thread is 0 rows (never an error). The comment's author is resolved to
// a name for display.
func (q *Queries) ListTaskComments(ctx context.Context, arg ListTaskCommentsParams) ([]ListTaskCommentsRow, error) {
	rows, err := q.db.Query(ctx, listTaskComments, arg.TaskID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskCommentsRow
	for rows.Next() {
		var i ListTaskCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorUserID,
			&i.AuthorName,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskItems = `-- name: ListTaskItems :many
SELECT id, task_id, title, position, done, done_at, created_at
FROM task_item
WHERE task_id = $1::uuid AND tenant_id = $2::uuid
ORDER BY position ASC, id ASC
`

type ListTaskItemsParams struct {
	TaskID   uuid.UUID `json:"task_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type ListTaskItemsRow struct {
	ID        uuid.UUID          `json:"id"`
	TaskID    uuid.UUID          `json:"task_id"`
	Title     string             `json:"title"`
	Position  int32              `json:"position"`
	Done      bool               `json:"done"`
	DoneAt    pgtype.Timestamptz `json:"done_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// One task's checklist, ordered by position (the detail view). Scoped to (task_id, tenant_id)
// (barrier 1). An empty checklist is 0 rows (not an error). $1 = task_id, $2 = tenant_id.
func (q *Queries) ListTaskItems(ctx context.Context, arg ListTaskItemsParams) ([]ListTaskItemsRow, error) {
	rows, err := q.db.Query(ctx, listTaskItems, arg.TaskID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskItemsRow
	for rows.Next() {
		var i ListTaskItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Title,
			&i.Position,
			&i.Done,
			&i.DoneAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT t.id, t.title, t.description, t.kind, t.priority, t.due_date,
       COALESCE(t.due_date, '9999-12-31')::date AS sort_due,
       t.status, t.source, t.assignee_user_id, t.deadline_id, t.intimation_id,
       t.court_record_id, t.completed_at,
       -- done_items feeds the derived display_status (see ListTasksByProcesso).
       COALESCE(p.done_items, 0)::bigint AS done_items,
       cr.cnj_number, cr.court,
       d.id AS draft_id, d.sent_to_signing_at, d.filed_at
FROM task t
LEFT JOIN LATERAL (
  SELECT count(*) FILTER (WHERE ti.done) AS done_items
  FROM task_item ti
  WHERE ti.task_id = t.id AND ti.tenant_id = t.tenant_id
) p ON true
LEFT JOIN court_record cr ON cr.id = t.court_record_id
LEFT JOIN draft d ON d.task_id = t.id AND d.superseded_at IS NULL
LEFT JOIN action_item ai ON ai.id = t.action_item_id
WHERE t.tenant_id = $1::uuid
  AND t.status <> 'DISMISSED'
  AND ($2::text = '' OR t.status = $2::text)
  AND ($3::uuid IS NULL OR t.assignee_user_id = $3::uuid)
  AND ($4::text = '' OR t.source = $4::text)
  AND ($5::uuid IS NULL OR t.intimation_id = $5::uuid)
  AND ($6::date IS NULL OR t.due_date >= $6::date)
  AND ($7::date IS NULL OR t.due_date <= $7::date)
  AND ($8::bool = false OR d.id IS NOT NULL OR t.kind = 'PECA' OR ai.gera_peca = true)
  AND (COALESCE(t.due_date, '9999-12-31'), t.id) > ($9::date, $10::uuid)
ORDER BY COALESCE(t.due_date, '9999-12-31') ASC, t.id ASC
LIMIT $11
`

type ListTasksParams struct {
	TenantID     uuid.UUID   `json:"tenant_id"`
	Status       string      `json:"status"`
	AssigneeID   pgtype.UUID `json:"assignee_id"`
	Source       string      `json:"source"`
	IntimationID pgtype.UUID `json:"intimation_id"`
	FromDate     pgtype.Date `json:"from_date"`
	ToDate       pgtype.Date `json:"to_date"`
	PipelineOnly bool        `json:"pipeline_only"`
	LastDue      pgtype.Date `json:"last_due"`
	LastID       uuid.UUID   `json:"last_id"`
	PageLimit    int32       `json:"page_limit"`
}

type ListTasksRow struct {
	ID              uuid.UUID          `json:"id"`
	Title           string             `json:"title"`
	Description     *string            `json:"description"`
	Kind            *string            `json:"kind"`
	Priority        *string            `json:"priority"`
	DueDate         pgtype.Date        `json:"due_date"`
	SortDue         pgtype.Date        `json:"sort_due"`
	Status          string             `json:"status"`
	Source          string             `json:"source"`
	AssigneeUserID  pgtype.UUID        `json:"assignee_user_id"`
	DeadlineID      pgtype.UUID        `json:"deadline_id"`
	IntimationID    pgtype.UUID        `json:"intimation_id"`
	CourtRecordID   pgtype.UUID        `json:"court_record_id"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	DoneItems       int64              `json:"done_items"`
	CnjNumber       *string            `json:"cnj_number"`
	Court           *string            `json:"court"`
	DraftID         pgtype.UUID        `json:"draft_id"`
	SentToSigningAt pgtype.Timestamptz `json:"sent_to_signing_at"`
	FiledAt         pgtype.Timestamptz `json:"filed_at"`
}

// The global task agenda (GET /v1/tasks, "meus prazos"): the tenant's tasks, soonest due
// first (undated last). Optional filters: @status (” = all), @assignee_id (NULL = all
// assignees; = principal.UserID for "meus"), @source (” = all), @intimation_id (NULL =
// all; = a specific intimation uuid to list only tasks of that intimação) and a due_date
// window [@from_date, @to_date] (NULL = open bound). The window filters on the REAL
// due_date, so it naturally EXCLUDES undated tasks (NULL >= date is NULL) — a dated-window
// query wants dated items. Ascending (sort_due, id) keyset; the first page passes the min
// sentinel ('0001-01-01', zero-uuid). cnj_number/court come from a LEFT JOIN on
// court_record (mirrors ListPrazos/GetPrazoSuggestContext) — LEFT, not JOIN, because
// task.court_record_id is nullable (an avulsa task hangs on no process, so it carries no
// context; the columns come back NULL/"" rather than dropping the row). DISMISSED is always
// excluded (a dispensada task is out of the agenda, not just out of the cockpit derivation).
// draft_id/sent_to_signing_at/filed_at come from a LEFT JOIN on the task's VIGENTE draft
// (superseded_at IS NULL — draft_task_id_uidx, migration 0089, guarantees at most one such
// row per task), and gera_peca (via action_item, LEFT JOIN on task.action_item_id) — the
// ingredients read.go's derivePipelineStage turns into pipeline_stage. @pipeline_only (bool)
// restricts to "peça-bound" tasks (has a draft, OR kind='PECA', OR the providência gera_peca)
// when true; false (the default) leaves every non-DISMISSED task in.
func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.TenantID,
		arg.Status,
		arg.AssigneeID,
		arg.Source,
		arg.IntimationID,
		arg.FromDate,
		arg.ToDate,
		arg.PipelineOnly,
		arg.LastDue,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksRow
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Kind,
			&i.Priority,
			&i.DueDate,
			&i.SortDue,
			&i.Status,
			&i.Source,
			&i.AssigneeUserID,
			&i.DeadlineID,
			&i.IntimationID,
			&i.CourtRecordID,
			&i.CompletedAt,
			&i.DoneItems,
			&i.CnjNumber,
			&i.Court,
			&i.DraftID,
			&i.SentToSigningAt,
			&i.FiledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProcesso = `-- name: ListTasksByProcesso :many

SELECT t.id, t.title, t.description, t.kind, t.priority, t.due_date,
       COALESCE(t.due_date, '9999-12-31')::date AS sort_due,
       t.status, t.source, t.assignee_user_id, t.deadline_id, t.intimation_id,
       t.court_record_id, t.completed_at,
       -- done_items feeds the derived display_status (Em execução once any item is ticked);
       -- the FE bucket reads it via display_status, not this raw count.
       COALESCE(p.done_items, 0)::bigint AS done_items
FROM task t
LEFT JOIN LATERAL (
  SELECT count(*) FILTER (WHERE ti.done) AS done_items
  FROM task_item ti
  WHERE ti.task_id = t.id AND ti.tenant_id = t.tenant_id
) p ON true
WHERE t.court_record_id = $1::uuid
  AND t.tenant_id = $2::uuid
  AND (COALESCE(t.due_date, '9999-12-31'), t.id) > ($3::date, $4::uuid)
ORDER BY COALESCE(t.due_date, '9999-12-31') ASC, t.id ASC
LIMIT $5
`

type ListTasksByProcessoParams struct {
	CourtRecordID uuid.UUID   `json:"court_record_id"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	LastDue       pgtype.Date `json:"last_due"`
	LastID        uuid.UUID   `json:"last_id"`
	PageLimit     int32       `json:"page_limit"`
}

type ListTasksByProcessoRow struct {
	ID             uuid.UUID          `json:"id"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	Kind           *string            `json:"kind"`
	Priority       *string            `json:"priority"`
	DueDate        pgtype.Date        `json:"due_date"`
	SortDue        pgtype.Date        `json:"sort_due"`
	Status         string             `json:"status"`
	Source         string             `json:"source"`
	AssigneeUserID pgtype.UUID        `json:"assignee_user_id"`
	DeadlineID     pgtype.UUID        `json:"deadline_id"`
	IntimationID   pgtype.UUID        `json:"intimation_id"`
	CourtRecordID  pgtype.UUID        `json:"court_record_id"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	DoneItems      int64              `json:"done_items"`
}

// ── task read models (GET /v1/processos/:id/tasks, GET /v1/tasks) ────────────
// The task agenda reads soonest-due first, but due_date is NULLABLE (an undated backlog
// task). Decisão travada: undated tasks sort LAST (a task with no date has no urgency, so it
// trails the dated ones). We model NULLS LAST as a computed sort key
// COALESCE(due_date, '9999-12-31') so the SAME ascending (sort_due, id) keyset the prazos
// reads use works unchanged (a min sentinel '0001-01-01' for the first page; the handler
// carries sort_due, not the raw due_date, into the next cursor). The read models expose the
// REAL due_date (NULL for undated) — sort_due is a query-internal keyset column.
// The Tasks tab of one process (GET /v1/processos/:id/tasks): the tasks anchored on the
// court_record, soonest due first (undated last). ALL statuses (the tab is not filtered — the
// FE decides what to show). @court_record_id is the court_record id; an avulsa task (NULL
// court_record_id) never matches, so it is absent from a process tab (correct — it hangs on no
// process). Scoped to tenant_id (barrier 1).
func (q *Queries) ListTasksByProcesso(ctx context.Context, arg ListTasksByProcessoParams) ([]ListTasksByProcessoRow, error) {
	rows, err := q.db.Query(ctx, listTasksByProcesso,
		arg.CourtRecordID,
		arg.TenantID,
		arg.LastDue,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByProcessoRow
	for rows.Next() {
		var i ListTasksByProcessoRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Kind,
			&i.Priority,
			&i.DueDate,
			&i.SortDue,
			&i.Status,
			&i.Source,
			&i.AssigneeUserID,
			&i.DeadlineID,
			&i.IntimationID,
			&i.CourtRecordID,
			&i.CompletedAt,
			&i.DoneItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
