// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analise.sql

package acquisitiondb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getIntimacaoAnaliseContext = `-- name: GetIntimacaoAnaliseContext :one

SELECT i.content, i.type,
       cr.id AS court_record_id, cr.cnj_number, cr.court, cr.degree, cr.class, cr.subject,
       d.id AS deadline_id, d.end_date AS deadline_end_date
FROM intimation i
JOIN court_record cr ON cr.id = i.court_record_id
LEFT JOIN deadline d ON d.notification_id = i.id AND d.tenant_id = i.tenant_id
                     AND d.status IN ('PENDING', 'OPEN')
WHERE i.id = $1 AND i.tenant_id = $2
ORDER BY d.end_date ASC
LIMIT 1
`

type GetIntimacaoAnaliseContextParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetIntimacaoAnaliseContextRow struct {
	Content         string      `json:"content"`
	Type            *string     `json:"type"`
	CourtRecordID   uuid.UUID   `json:"court_record_id"`
	CnjNumber       string      `json:"cnj_number"`
	Court           string      `json:"court"`
	Degree          string      `json:"degree"`
	Class           *string     `json:"class"`
	Subject         *string     `json:"subject"`
	DeadlineID      pgtype.UUID `json:"deadline_id"`
	DeadlineEndDate pgtype.Date `json:"deadline_end_date"`
}

// analise.sql — queries for the AI analysis of one intimation (POST /v1/intimacoes/:id/analise).
// GetIntimacaoAnaliseContext reads the teor + the court context the prompt needs; the write
// query OVERWRITES the ai_summary/ai_analyzed_at columns (re-executable — "Gerar novamente"
// re-runs it). The providências themselves are NO LONGER persisted here as jsonb — Analisar
// publishes acquisition.intimation.analyzed instead, and the actionitem slice's listener
// materializes real action_item rows from it (docs/erd-costura-providencia-tarefa-peca.md).
// One intimation's teor plus its court record's identification and the derived prazo end_date
// (LEFT JOIN deadline on notification_id — NULL when no prazo yet; the IA uses it as the ceiling
// for suggested due_dates). court_record_id/deadline_id are carried through so the caller can
// stamp them onto the acquisition.intimation.analyzed event without a second round-trip — the
// actionitem slice's materialized action_item rows need both. Scoped by tenant_id + intimation
// id (barrier 1). A miss/foreign row → pgx.ErrNoRows → ErrIntimationNotFound (the same 404
// semantics as GetIntimacao). type is nullable.
func (q *Queries) GetIntimacaoAnaliseContext(ctx context.Context, arg GetIntimacaoAnaliseContextParams) (GetIntimacaoAnaliseContextRow, error) {
	row := q.db.QueryRow(ctx, getIntimacaoAnaliseContext, arg.ID, arg.TenantID)
	var i GetIntimacaoAnaliseContextRow
	err := row.Scan(
		&i.Content,
		&i.Type,
		&i.CourtRecordID,
		&i.CnjNumber,
		&i.Court,
		&i.Degree,
		&i.Class,
		&i.Subject,
		&i.DeadlineID,
		&i.DeadlineEndDate,
	)
	return i, err
}

const insertProcessActivityLog = `-- name: InsertProcessActivityLog :exec
INSERT INTO process_activity_log (tenant_id, court_record_id, event_type, payload)
VALUES ($1, $2, $3, $4)
`

type InsertProcessActivityLogParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	CourtRecordID uuid.UUID `json:"court_record_id"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
}

// Appends one row to the process's activity log (docs — Cockpit "Atividade" timeline).
// event_type is the closed set the migration's CHECK enforces; payload carries the
// event-specific detail as jsonb. Scoped by tenant_id (barrier 1) + RLS (barrier 2). Called
// LOG-NOT-FAIL by producers: a failed insert here must never roll back the write it
// documents, so callers log-and-continue on error instead of propagating it.
func (q *Queries) InsertProcessActivityLog(ctx context.Context, arg InsertProcessActivityLogParams) error {
	_, err := q.db.Exec(ctx, insertProcessActivityLog,
		arg.TenantID,
		arg.CourtRecordID,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const listActiveMembers = `-- name: ListActiveMembers :many
SELECT u.id, u.name
FROM membership m
JOIN app_user u ON u.id = m.app_user_id AND u.tenant_id = m.tenant_id
WHERE m.tenant_id = $1 AND m.status = 'ACTIVE'
ORDER BY u.name, u.id
`

type ListActiveMembersRow struct {
	ID   uuid.UUID `json:"id"`
	Name *string   `json:"name"`
}

// The tenant's ACTIVE firm members (internal app_user id + name) — the assignable responsáveis
// the analyze_intimation prompt lists so the IA suggests a real assignee. Same join as identity's
// ListOrgMembers (membership status ACTIVE), projected to just id+name; ordered by name for a
// stable prompt. Scoped by tenant_id (barrier 1). Reused only for the AI analysis context.
func (q *Queries) ListActiveMembers(ctx context.Context, tenantID uuid.UUID) ([]ListActiveMembersRow, error) {
	rows, err := q.db.Query(ctx, listActiveMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveMembersRow
	for rows.Next() {
		var i ListActiveMembersRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIntimationAIAnalysis = `-- name: SetIntimationAIAnalysis :one
UPDATE intimation
SET ai_summary      = $1,
    ai_analyzed_at  = now()
WHERE id = $2
  AND tenant_id = $3
RETURNING court_record_id
`

type SetIntimationAIAnalysisParams struct {
	AiSummary *string   `json:"ai_summary"`
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

// Persists (OVERWRITES) the AI analysis of one intimation's ai_summary/ai_analyzed_at. Unlike
// SetCourtRecordAIResume there is NO write-once guard — the analysis is re-executable ("Gerar
// novamente"). Scoped by tenant_id (barrier 1). Degraded mode passes ai_summary=”.
// RETURNING court_record_id so the caller can log a process_activity_log row in the SAME
// tx, without a second round-trip to look up the owning court record.
func (q *Queries) SetIntimationAIAnalysis(ctx context.Context, arg SetIntimationAIAnalysisParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, setIntimationAIAnalysis, arg.AiSummary, arg.ID, arg.TenantID)
	var court_record_id uuid.UUID
	err := row.Scan(&court_record_id)
	return court_record_id, err
}
