// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analise.sql

package acquisitiondb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getIntimacaoAnaliseContext = `-- name: GetIntimacaoAnaliseContext :one

SELECT i.content, i.type,
       cr.cnj_number, cr.court, cr.degree, cr.class, cr.subject,
       d.end_date AS deadline_end_date
FROM intimation i
JOIN court_record cr ON cr.id = i.court_record_id
LEFT JOIN deadline d ON d.notification_id = i.id AND d.tenant_id = i.tenant_id
                     AND d.status IN ('PENDING', 'OPEN')
WHERE i.id = $1 AND i.tenant_id = $2
ORDER BY d.end_date ASC
LIMIT 1
`

type GetIntimacaoAnaliseContextParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetIntimacaoAnaliseContextRow struct {
	Content         string      `json:"content"`
	Type            *string     `json:"type"`
	CnjNumber       string      `json:"cnj_number"`
	Court           string      `json:"court"`
	Degree          string      `json:"degree"`
	Class           *string     `json:"class"`
	Subject         *string     `json:"subject"`
	DeadlineEndDate pgtype.Date `json:"deadline_end_date"`
}

// analise.sql — queries for the AI analysis of one intimation (POST /v1/intimacoes/:id/analise).
// GetIntimacaoAnaliseContext reads the teor + the court context the prompt needs; the write
// query OVERWRITES the three ai_* columns (re-executable — "Gerar novamente" re-runs it).
// One intimation's teor plus its court record's identification and the derived prazo end_date
// (LEFT JOIN deadline on notification_id — NULL when no prazo yet; the IA uses it as the ceiling
// for suggested due_dates). Scoped by tenant_id + intimation id (barrier 1). A miss/foreign row →
// pgx.ErrNoRows → ErrIntimationNotFound (the same 404 semantics as GetIntimacao). type is nullable.
func (q *Queries) GetIntimacaoAnaliseContext(ctx context.Context, arg GetIntimacaoAnaliseContextParams) (GetIntimacaoAnaliseContextRow, error) {
	row := q.db.QueryRow(ctx, getIntimacaoAnaliseContext, arg.ID, arg.TenantID)
	var i GetIntimacaoAnaliseContextRow
	err := row.Scan(
		&i.Content,
		&i.Type,
		&i.CnjNumber,
		&i.Court,
		&i.Degree,
		&i.Class,
		&i.Subject,
		&i.DeadlineEndDate,
	)
	return i, err
}

const getIntimationProvidenciasForUpdate = `-- name: GetIntimationProvidenciasForUpdate :one
SELECT ai_providencias, ai_analyzed_at
FROM intimation
WHERE id = $1 AND tenant_id = $2
FOR UPDATE
`

type GetIntimationProvidenciasForUpdateParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetIntimationProvidenciasForUpdateRow struct {
	AiProvidencias []byte             `json:"ai_providencias"`
	AiAnalyzedAt   pgtype.Timestamptz `json:"ai_analyzed_at"`
}

// Reads the ai_providencias jsonb + ai_analyzed_at of one intimation, locking the row
// (FOR UPDATE) so an aprovar/descartar read-modify-write is serialized. NULL ai_analyzed_at
// (never analysed) vs a set stamp lets the use case reject a status change on an un-analysed
// intimation. Scoped by tenant_id (barrier 1); a miss/foreign row → pgx.ErrNoRows.
func (q *Queries) GetIntimationProvidenciasForUpdate(ctx context.Context, arg GetIntimationProvidenciasForUpdateParams) (GetIntimationProvidenciasForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getIntimationProvidenciasForUpdate, arg.ID, arg.TenantID)
	var i GetIntimationProvidenciasForUpdateRow
	err := row.Scan(&i.AiProvidencias, &i.AiAnalyzedAt)
	return i, err
}

const insertProcessActivityLog = `-- name: InsertProcessActivityLog :exec
INSERT INTO process_activity_log (tenant_id, court_record_id, event_type, payload)
VALUES ($1, $2, $3, $4)
`

type InsertProcessActivityLogParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	CourtRecordID uuid.UUID `json:"court_record_id"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
}

// Appends one row to the process's activity log (docs — Cockpit "Atividade" timeline).
// event_type is the closed set the migration's CHECK enforces; payload carries the
// event-specific detail as jsonb. Scoped by tenant_id (barrier 1) + RLS (barrier 2). Called
// LOG-NOT-FAIL by producers: a failed insert here must never roll back the write it
// documents, so callers log-and-continue on error instead of propagating it.
func (q *Queries) InsertProcessActivityLog(ctx context.Context, arg InsertProcessActivityLogParams) error {
	_, err := q.db.Exec(ctx, insertProcessActivityLog,
		arg.TenantID,
		arg.CourtRecordID,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const listActiveMembers = `-- name: ListActiveMembers :many
SELECT u.id, u.name
FROM membership m
JOIN app_user u ON u.id = m.app_user_id AND u.tenant_id = m.tenant_id
WHERE m.tenant_id = $1 AND m.status = 'ACTIVE'
ORDER BY u.name, u.id
`

type ListActiveMembersRow struct {
	ID   uuid.UUID `json:"id"`
	Name *string   `json:"name"`
}

// The tenant's ACTIVE firm members (internal app_user id + name) — the assignable responsáveis
// the analyze_intimation prompt lists so the IA suggests a real assignee. Same join as identity's
// ListOrgMembers (membership status ACTIVE), projected to just id+name; ordered by name for a
// stable prompt. Scoped by tenant_id (barrier 1). Reused only for the AI analysis context.
func (q *Queries) ListActiveMembers(ctx context.Context, tenantID uuid.UUID) ([]ListActiveMembersRow, error) {
	rows, err := q.db.Query(ctx, listActiveMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveMembersRow
	for rows.Next() {
		var i ListActiveMembersRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIntimationAIAnalysis = `-- name: SetIntimationAIAnalysis :one
UPDATE intimation
SET ai_summary      = $1,
    ai_providencias = $2,
    ai_act          = $3,
    ai_analyzed_at  = now()
WHERE id = $4
  AND tenant_id = $5
RETURNING court_record_id
`

type SetIntimationAIAnalysisParams struct {
	AiSummary      *string   `json:"ai_summary"`
	AiProvidencias []byte    `json:"ai_providencias"`
	AiAct          *string   `json:"ai_act"`
	ID             uuid.UUID `json:"id"`
	TenantID       uuid.UUID `json:"tenant_id"`
}

// Persists (OVERWRITES) the AI analysis of one intimation. Unlike SetCourtRecordAIResume
// there is NO write-once guard — the analysis is re-executable ("Gerar novamente"). Scoped
// by tenant_id (barrier 1). Degraded mode passes ai_summary=” + ai_providencias='[]'.
// RETURNING court_record_id so the caller can log a process_activity_log row in the SAME
// tx, without a second round-trip to look up the owning court record.
func (q *Queries) SetIntimationAIAnalysis(ctx context.Context, arg SetIntimationAIAnalysisParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, setIntimationAIAnalysis,
		arg.AiSummary,
		arg.AiProvidencias,
		arg.AiAct,
		arg.ID,
		arg.TenantID,
	)
	var court_record_id uuid.UUID
	err := row.Scan(&court_record_id)
	return court_record_id, err
}

const setIntimationProvidencias = `-- name: SetIntimationProvidencias :exec
UPDATE intimation
SET ai_providencias = $1
WHERE id = $2 AND tenant_id = $3
`

type SetIntimationProvidenciasParams struct {
	AiProvidencias []byte    `json:"ai_providencias"`
	ID             uuid.UUID `json:"id"`
	TenantID       uuid.UUID `json:"tenant_id"`
}

// Overwrites ONLY the ai_providencias jsonb (leaves ai_summary / ai_analyzed_at untouched) —
// the write half of the aprovar/descartar status flip. Scoped by tenant_id (barrier 1).
func (q *Queries) SetIntimationProvidencias(ctx context.Context, arg SetIntimationProvidenciasParams) error {
	_, err := q.db.Exec(ctx, setIntimationProvidencias, arg.AiProvidencias, arg.ID, arg.TenantID)
	return err
}
