// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integration.sql

package acquisitiondb

import (
	"context"

	"github.com/google/uuid"
)

const getIntegrationBySource = `-- name: GetIntegrationBySource :one
SELECT id, tenant_id, source, scope, credential_ref, status, created_at, updated_at FROM integration
WHERE tenant_id = $1 AND source = $2
`

type GetIntegrationBySourceParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Source   string    `json:"source"`
}

func (q *Queries) GetIntegrationBySource(ctx context.Context, arg GetIntegrationBySourceParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationBySource, arg.TenantID, arg.Source)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.Scope,
		&i.CredentialRef,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT id, tenant_id, source, scope, credential_ref, status, created_at, updated_at FROM integration
WHERE tenant_id = $1
ORDER BY created_at, id
`

// All of a tenant's integrations, oldest first. tenant_id filter is isolation
// barrier 1 (the app layer); RLS is barrier 2.
func (q *Queries) ListIntegrations(ctx context.Context, tenantID uuid.UUID) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Integration
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Source,
			&i.Scope,
			&i.CredentialRef,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIntegration = `-- name: UpsertIntegration :one

INSERT INTO integration (tenant_id, source, scope, status)
VALUES ($1, $2, $3, 'ACTIVE')
ON CONFLICT (tenant_id, source) DO UPDATE
   SET scope      = EXCLUDED.scope,
       status     = 'ACTIVE',
       updated_at = now()
RETURNING id, tenant_id, source, scope, credential_ref, status, created_at, updated_at
`

type UpsertIntegrationParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Source   string    `json:"source"`
	Scope    []byte    `json:"scope"`
}

// acquisition slice queries (integration).
// The upsert is keyed by (tenant_id, source) so re-activating a source is
// idempotent at the row level; credential_ref is never written from here (it
// stays NULL in v0) and is preserved across updates.
// Activate (or re-activate) a tenant's subscription to a data source. On
// conflict only scope/status/updated_at change — credential_ref is left intact.
func (q *Queries) UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, upsertIntegration, arg.TenantID, arg.Source, arg.Scope)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.Scope,
		&i.CredentialRef,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
