// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parties.sql

package acquisitiondb

import (
	"context"

	"github.com/google/uuid"
)

const batchUpsertParties = `-- name: BatchUpsertParties :many

INSERT INTO party (tenant_id, case_id, role, name, source)
SELECT $1::uuid, r.case_id, r.role, r.name, 'DJEN'
FROM jsonb_to_recordset($2::jsonb) AS r(
    case_id uuid, role text, name text
)
ON CONFLICT (tenant_id, case_id, role, name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, case_id, role, name
`

type BatchUpsertPartiesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Parties  []byte    `json:"parties"`
}

type BatchUpsertPartiesRow struct {
	ID     uuid.UUID `json:"id"`
	CaseID uuid.UUID `json:"case_id"`
	Role   string    `json:"role"`
	Name   string    `json:"name"`
}

// parties.sql (acquisition slice) — the process's partes (autor/réu/terceiro) and
// their advogados, materialized from the DJEN so the cockpit renders the AUTOR/RÉU
// cards. Two write paths (idempotent bulk upserts, run in the sync tx) and one read
// (the /processos/:id/partes deep-read). All tenant-scoped (barrier 1) on top of RLS.
// Upsert MANY parties in one round-trip from a jsonb array of {case_id, role, name}.
// Idempotent on the natural key (tenant, case, role, name): a re-observation of the
// same communication re-lands the same rows. ON CONFLICT DO UPDATE (a no-op touch of
// name) rather than DO NOTHING so the RETURNING yields the row id whether it was just
// inserted OR already existed — the caller needs every party's id to attach its
// advogados. document stays NULL (v0 never discloses CPF/CNPJ); source is DJEN.
// RETURNING role+name lets the caller map each party id back to its parsed counsels.
func (q *Queries) BatchUpsertParties(ctx context.Context, arg BatchUpsertPartiesParams) ([]BatchUpsertPartiesRow, error) {
	rows, err := q.db.Query(ctx, batchUpsertParties, arg.TenantID, arg.Parties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchUpsertPartiesRow
	for rows.Next() {
		var i BatchUpsertPartiesRow
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.Role,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const batchUpsertPartyCounsels = `-- name: BatchUpsertPartyCounsels :exec
INSERT INTO party_counsel (tenant_id, party_id, name, oab, uf, source)
SELECT $1::uuid, r.party_id, r.name, r.oab, r.uf, 'DJEN'
FROM jsonb_to_recordset($2::jsonb) AS r(
    party_id uuid, name text, oab text, uf text
)
ON CONFLICT (tenant_id, party_id, oab, uf) DO NOTHING
`

type BatchUpsertPartyCounselsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Counsels []byte    `json:"counsels"`
}

// Upsert MANY advogados in one round-trip from a jsonb array of {party_id, name, oab,
// uf}. Idempotent on (tenant, party, oab, uf): ON CONFLICT DO NOTHING, so a re-observation
// neither duplicates nor errors. source is DJEN. The name is refreshed only on insert
// (a DO NOTHING leaves the existing row) — an advogado's OAB is the stable identity.
func (q *Queries) BatchUpsertPartyCounsels(ctx context.Context, arg BatchUpsertPartyCounselsParams) error {
	_, err := q.db.Exec(ctx, batchUpsertPartyCounsels, arg.TenantID, arg.Counsels)
	return err
}

const listPartiesByProcesso = `-- name: ListPartiesByProcesso :many
SELECT p.id, p.role, p.name, p.document,
       -- Cast to text so pgx scans a JSON string (a plain jsonb column decodes into a Go
       -- map/slice for an interface{} target, not raw bytes); the repo unmarshals the text.
       COALESCE(
         (SELECT jsonb_agg(jsonb_build_object('name', pc.name, 'oab', pc.oab, 'uf', pc.uf)
                           ORDER BY pc.name)
          FROM party_counsel pc
          WHERE pc.party_id = p.id),
         '[]'::jsonb
       )::text AS counsels
FROM party p
WHERE p.tenant_id = $1::uuid
  AND p.case_id = (
      SELECT cr.case_id FROM court_record cr
      WHERE cr.id = $2::uuid AND cr.tenant_id = $1::uuid
  )
ORDER BY p.role, p.name
`

type ListPartiesByProcessoParams struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	CourtRecordID uuid.UUID `json:"court_record_id"`
}

type ListPartiesByProcessoRow struct {
	ID       uuid.UUID `json:"id"`
	Role     string    `json:"role"`
	Name     string    `json:"name"`
	Document *string   `json:"document"`
	Counsels string    `json:"counsels"`
}

// The /processos/:id/partes deep-read: every party of the process behind a court_record
// :id, with its advogados aggregated as a jsonb array (name/oab/uf), in one round-trip.
// Isolation: court_record → court_case resolves the case, scoped by tenant_id (barrier 1);
// a foreign or unknown :id resolves to no case and yields no rows. Ordered by role then
// name so the caller buckets autor/réu/terceiro deterministically. counsels defaults to
// an empty jsonb array (never NULL) when a party has no advogado.
func (q *Queries) ListPartiesByProcesso(ctx context.Context, arg ListPartiesByProcessoParams) ([]ListPartiesByProcessoRow, error) {
	rows, err := q.db.Query(ctx, listPartiesByProcesso, arg.TenantID, arg.CourtRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartiesByProcessoRow
	for rows.Next() {
		var i ListPartiesByProcessoRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Name,
			&i.Document,
			&i.Counsels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
