// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package acquisitiondb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetIntegrationBySource(ctx context.Context, arg GetIntegrationBySourceParams) (Integration, error)
	// All of a tenant's integrations, oldest first. tenant_id filter is isolation
	// barrier 1 (the app layer); RLS is barrier 2.
	ListIntegrations(ctx context.Context, tenantID uuid.UUID) ([]Integration, error)
	// acquisition slice queries (integration).
	// The upsert is keyed by (tenant_id, source) so re-activating a source is
	// idempotent at the row level; credential_ref is never written from here (it
	// stays NULL in v0) and is preserved across updates.
	// Activate (or re-activate) a tenant's subscription to a data source. On
	// conflict only scope/status/updated_at change — credential_ref is left intact.
	UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) (Integration, error)
}

var _ Querier = (*Queries)(nil)
