// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package acquisitiondb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Serialize the acquisition domain's WRITES per tenant. The sync and enrichment
	// write transactions take this transaction-scoped advisory lock as their FIRST
	// statement, so two concurrent slices never hold overlapping row/index locks on
	// court_record and thus never deadlock (40P01) — while their slow DJEN/DATAJUD
	// fetches (which run OUTSIDE the tx) still overlap freely. Postgres releases the
	// lock automatically at commit/rollback. The key is hashed from the tenant, so
	// different tenants never block each other; hashtext is int4, widened to the int8
	// pg_advisory_xact_lock expects.
	AcquireTenantWriteLock(ctx context.Context, tenantID string) error
	// Membership guard for the assign write: is $1 an app_user of tenant $2? Used only when
	// a non-null user_id is being assigned (desatribuir skips it). A false result → the
	// typed "usuário não é membro do escritório" (→ 404/invalid) so a caller cannot pin a
	// process on a user outside their escritório.
	AppUserExistsInTenant(ctx context.Context, arg AppUserExistsInTenantParams) (bool, error)
	// Set (or clear, when $2 is NULL) the responsável on a court_case, tenant-scoped
	// (barrier 1, with RLS as barrier 2). The case_id is the one resolved from the
	// court_record above; the WHERE ties the write to the caller's own tenant so a mismatched
	// (case, tenant) touches nothing. Idempotent — re-assigning the same user is a no-op write.
	AssignCaseResponsible(ctx context.Context, arg AssignCaseResponsibleParams) error
	// Set (or clear, via NULL) the single assignee_user_id on one intimation,
	// tenant-scoped (barrier 1, RLS barrier 2). Nullable: passing NULL desatribui.
	// The use case pre-validates membership (AppUserExistsInTenant) before calling
	// this, so the FK is always satisfied when non-null. A zero-row result (unknown
	// id or foreign tenant's row) surfaces as pgx.ErrNoRows → ErrIntimationNotFound
	// (→ 404). Idempotent: re-assigning the same user re-writes the same value.
	AssignIntimationAssignee(ctx context.Context, arg AssignIntimationAssigneeParams) (uuid.UUID, error)
	// backfill_job queries (acquisition slice).
	// The backfill listener reacts to integration_activated: on the FIRST activation
	// of an integration it creates one backfill_job and emits the sync slices. These
	// two queries are the job's first-activation guard (exists) and its insert; the
	// counters/completion (slices_ok, slices_error, final status) belong to the sync
	// slice, not here.
	// True when a backfill_job already exists for this integration (any status). The
	// listener uses it as the first-activation guard: a re-activation must not
	// re-dispatch a backfill.
	BackfillJobExistsByIntegration(ctx context.Context, integrationID uuid.UUID) (bool, error)
	// Create N fresh lides in one round-trip (v0: one case per new record). Returns the
	// N new ids; the caller pairs each with a new court_record.
	BatchInsertCourtCases(ctx context.Context, arg BatchInsertCourtCasesParams) ([]uuid.UUID, error)
	// Bulk create of first-seen records from a jsonb array of rows: folds the post-sync
	// fields (completeness/judging_body/next_sync_at) straight into the INSERT, so a NEW
	// record needs no separate MarkCourtRecordSynced. JSON null → SQL NULL naturally
	// (nullable class/subject/judging_body/sync_run_id). ON CONFLICT DO NOTHING keeps it
	// idempotent (a re-run of the window no-ops on rows it already created); RETURNING the
	// natural key lets the caller map ids back to input order. Under the per-tenant
	// advisory lock there is no concurrent same-tenant writer, so the conflict path only
	// fires on a genuine re-run, never a create race.
	BatchInsertCourtRecords(ctx context.Context, arg BatchInsertCourtRecordsParams) ([]BatchInsertCourtRecordsRow, error)
	// Bulk counterpart of InsertDocketEntry: insert MANY andamentos in ONE round-trip from
	// a jsonb array of rows, ON CONFLICT (court_record_id, hash) DO NOTHING (idempotent).
	// Only the rows that were ACTUALLY new are returned (DO NOTHING omits conflicts), so the
	// caller maps them back to build the observed events. This is what keeps the enrichment's
	// per-tenant write lock hold short even for a process with a long movimento history.
	BatchInsertDocketEntries(ctx context.Context, entries []byte) ([]BatchInsertDocketEntriesRow, error)
	// Bulk MarkCourtRecordSynced for reobserved (already-existing) records: refresh
	// completeness/next_sync_at and COALESCE judging_body/class/subject (a sync that
	// omits them keeps the prior value; a sync that supplies them overwrites — COALESCE on
	// NULLIF('', prior) so an empty string from the source does not clobber a real value).
	// class and subject are included so a tribunal correction in DJEN/DATAJUD propagates
	// on the next re-sync instead of being frozen at the first-seen value.
	// completeness uses GREATEST (never DOWNGRADE): a DJEN re-observation (0.3) must NOT
	// clobber a prior DATAJUD enrichment (0.9). Without this the churn of a backfill
	// re-discovering the same process across windows/OABs erases every enrichment.
	BatchMarkCourtRecordsSynced(ctx context.Context, updates []byte) error
	// Bulk counterpart of InsertIntimation: upsert MANY intimações in one round-trip from
	// a jsonb array of rows. Same ON CONFLICT (tenant, case, hash) DO UPDATE as the single
	// version (a retracted publication re-arrives with the same hash carrying CANCELLED).
	// JSON handles it all: null → NULL (nullable dates/type/source_url), and recipients
	// (text[]) maps from a JSON array.
	//
	// The RETURNING is enriched so the producer can emit the right domain event per row,
	// in the SAME tx, without the deadline slice reading anything back:
	//   • inserted  ((xmax = 0)) — a FIRST insert → intimation.observed;
	//   • old_status — the status BEFORE this upsert, read by a correlated subquery on
	//     `intimation`. A data-modifying CTE and the main query share one snapshot, so
	//     the subquery cannot see `upserted`'s effect and returns the PRE-upsert row (a
	//     fresh insert has no prior row → NULL → ''). old_status <> 'CANCELLED' + new
	//     status = 'CANCELLED' on an UPDATE is the ACTIVE → CANCELLED transition →
	//     intimation.cancelled.
	//   • court — denormalized from the row's court_record (a join), so the producer
	//     derives uf via ufFromTribunal at emission.
	BatchUpsertIntimations(ctx context.Context, arg BatchUpsertIntimationsParams) ([]BatchUpsertIntimationsRow, error)
	// parties.sql (acquisition slice) — the process's partes (autor/réu/terceiro) and
	// their advogados, materialized from the DJEN so the cockpit renders the AUTOR/RÉU
	// cards. Two write paths (idempotent bulk upserts, run in the sync tx) and one read
	// (the /processos/:id/partes deep-read). All tenant-scoped (barrier 1) on top of RLS.
	// Upsert MANY parties in one round-trip from a jsonb array of {case_id, role, name}.
	// Idempotent on the natural key (tenant, case, role, name): a re-observation of the
	// same communication re-lands the same rows. ON CONFLICT DO UPDATE (a no-op touch of
	// name) rather than DO NOTHING so the RETURNING yields the row id whether it was just
	// inserted OR already existed — the caller needs every party's id to attach its
	// advogados. document stays NULL (v0 never discloses CPF/CNPJ); source is DJEN.
	// RETURNING role+name lets the caller map each party id back to its parsed counsels.
	BatchUpsertParties(ctx context.Context, arg BatchUpsertPartiesParams) ([]BatchUpsertPartiesRow, error)
	// Upsert MANY advogados in one round-trip from a jsonb array of {party_id, name, oab,
	// uf}. Idempotent on (tenant, party, oab, uf): ON CONFLICT DO NOTHING, so a re-observation
	// neither duplicates nor errors. source is DJEN. The name is refreshed only on insert
	// (a DO NOTHING leaves the existing row) — an advogado's OAB is the stable identity.
	BatchUpsertPartyCounsels(ctx context.Context, arg BatchUpsertPartyCounselsParams) error
	// Atribuição em massa do responsável para TODA a faixa/filtro atual (modo
	// "todos" da UI — inclui linhas ainda não paginadas). Reusa EXATAMENTE a
	// cláusula de filtro do ListIntimacoes (search/type/user_status/court/assignee/
	// urgencia) via subquery. tenant-scoped (barrier 1, RLS barrier 2).
	BulkAssignIntimacoesByFilter(ctx context.Context, arg BulkAssignIntimacoesByFilterParams) (int64, error)
	// Atribuição em massa do responsável para uma lista explícita de ids,
	// tenant-scoped (barrier 1, RLS barrier 2). NULL desatribui.
	BulkAssignIntimacoesByIDs(ctx context.Context, arg BulkAssignIntimacoesByIDsParams) (int64, error)
	// Push a record's next_sync_at forward as its re-poll is enqueued, so the next tick
	// does not re-enqueue it; if the resync never lands, it falls due again after the
	// interval (at-least-once).
	ClaimCourtRecordResync(ctx context.Context, arg ClaimCourtRecordResyncParams) error
	// Fecho por ETA da linha ENRICHMENT de uma importação: carimba o status terminal
	// (@status = OK quando a cobertura foi atingida, PARTIAL senão) e finished_at = @at. Roda
	// no listener do EnrichmentRunCloseScheduled, agendado no fim do backfill + carência. Só
	// afeta a linha ENRICHMENT daquela importação. Retorna o número de linhas afetadas: 0
	// significa que a importação não aplicou nenhum enriquecimento (nenhuma linha foi criada)
	// — o listener trata esse caso criando uma linha honesta com updated=0.
	CloseImportEnrichmentRun(ctx context.Context, arg CloseImportEnrichmentRunParams) (int64, error)
	// Count the tenant's ACTIVE court records inside the caller's tx. The entitlement
	// gate reads this against the subscription's active_process_limit before creating a
	// BRAND-NEW record (the MISS path of FindOrCreateCourtRecord only — a reobservation
	// of an existing record is never gated). It runs in the SAME tx as the pending
	// INSERT so the count is consistent with what is about to be created. lifecycle is
	// the schema's process-liveness flag; only ACTIVE records count against the ceiling.
	CountActiveCourtRecordsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	// The "X de Y" total for the Andamentos tab: how many docket entries the process
	// holds. Tenant-scoped through the same court_record join as the list.
	CountAndamentosByProcesso(ctx context.Context, arg CountAndamentosByProcessoParams) (int64, error)
	// The "Y" of the counter when the user filters ?lifecycle: how many records the tenant
	// holds in that lifecycle, so "X de Y" stays meaningful (X ⊆ that lifecycle). ACTIVE —
	// the screen's default context — keeps the cheaper CountActiveCourtRecordsByTenant.
	CountCourtRecordsByLifecycle(ctx context.Context, arg CountCourtRecordsByLifecycleParams) (int64, error)
	// Quantos prazos (deadline) o tenant derivou dentro da janela de uma captura
	// [started_at, finished_at] — a coluna "prazos" por linha da tabela. deadline.
	// created_at nasce em 0046. Escopado por tenant (barreira 1 + RLS).
	CountDeadlinesCreatedBetween(ctx context.Context, arg CountDeadlinesCreatedBetweenParams) (int64, error)
	// O KPI "prazos derivados hoje": deadline criados hoje (created_at >= hoje),
	// por tenant.
	CountDeadlinesCreatedToday(ctx context.Context, tenantID uuid.UUID) (int64, error)
	// O total de processos que a importação DESCOBRIU: SUM(sync_run.court_records_new) das
	// janelas do backfill_job. É a métrica de cobertura contra a qual o fecho por ETA compara
	// o contador de enriquecimentos aplicados (updated >= total → OK, senão PARTIAL).
	CountImportDiscoveredRecords(ctx context.Context, arg CountImportDiscoveredRecordsParams) (int64, error)
	// Bucket counts for the list envelope's `buckets` object, derived in the same
	// request as ListIntimacoes (no N+1). Mirrors the urgência buckets of the list's
	// WHERE clause but expressed as FILTER aggregates over the SAME non-urgência
	// filters (type, user_status, court, search — assignee is deliberately NOT
	// applied here, mirroring how the processes screen's other chips don't gate its
	// own filter options) — so the header badges agree with what the list would show
	// when the user picks that bucket. The seven buckets are mutually disjoint and
	// all exclude user_status RESOLVED/IGNORED. The four+ temporal buckets restrict
	// to status IN (PENDING, OPEN): MISSED/MET deadlines belong to closed intimations
	// and are not counted as actionable. `sem_data_definida` counts intimations with
	// no derived deadline (deadline LEFT JOIN miss). The buckets do NOT apply the
	// `nao_confirmado` triage toggle (it is a per-list filter, independent of tabs).
	CountIntimacoesBuckets(ctx context.Context, arg CountIntimacoesBucketsParams) (CountIntimacoesBucketsRow, error)
	// The "X de Y" total for the Intimações tab: how many intimations the process holds.
	// Scoped by the same court_record_id + tenant_id as the list; no court_record join is
	// needed (intimation carries tenant_id), unlike the andamentos count.
	CountIntimacoesByProcesso(ctx context.Context, arg CountIntimacoesByProcessoParams) (int64, error)
	// The filtered "X" of the intimations inbox's "X de Y" counter: how many intimations
	// match the active filters (search on the court record's cnj_number/class/judging_body,
	// type, user_status, court, urgencia, assignee). Called only when a filter is present;
	// the unfiltered "Y" reuses CountIntimationsByTenant. SAME predicates as ListIntimacoes
	// (minus the keyset). The LEFT JOIN deadline mirrors ListIntimacoes so the urgencia
	// filter agrees with the page.
	CountIntimacoesFiltered(ctx context.Context, arg CountIntimacoesFilteredParams) (int64, error)
	// The reconciliations totals: how many intimations the tenant holds (paired with
	// CountActiveCourtRecordsByTenant for the processes side).
	CountIntimationsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	// The filtered "X" of the processes screen's "X de Y" counter: how many court records
	// match the active filters (search on cnj_number ILIKE, court, degree, lifecycle, and
	// the case-level responsável). Called only when any filter is present; the unfiltered
	// "Y" is CountActiveCourtRecordsByTenant (or CountCourtRecordsByLifecycle when
	// ?lifecycle is set). The SAME predicates as ListProcessos (minus the keyset), so the
	// counter agrees with the page. The LEFT JOIN court_case is needed for the assignee
	// predicate; the case id is the join key, so it never multiplies rows.
	CountProcessosFiltered(ctx context.Context, arg CountProcessosFilteredParams) (int64, error)
	// How many court_records of an ENTIRE import (all tribunals of the backfill_job's tenant)
	// still need enriching. The batch job closes the import's ENRICHMENT capture row ONLY when
	// this reaches 0 — the deterministic fecho: not "updated >= total" (a process DATAJUD never
	// indexed never reaches 0.9), but "no untried record remains". Not-found processes stay
	// marked-attempted-but-<0.9, so they DROP OUT of this count without ever gralduating,
	// which is what stops an infinite loop and lets the fecho land as PARTIAL. Scoped by
	// tenant; the scan index serves the predicate. @backfill_job_id is unused in the filter
	// (the tenant's whole enrichment backlog is the import's, v0 runs one import at a time),
	// kept in the signature so the caller's intent (this import) reads clearly.
	CountRemainingDueForJob(ctx context.Context, tenantID uuid.UUID) (int64, error)
	// Quantas tarefas (task) foram criadas dentro da janela de uma captura
	// [started_at, finished_at]. task.created_at já existe. Escopado por tenant.
	CountTasksCreatedBetween(ctx context.Context, arg CountTasksCreatedBetweenParams) (int64, error)
	// O card "OABs" de uma captura: quantas OABs o tenant monitora pela integração
	// DJEN (a fonte que descobre). Junta watched_oab à integration da fonte DJEN.
	CountWatchedOABsForDJEN(ctx context.Context, tenantID uuid.UUID) (int64, error)
	// Drop a court_case orphaned when a concurrent sync won the court_record create
	// race (our InsertCourtRecord hit ON CONFLICT DO NOTHING) — keeps cases 1:1 with
	// records (v0 has no consolidation).
	DeleteCourtCase(ctx context.Context, id uuid.UUID) error
	// watched_oab queries (acquisition slice). The per-tenant index of watched OABs the
	// national match joins against. Populated from the integration_activated event: the
	// use case replaces an integration's set (delete + insert) so a scope change is
	// reflected. Writes run per-tenant (RLS by app.tenant_id); the match reads system-wide.
	// Clear an integration's watched OABs before re-populating, so a removed OAB stops
	// matching. Scoped to the integration (the tenant is implied by the RLS tx).
	DeleteWatchedOABsByIntegration(ctx context.Context, integrationID uuid.UUID) error
	// scheduler (re-poll) queries (acquisition slice).
	// The re-poll scheduler runs system-scoped (DoSystem sets app.system='on', so the
	// court_record RLS system escape hatch from migration 0016 exposes every tenant's
	// rows). Each tick it finds records whose next_sync_at is due, enqueues a fresh
	// court_record_observed for each (the enrichment consumer refreshes the DATAJUD
	// movimentos), and claims them by pushing next_sync_at forward so a later tick does
	// not re-enqueue the same record before the resync lands.
	// Records due for a DATAJUD re-poll: ACTIVE only (SUPERSEDED placeholders and
	// archived processes drop out) with a past next_sync_at. Served by the partial
	// index on next_sync_at WHERE lifecycle='ACTIVE'.
	DueCourtRecordsForResync(ctx context.Context, limit int32) ([]DueCourtRecordsForResyncRow, error)
	// Flip the job to its terminal status, but ONLY from RUNNING: the WHERE guard
	// makes this the single winning transition, so a late or over-count delivery that
	// reaches here cannot re-finalize. Scoped by tenant_id (isolation barrier 1).
	FinalizeBackfillJob(ctx context.Context, arg FinalizeBackfillJobParams) error
	// Resolve the sync_run opened by a given sync_requested event, inside the caller's
	// (tenant-scoped) tx. On a re-delivery of an already-marked event, the sync use
	// case reads this to decide: a RUNNING run means a prior attempt died before
	// closing it (so the cycle resumes it), while a closed (OK/FAILED) run is a no-op
	// ack. A miss (pgx.ErrNoRows) is the typed ErrSyncRunNotFound.
	FindSyncRunByEventID(ctx context.Context, eventID *string) (FindSyncRunByEventIDRow, error)
	// Uma linha capture_run do tenant (detalhe de DAILY_CAPTURE / ENRICHMENT). A carga
	// inicial (INITIAL_LOAD) continua no endpoint de reconciliation existente — este é
	// só para as duas capturas nativas. A linha ENRICHMENT deriva a janela da importação
	// (LEFT JOIN backfill_job), como no ListCaptureRuns. Um miss (pgx.ErrNoRows) vira o 404.
	GetCaptureRunByID(ctx context.Context, arg GetCaptureRunByIDParams) (GetCaptureRunByIDRow, error)
	// Os KPIs do topo da tela, escopados ao tenant. last_capture_at é a captura
	// bem-sucedida mais recente (OK/PARTIAL, com finished_at); intimations_new_today
	// soma as intimações novas das capturas iniciadas hoje (started_at >= hoje).
	GetCaptureSummary(ctx context.Context, tenantID uuid.UUID) (GetCaptureSummaryRow, error)
	// responsável do processo (case-level) — the write path for PUT
	// /v1/processos/:id/responsavel. All three run inside the caller's tx (UoW +
	// SET LOCAL app.tenant_id), so RLS is a second barrier under the explicit
	// tenant_id filters here. No outbox event yet — auditoria/evento is a future
	// slice (there is no consumer), so this is a bare projection write.
	// Resolve the court_case behind a court_record :id, tenant-scoped (barrier 1). The FE
	// addresses a process by its court_record id (the same id /processos returns), but the
	// responsável lives on court_case — so the write must hop record → case first. No row
	// (unknown id or a foreign tenant's record) → pgx.ErrNoRows, mapped to ErrProcessoNotFound
	// (→ 404) upstream, never nil,nil.
	GetCaseIDByCourtRecord(ctx context.Context, arg GetCaseIDByCourtRecordParams) (uuid.UUID, error)
	// Resolve a court record by its natural key inside the caller's tx. A miss
	// (pgx.ErrNoRows) is how FindOrCreateCourtRecord learns it must create one.
	GetCourtRecordByKey(ctx context.Context, arg GetCourtRecordByKeyParams) (GetCourtRecordByKeyRow, error)
	// Batch counterpart of GetCourtRecordByKey: resolve MANY records by their natural
	// keys in one round-trip, so a sync window partitions its whole result into existing
	// (reobservation → update) vs new (create) with ONE query instead of one GET per
	// record. Keys arrive as a jsonb array of {cnj_number, degree} — one scalar param,
	// so sqlc stays happy (it does not model multi-arg unnest).
	GetCourtRecordsByKeys(ctx context.Context, arg GetCourtRecordsByKeysParams) ([]GetCourtRecordsByKeysRow, error)
	// Lê os contadores da linha ENRICHMENT de uma importação: court_records_updated (quantos
	// processos foram enriquecidos) E errors (quantos hits o DATAJUD retornou mas não conseguimos
	// parsear — erro REAL). O fecho decide o status terminal SÓ por errors: 0 → OK ("Concluída"),
	// >0 → PARTIAL ("Falha parcial"); os não-encontrados no índice (0 hits) NÃO entram em errors,
	// então são normais e não rebaixam o status. Um miss (pgx.ErrNoRows) significa que a importação
	// não aplicou nenhum enriquecimento — o listener trata criando a linha honesta com updated=0.
	GetImportEnrichmentCounter(ctx context.Context, arg GetImportEnrichmentCounterParams) (GetImportEnrichmentCounterRow, error)
	GetIntegrationBySource(ctx context.Context, arg GetIntegrationBySourceParams) (Integration, error)
	// One intimation by id, for the FE deep-link into the inbox DETAIL screen (an intimation
	// not on the loaded list page). It is a SUPERSET of the list projection: it carries the
	// list fields (so it still maps a full IntimacaoView, including the prazo block) PLUS the
	// detail-only extras the inbox row omits —
	//   • content                — the FULL teor (not the 500-rune preview the list truncates);
	//   • judging_body           — the court record's órgão julgador (court_record.judging_body);
	//   • recipients             — the addressee jsonb list (every destinatário + matched-OAB flag);
	//   • user_status            — the triagem state (PENDING|RESOLVED|IGNORED);
	//   • assignee_user_id/name  — responsável pela intimação (nullable, LEFT JOIN app_user);
	//   • deadline.confirmed_at  — when the deadline was confirmed (for history derivation);
	//   • deadline.confirmed_by_name — confirmer's name (for history label; nullable);
	//   • deadline.status (already present) — for history label (OPEN/NO_DEADLINE branch).
	// The LEFT JOIN deadline mirrors ListIntimacoes (same 1:1 notification_id join); NULL
	// when the intimação has no prazo yet. Scoped by tenant_id (barrier 1): a foreign or
	// unknown id yields no row (→ typed 404 upstream, never nil,nil). Read-only, off the
	// write path.
	GetIntimacao(ctx context.Context, arg GetIntimacaoParams) (GetIntimacaoRow, error)
	// analise.sql — queries for the AI analysis of one intimation (POST /v1/intimacoes/:id/analise).
	// GetIntimacaoAnaliseContext reads the teor + the court context the prompt needs; the write
	// query OVERWRITES the three ai_* columns (re-executable — "Gerar novamente" re-runs it).
	// One intimation's teor plus its court record's identification and the derived prazo end_date
	// (LEFT JOIN deadline on notification_id — NULL when no prazo yet; the IA uses it as the ceiling
	// for suggested due_dates). Scoped by tenant_id + intimation id (barrier 1). A miss/foreign row →
	// pgx.ErrNoRows → ErrIntimationNotFound (the same 404 semantics as GetIntimacao). type is nullable.
	GetIntimacaoAnaliseContext(ctx context.Context, arg GetIntimacaoAnaliseContextParams) (GetIntimacaoAnaliseContextRow, error)
	// Reads the ai_providencias jsonb + ai_analyzed_at of one intimation, locking the row
	// (FOR UPDATE) so an aprovar/descartar read-modify-write is serialized. NULL ai_analyzed_at
	// (never analysed) vs a set stamp lets the use case reject a status change on an un-analysed
	// intimation. Scoped by tenant_id (barrier 1); a miss/foreign row → pgx.ErrNoRows.
	GetIntimationProvidenciasForUpdate(ctx context.Context, arg GetIntimationProvidenciasForUpdateParams) (GetIntimationProvidenciasForUpdateRow, error)
	// The tenant's most recent backfill job — status + tallies — for the import-status
	// read (the FE banner "importando seus processos…"). Newest job wins (a re-activation
	// opens a new job). No job ever → no row; the read use case maps that to NONE (not
	// importing). Scoped by tenant_id (isolation barrier 1; RLS is barrier 2).
	GetLatestBackfillStatus(ctx context.Context, tenantID uuid.UUID) (GetLatestBackfillStatusRow, error)
	// One process by id, for the FE deep-link into the processes detail (a process not on
	// the loaded list page). SAME projection as ListProcessos — the record's fields, its
	// last andamento via the LATERAL, and claim_value — so it maps to the same ProcessoView.
	// Scoped by id + tenant_id (barrier 1); NOT filtered by lifecycle, so a SUPERSEDED
	// placeholder is still reachable by direct link. A foreign or unknown id yields no row
	// (→ typed 404 upstream, never nil,nil). Read-only, off the write path.
	// next_deadline: same correlated LATERAL as ListProcessos (see above).
	GetProcesso(ctx context.Context, arg GetProcessoParams) (GetProcessoRow, error)
	// One import's reconciliação header (the detail screen), same shape/aggregation as
	// ListReconciliations but for a single backfill_job.
	GetReconciliation(ctx context.Context, arg GetReconciliationParams) (GetReconciliationRow, error)
	// The intimations with status = 'ACTIVE' (the DJEN cancellation lifecycle), each with
	// the days of its derived deadline (deadline.days, via the 1:1 notification_id link;
	// NULL when the intimação has no prazo yet). tenant-scoped.
	GetResumoActiveIntimations(ctx context.Context, arg GetResumoActiveIntimationsParams) ([]GetResumoActiveIntimationsRow, error)
	// resumo.sql — read-model queries for the AI process summary (GET /v1/processos/:id/resume).
	// The context is assembled by the repository from four narrow queries (one base row +
	// three :many reads) so sqlc types every column instead of a json_agg that would come
	// back as an opaque interface{}. The write query persists the AI summary best-effort
	// (WHERE ai_resume IS NULL makes it idempotent — a race between two first-opens is a
	// safe no-op on the loser).
	// One process's identification row plus the cached AI resume (if any). Scoped by
	// tenant_id + court_record_id (barrier 1). A miss/foreign row → pgx.ErrNoRows →
	// ErrProcessoNotFound (the same 404 semantics as GetProcesso).
	GetResumoContext(ctx context.Context, arg GetResumoContextParams) (GetResumoContextRow, error)
	// The last 10 docket entries for the process, newest first. Scoped by tenant through
	// the court_record join (docket_entry carries no tenant_id of its own).
	GetResumoMovements(ctx context.Context, arg GetResumoMovementsParams) ([]GetResumoMovementsRow, error)
	// The prazos that are not closed (OPEN or PENDING — a prazo born PENDING is a rule
	// suggestion awaiting F2 confirmation, still relevant to the summary). days_left is
	// computed as calendar days to end_date, mirroring the prazos screen read. tenant-scoped.
	GetResumoOpenDeadlines(ctx context.Context, arg GetResumoOpenDeadlinesParams) ([]GetResumoOpenDeadlinesRow, error)
	// Count one failed slice; same atomic lock-and-read-back contract as
	// IncrementBackfillSlicesOK. A job with any failed slice finalizes PARTIAL.
	IncrementBackfillSlicesError(ctx context.Context, arg IncrementBackfillSlicesErrorParams) (IncrementBackfillSlicesErrorRow, error)
	// Count one successful slice and read the job's tallies back atomically. The
	// UPDATE takes a row lock, so concurrent slice closes serialize and the counter
	// never loses a bump; the RETURNING lets the caller decide, in the same tx,
	// whether this was the last slice. Scoped by tenant_id (isolation barrier 1); a
	// non-matching row (wrong tenant / gone) affects zero rows and returns no row.
	IncrementBackfillSlicesOK(ctx context.Context, arg IncrementBackfillSlicesOKParams) (IncrementBackfillSlicesOKRow, error)
	// Incrementa a linha ENRICHMENT DA IMPORTAÇÃO por UM enriquecimento DATAJUD aplicado, na
	// MESMA tx do applyEnrichment (sob o advisory lock do tenant). A primeira aplicação da
	// importação cria a linha em status RUNNING ("Em andamento") com court_records_updated=1;
	// as seguintes somam +1 e avançam finished_at, MANTENDO RUNNING — o status terminal
	// (OK/PARTIAL) é carimbado só pelo fecho por ETA (CloseImportEnrichmentRun), quando a
	// fila de enriquecimento drenou e a cobertura é conhecida. window_from/to ficam NULL: a
	// linha deriva a janela do backfill_job (ver ListCaptureRuns). O índice parcial
	// capture_run_enrichment_import_uq (backfill_job_id WHERE kind='ENRICHMENT') é o alvo do
	// conflito — uma linha por importação. Só chega aqui passado o dedup do evento, então uma
	// re-entrega nunca conta em dobro.
	IncrementImportEnrichmentRun(ctx context.Context, arg IncrementImportEnrichmentRunParams) error
	// Batch counterpart of IncrementImportEnrichmentRun: bump an import's ENRICHMENT row by
	// @delta applied enrichments (records a step graded) AND @errs REAL parse errors (hits
	// DATAJUD returned but we could not parse — NOT the "not in the index" 0-hit case, which is
	// expected and never counted). The first step creates the row RUNNING; later steps sum both
	// counters and advance finished_at, staying RUNNING — the terminal status is stamped by the
	// fecho (CloseImportEnrichmentRun), which decides OK vs PARTIAL purely from the accumulated
	// `errors` (0 errors → OK even if some processes were not found in DATAJUD). Same partial-
	// unique conflict target as the +1 variant. The caller skips this when delta==0 AND errs==0
	// (a no-op upsert would mint a spurious RUNNING row).
	IncrementImportEnrichmentRunBy(ctx context.Context, arg IncrementImportEnrichmentRunByParams) error
	// Create the onboarding backfill job. total_slices is precomputed by the use
	// case; the counters default to zero and status is passed explicitly so a
	// zero-slice horizon can land COMPLETED instead of RUNNING.
	InsertBackfillJob(ctx context.Context, arg InsertBackfillJobParams) (uuid.UUID, error)
	// Create the lide a first-seen court record hangs on. v0 has no consolidation
	// yet, so every new record gets its own case; merging is a later slice.
	InsertCourtCase(ctx context.Context, tenantID uuid.UUID) (uuid.UUID, error)
	// Create a court record under a case. The natural key (tenant, cnj, degree) is
	// UNIQUE; ON CONFLICT DO NOTHING makes a concurrent double-create idempotent (two
	// backfill windows discovering the same process at once) — the loser gets no row
	// (pgx.ErrNoRows) and the caller re-resolves the winner instead of a 23505 rollback.
	// judging_body (órgão julgador) comes from the source when disclosed (DJEN
	// nomeOrgao / DATAJUD orgaoJulgador), NULL when it does not.
	InsertCourtRecord(ctx context.Context, arg InsertCourtRecordParams) (uuid.UUID, error)
	// Grava a linha DAILY_CAPTURE de um dia, na MESMA tx do write per-tenant do fan-out
	// (writeForTenant, sob o advisory lock do tenant). Abre e fecha de uma vez: o
	// fan-out é síncrono (upsert dos records + intimações), então started_at/finished_at
	// e o status final (OK) já são conhecidos. ON CONFLICT (tenant, source, kind,
	// window_from) faz um re-run do MESMO dia SOMAR aos contadores e avançar finished_at
	// — idempotência-friendly sob at-least-once (uma re-entrega do dia não zera o dia).
	InsertDailyCaptureRun(ctx context.Context, arg InsertDailyCaptureRunParams) error
	// Append one andamento, idempotent on (court_record_id, hash). On conflict the
	// row is left untouched and no id is returned (pgx.ErrNoRows), which the caller
	// reads as "deduped" — so a re-sync emits no docket_entry_observed for it.
	// tpu_code (Tabela Processual Unificada) and complements are DATAJUD movimento
	// classification; NULL for sources that do not classify the entry.
	InsertDocketEntry(ctx context.Context, arg InsertDocketEntryParams) (uuid.UUID, error)
	// Fecho por ETA quando a importação não aplicou NENHUM enriquecimento (CloseImportEnrichmentRun
	// afetou 0 linhas): cria a linha ENRICHMENT terminal de forma honesta (court_records_updated=0,
	// status carimbado pelo fecho). ON CONFLICT DO NOTHING protege contra a corrida de uma
	// aplicação que chegou entre o UPDATE e este INSERT (o índice parcial é o alvo).
	InsertEmptyImportEnrichmentRun(ctx context.Context, arg InsertEmptyImportEnrichmentRunParams) error
	// Append or reconcile one intimação, keyed on (tenant_id, case_id, hash). Unlike
	// docket entries, this is ON CONFLICT DO UPDATE (not DO NOTHING): when the DJEN
	// retracts a publication (data_cancelamento) the SAME hash re-arrives carrying
	// status=CANCELLED + cancelled_at/cancel_reason, and the existing row MUST be
	// updated so the deadline slice revokes the derived prazo — a DO NOTHING would
	// leave a phantom deadline. type/source_url are refreshed alongside. recipients is
	// written on insert and left untouched on update (the matched-OAB flag is stable
	// per hash). (xmax = 0) tells the caller whether THIS upsert inserted a fresh row
	// (true) or updated an existing one (false), so it can still tally new vs. deduped.
	InsertIntimation(ctx context.Context, arg InsertIntimationParams) (InsertIntimationRow, error)
	// publication store queries (acquisition slice). The national DJEN firehose: the
	// ingestion sweeps the diário by tribunal/day and lands every communication here,
	// to be matched to tenants' watched OABs locally. No tenant scope (national reference
	// data, like holiday), so no RLS and no tenant filter.
	// Land one national communication, idempotent on the DJEN hash (globally unique per
	// communication). The daily lookback re-fetches recent days, so ON CONFLICT (hash)
	// DO NOTHING makes a re-ingest a no-op: the loser gets no row (pgx.ErrNoRows), which
	// the caller reads as "already ingested" to tally new vs. deduped. recipient_oabs is
	// the normalized "NUMBER|UF" key set for the local OAB match; payload is the raw item.
	InsertPublication(ctx context.Context, arg InsertPublicationParams) (uuid.UUID, error)
	// sync cycle queries (acquisition slice).
	// The sync listener reacts to sync_requested: it opens a sync_run (RUNNING),
	// fetches+parses a window, then upserts the observed records/entries/intimations
	// and closes the run (OK/FAILED) — all keyed off the court_record's natural key
	// (tenant_id, cnj_number, degree). Idempotency lives in the schema: docket_entry
	// and intimation carry UNIQUE constraints, so a re-sync of the same window
	// inserts nothing new (ON CONFLICT DO NOTHING) and the RETURNING clause tells the
	// caller which rows were actually new.
	// Open a sync run. court_record_id is left NULL (OAB window discovery is not yet
	// tied to one record); finished_at/error stay NULL until the run closes. event_id
	// records the sync_requested event that opened it, so a re-delivery can find and
	// resume a run that never closed (FindSyncRunByEventID). window_from/to stamp the
	// slice's date window so the reconciliations read can show it (NULL when absent).
	InsertSyncRun(ctx context.Context, arg InsertSyncRunParams) (uuid.UUID, error)
	// Add one watched OAB for an integration, idempotent on (integration_id, oab_key):
	// a re-activation with the same scope is a no-op. oab_key is the normalized "NUMBER|UF".
	InsertWatchedOAB(ctx context.Context, arg InsertWatchedOABParams) error
	// The tenant's ACTIVE firm members (internal app_user id + name) — the assignable responsáveis
	// the analyze_intimation prompt lists so the IA suggests a real assignee. Same join as identity's
	// ListOrgMembers (membership status ACTIVE), projected to just id+name; ordered by name for a
	// stable prompt. Scoped by tenant_id (barrier 1). Reused only for the AI analysis context.
	ListActiveMembers(ctx context.Context, tenantID uuid.UUID) ([]ListActiveMembersRow, error)
	// The "Andamentos" tab of one process: the court record's docket entries, newest
	// first. Scoped by tenant via the court_record join (docket_entry has no tenant_id
	// of its own) so a foreign court_record.id passed as :id yields nothing. Descending
	// keyset on (occurred_at, id) — served by docket_entry(court_record_id, occurred_at)
	// — the first page passes the max sentinel ('9999-12-31T23:59:59Z', max-uuid).
	ListAndamentosByProcesso(ctx context.Context, arg ListAndamentosByProcessoParams) ([]ListAndamentosByProcessoRow, error)
	// Tela "Capturas" (acquisition slice). Trilha de auditoria unificada dos três
	// fluxos de captura, por-tenant:
	//   • DAILY_CAPTURE — o fan-out diário do firehose nacional (capture_run, kind);
	//   • ENRICHMENT    — o enriquecimento DATAJUD do dia (capture_run, kind);
	//   • INITIAL_LOAD  — a carga inicial de onboarding (backfill_job agregando sync_run).
	// capture_run é escrito na MESMA tx dos writes que já existem (writeForTenant /
	// applyEnrichment); backfill_job/sync_run continuam do fluxo de reconciliação. A
	// lista faz UNION ALL das duas fontes; o read model deriva o rótulo/DisplayStatus.
	// As capturas do tenant, mais recentes primeiro. UNION ALL de capture_run (DAILY_
	// CAPTURE, 1 linha por dia; ENRICHMENT, 1 linha por importação) com backfill_job
	// (INITIAL_LOAD, uma linha por importação agregando as janelas sync_run). Os tallies do
	// INITIAL_LOAD somam as colunas dedicadas das janelas (court_records_new/intimations_new/
	// court_records_updated) e os errors vêm de slices_error. A linha ENRICHMENT não tem
	// janela própria (window_from/to NULL): ela DERIVA a janela da importação via LEFT JOIN
	// backfill_job por capture_run.backfill_job_id (COALESCE cai na coluna própria da linha
	// quando não há import — DAILY_CAPTURE). window/started/finished normalizados para o
	// mesmo shape das duas fontes. Bounded por $2 (sem paginação v0).
	ListCaptureRuns(ctx context.Context, arg ListCaptureRunsParams) ([]ListCaptureRunsRow, error)
	// All of a tenant's integrations, oldest first. tenant_id filter is isolation
	// barrier 1 (the app layer); RLS is barrier 2.
	ListIntegrations(ctx context.Context, tenantID uuid.UUID) ([]Integration, error)
	// Selectable ?court values for the intimações inbox: the distinct courts of the
	// tenant's intimated court records, ordered by name (case-insensitive).
	ListIntimacaoCourts(ctx context.Context, tenantID uuid.UUID) ([]string, error)
	// The intimações inbox: the tenant's intimations, newest availability first, with
	// the court record's number/court/degree joined in. Descending keyset on
	// (made_available_at, id); the first page passes the max sentinel
	// ('9999-12-31', max-uuid). Optional filters — @court (free text from the DISTINCT
	// options), @type / @user_status (closed sets), @urgencia (deadline-proximity /
	// providência bucket, closed set), @search (cnj_number/class/judging_body ILIKE),
	// @assignee_id (the "Minhas" toggle) — are additive ANDs. The LEFT JOIN deadline
	// exposes the derived prazo (1:1 per notification_id, UNIQUE); NULL when no prazo
	// exists yet. ai_analyzed_at + assignee_user_id/name mirror GetIntimacao's
	// projection (same LEFT JOIN app_user pattern) so the inbox row can render the
	// "não analisada" badge and the responsável label without a deep-link.
	ListIntimacoes(ctx context.Context, arg ListIntimacoesParams) ([]ListIntimacoesRow, error)
	// The "Intimações" tab of one process: the intimations filed on this court record,
	// newest availability first, with the record's number/court/degree joined in (same
	// projection as ListIntimacoes). Scoped by both court_record_id (the :id) and
	// tenant_id (barrier 1) — intimation has its own tenant_id, so a foreign :id (another
	// tenant's record) matches nothing. Descending keyset on (made_available_at, id) —
	// served by intimation(court_record_id, made_available_at DESC) — the first page
	// passes the max sentinel ('9999-12-31', max-uuid).
	ListIntimacoesByProcesso(ctx context.Context, arg ListIntimacoesByProcessoParams) ([]ListIntimacoesByProcessoRow, error)
	// The intimations a window first discovered (collapse), newest availability first.
	ListIntimacoesBySyncRun(ctx context.Context, arg ListIntimacoesBySyncRunParams) ([]ListIntimacoesBySyncRunRow, error)
	// The /processos/:id/partes deep-read: every party of the process behind a court_record
	// :id, with its advogados aggregated as a jsonb array (name/oab/uf), in one round-trip.
	// Isolation: court_record → court_case resolves the case, scoped by tenant_id (barrier 1);
	// a foreign or unknown :id resolves to no case and yields no rows. Ordered by role then
	// name so the caller buckets autor/réu/terceiro deterministically. counsels defaults to
	// an empty jsonb array (never NULL) when a party has no advogado.
	ListPartiesByProcesso(ctx context.Context, arg ListPartiesByProcessoParams) ([]ListPartiesByProcessoRow, error)
	// Selectable ?assignee values for the processes screen: the responsáveis of the
	// tenant's live processes, joined at case level (court_record → court_case →
	// app_user) exactly like the list's projection, deduped by id, ordered by name
	// (case-insensitive). The list filters on cc.assigned_user_id, so an unassigned case
	// yields no option.
	ListProcessoAssignees(ctx context.Context, tenantID uuid.UUID) ([]ListProcessoAssigneesRow, error)
	// ── filter options (the envelope's selectable sets) ──────────────────────────
	// Distinct-value reads that back the list envelopes' filter chips. Each is
	// tenant-scoped (barrier 1) and matches the list's OWN context predicate (the
	// processos options restrict to the default ACTIVE lifecycle), so the options
	// reflect what the list can actually show. Empty values are skipped in Go (a blank
	// chip is never selectable).
	// Selectable ?court values for the processes screen: the distinct courts of the
	// tenant's live (ACTIVE) records, ordered by name (case-insensitive). The DISTINCT
	// lives in the inner query — a bare SELECT DISTINCT with ORDER BY on an expression not
	// in the select list is rejected by Postgres — and the outer layer orders.
	ListProcessoCourts(ctx context.Context, tenantID uuid.UUID) ([]string, error)
	// Selectable ?degree values for the processes screen: the distinct degrees of the
	// tenant's live (ACTIVE) records, ordered by name (case-insensitive).
	ListProcessoDegrees(ctx context.Context, tenantID uuid.UUID) ([]string, error)
	// read-model queries (acquisition slice) — the screen reads, kept OFF the write
	// path (docs: "leitura de tela usa read model, DTO por query dedicada"). Each is
	// tenant-scoped (barrier 1) and keyset-paginated on a stable (sort_key, id) pair
	// so paging is offset-free and stable under concurrent inserts. The caller passes
	// a sentinel cursor for the first page, so there is no conditional WHERE.
	// The consolidated processes screen: the tenant's live court records (SUPERSEDED
	// placeholders drop out), each with its most recent andamento for the "last
	// movement" column. Ordered by cnj_number then id (ascending keyset): the first
	// page passes ('', zero-uuid). Optional filters — @court / @degree (free text from
	// the DISTINCT options), @lifecycle (a closed set; '' keeps the default ACTIVE
	// context), @assignee_id (NULL = any; the case-level responsável) — are additive
	// ANDs, so an absent filter matches everything.
	// next_deadline: the nearest OPEN/PENDING prazo of the process, derived via a
	// correlated LATERAL (LIMIT 1 — one row per process, keyset stays N rows = N
	// processes). The path is court_record → intimation → deadline (notification_id
	// is the historic FK name for intimation_id). NULL when no OPEN/PENDING prazo exists.
	// CASE WHEN d.id IS NOT NULL guards all nullable deadline expressions (mirrors the
	// ListIntimacoes pattern in this file) so sqlc infers nullable types correctly.
	ListProcessos(ctx context.Context, arg ListProcessosParams) ([]ListProcessosRow, error)
	// The court records a window first discovered (collapse). Scoped by tenant (RLS +
	// filter) and the discovering sync_run_id; bounded defensively.
	ListProcessosBySyncRun(ctx context.Context, arg ListProcessosBySyncRunParams) ([]ListProcessosBySyncRunRow, error)
	// The reconciliations screen: one "reconciliação" per import (backfill_job), with
	// the processes/intimations its windows discovered summed up, the job's overall
	// date window (the janela de prazo geral) and slice tallies. finished_at is the
	// last window close once the job is no longer RUNNING (NULL while running).
	ListReconciliations(ctx context.Context, arg ListReconciliationsParams) ([]ListReconciliationsRow, error)
	// The windows (sync_runs) of one import, chronological, with the failure reason
	// lifted out of the error jsonb. Drives the detail screen's per-window table and
	// the collapse (each row's id feeds ListProcessos/IntimacoesBySyncRun).
	ListSyncRunsByJob(ctx context.Context, arg ListSyncRunsByJobParams) ([]ListSyncRunsByJobRow, error)
	// Termos monitorados com nome derivado: as OABs monitoradas pelo tenant via DJEN,
	// cada uma com o nome mais frequente encontrado em party_counsel (mode() within group).
	// oab_key é "NUMBER|UF"; devolvemos "UFNUMBER" (canônico do FE) via uf||split_part.
	// O LEFT JOIN garante que OABs novas (sem captura ainda) casam zero linhas de
	// party_counsel; mode() sobre um grupo todo NULL também devolve NULL — o COALESCE
	// pra '' evita isso (sqlc infere a coluna como NOT NULL pelo ::text, e o scan do pgx
	// falha contra um NULL de verdade; repository.go já trata "" como "sem nome").
	// Ordenado por oab_key para estabilidade (sem offset, lista pequena).
	ListWatchedOABsWithName(ctx context.Context, tenantID uuid.UUID) ([]ListWatchedOABsWithNameRow, error)
	// Record that a sync touched this court record: refresh its completeness and
	// schedule the next sweep (next_sync_at drives the scheduler slice later).
	// judging_body is COALESCEd, not overwritten: a sync that does not disclose the
	// órgão julgador (NULL) keeps the value a prior sync learned — DATAJUD reveals it
	// after a DJEN discovery landed the record without it (placeholder+merge).
	MarkCourtRecordSynced(ctx context.Context, arg MarkCourtRecordSyncedParams) error
	// Stamp enrichment_attempted_at = @at on EVERY record a batch visited — graded OR not
	// (a number DATAJUD did not return still counts as attempted). This is what removes the
	// record from the scan index so the next step reads fresh work and the fecho can reach
	// 0-remaining. Scoped by tenant (RLS barrier 1). Ids arrive as a uuid[] so one round-trip
	// marks the whole batch.
	MarkEnrichmentAttempted(ctx context.Context, arg MarkEnrichmentAttemptedParams) error
	// match queries (acquisition slice). The join that turns the national publication
	// firehose into per-tenant work: a watched_oab key ∈ a publication's recipient_oabs.
	// Read system-wide (uow.DoSystem sets app.system='on' so the watched_oab RLS opens
	// across tenants); publication is national and unscoped.
	// Every (tenant, matched OAB, publication payload) for the communications made
	// available on a day. One publication watched by two OABs of the same tenant yields
	// two rows; the match use case groups by tenant and dedups the payloads. payload is
	// the raw DJEN item, re-parsed per matched tenant to create its court_record/intimação.
	MatchPublicationsByDay(ctx context.Context, madeAvailableAt pgtype.Date) ([]MatchPublicationsByDayRow, error)
	// One tenant's matches from a date forward — the onboarding history catch-up: a new
	// integration's watched OABs are matched against the publications ALREADY stored (the
	// 90-day bootstrap window), so the client sees its recent intimações immediately, with
	// ZERO per-OAB DJEN calls. The forward daily match (MatchPublicationsByDay) covers
	// everything from tomorrow on.
	MatchPublicationsForTenantSince(ctx context.Context, arg MatchPublicationsForTenantSinceParams) ([]MatchPublicationsForTenantSinceRow, error)
	// Merge-path only: move the placeholder's intimations onto a PRE-EXISTING graded
	// record when grading in place would violate the (tenant, cnj, degree) UNIQUE.
	// Unicidade de intimation é (tenant, case_id, hash), so swapping court_record_id never
	// breaks dedup (same case). Returns the number of rows moved.
	RepointIntimations(ctx context.Context, arg RepointIntimationsParams) (int64, error)
	// The batch enrichment's scan: up to @lim court_records of ONE tribunal (@court) that
	// still need enriching — completeness below the DATAJUD ceiling (0.9), never attempted,
	// and not a superseded merge-placeholder. Served by court_record_enrichment_scan_idx
	// (tenant_id, court WHERE the same predicate). ORDER BY id is a STABLE deterministic
	// order (court_record has no created_at column; v0 priority is just "make progress",
	// not recency) so re-runs page the same way; enrichment_attempted_at IS NULL is what
	// makes the scan shrink each step, so a re-delivery re-reads the REMAINING work only.
	SelectDueForEnrichment(ctx context.Context, arg SelectDueForEnrichmentParams) ([]SelectDueForEnrichmentRow, error)
	// Best-effort persist of the AI-generated resume. The WHERE ai_resume IS NULL makes
	// the write idempotent at the DB layer — a race between two first-opens updates 0
	// rows on the loser, which is NOT an error (write-once by design).
	SetCourtRecordAIResume(ctx context.Context, arg SetCourtRecordAIResumeParams) error
	// Persists (OVERWRITES) the AI analysis of one intimation. Unlike SetCourtRecordAIResume
	// there is NO write-once guard — the analysis is re-executable ("Gerar novamente"). Scoped
	// by tenant_id (barrier 1). Degraded mode passes ai_summary='' + ai_providencias='[]'.
	SetIntimationAIAnalysis(ctx context.Context, arg SetIntimationAIAnalysisParams) error
	// Overwrites ONLY the ai_providencias jsonb (leaves ai_summary / ai_analyzed_at untouched) —
	// the write half of the aprovar/descartar status flip. Scoped by tenant_id (barrier 1).
	SetIntimationProvidencias(ctx context.Context, arg SetIntimationProvidenciasParams) error
	// triagem da intimação — the write path for POST /v1/intimacoes/:id/{resolve,
	// ignore,reopen}. The user drives the intimation's workflow state (user_status,
	// 0030), SEPARATE from the DJEN cancellation `status`. Runs inside the caller's tx
	// (UoW + SET LOCAL app.tenant_id), so RLS is a second barrier under the explicit
	// tenant_id filter. No outbox event yet — there is no consumer of a triagem fact —
	// so this is a bare projection write (a future slice can emit in this same tx).
	// Set the intimation's triagem state (user_status) to $3, tenant-scoped (barrier 1,
	// RLS barrier 2). The three actions map to the three target states: resolve→RESOLVED,
	// ignore→IGNORED, reopen→PENDING. Only user_status is touched — the DJEN `status`
	// (ACTIVE/CANCELLED) is left alone. A zero-row result (unknown id or a foreign tenant's
	// row) surfaces as pgx.ErrNoRows → ErrIntimationNotFound (→ 404), never nil,nil.
	// Idempotent: re-resolving an already-RESOLVED row rewrites the same value.
	SetIntimationUserStatus(ctx context.Context, arg SetIntimationUserStatusParams) (uuid.UUID, error)
	// The KPI counts for the intimações inbox header (GET /v1/intimacoes/summary), one
	// aggregate scan over the tenant's intimations. The LEFT JOIN deadline (1:1 per
	// notification_id) enables the urgência buckets without a second scan.
	//   pendentes      = triagem PENDING (awaiting user decision)
	//   em_atraso      = prazo vencido (days_left < 0) AND status IN (PENDING, OPEN)
	//   vencem_hoje    = prazo vence hoje (days_left = 0) AND status IN (PENDING, OPEN)
	//   nao_confirmado = prazo sugerido ainda não confirmado (status = 'PENDING')
	// `em_analise` (AI-in-progress) has no source yet — kept at 0 so the FE contract is
	// stable. `criticas` is retired (replaced by em_atraso/vencem_hoje/nao_confirmado),
	// kept at 0 for backward-compat. tenant-scoped (barrier 1, RLS barrier 2).
	SummarizeIntimacoes(ctx context.Context, tenantID uuid.UUID) (SummarizeIntimacoesRow, error)
	// The KPI counts for the processes list header (GET /v1/processos/summary), one
	// aggregate scan over the tenant's court_records grouped into the FE's buckets by
	// court_record.lifecycle (ACTIVE|SUSPENDED|ARCHIVED|SUPERSEDED). SUPERSEDED is the
	// internal UNKNOWN placeholder left after a DATAJUD grade re-point (not a user-facing
	// process), so it is EXCLUDED from every bucket and from `total` — the screen counts
	// only real processes. `baixados` has NO lifecycle source in the v0 schema (there is no
	// BAIXADO value; a baixa would surface as ARCHIVED), so it is always 0 until the schema
	// models it — kept in the projection so the FE contract is stable. tenant-scoped
	// (barrier 1, RLS barrier 2).
	SummarizeProcessos(ctx context.Context, tenantID uuid.UUID) (SummarizeProcessosRow, error)
	// Merge-path only: retire the UNKNOWN placeholder after its intimations moved onto the
	// pre-existing graded record. It no longer represents a live process (the graded record
	// does), so it drops out of the ACTIVE count and the scheduler (next_sync_at NULL).
	SupersedeCourtRecord(ctx context.Context, arg SupersedeCourtRecordParams) error
	// enrichment cycle queries (acquisition slice).
	// DATAJUD enrichment reacts to court_record_observed for a DJEN placeholder
	// (degree=UNKNOWN): it fetches the process by number, reveals the grau, and GRADES
	// THE PLACEHOLDER IN PLACE — a single UPDATE that mutates the existing court_record
	// (ev.CourtRecordID) to the real degree + DATAJUD-authoritative fields on the SAME
	// id (UpdateCourtRecordGrade). Because the id never changes, the intimations,
	// deadlines and docket entries already anchored to it stay correct — no orphan, no
	// duplicate (FIX B). The (tenant, cnj, degree) UNIQUE means the ONE case that cannot
	// graduate in place is a rare pre-existing graded record at that grade: the use case
	// detects it first (GetCourtRecordByKey, sync.sql) and MERGES the placeholder into it
	// instead — RepointIntimations moves the placeholder's intimations onto the graded
	// record and SupersedeCourtRecord retires the placeholder (DJEN discovery produces no
	// docket entries, so the placeholder never has any to re-point).
	// Grade a court_record IN PLACE: mutate the row named by @court_record_id — the DJEN
	// UNKNOWN placeholder — to the DATAJUD-revealed degree and the fields DATAJUD is
	// authoritative for, keeping the SAME id. Because the id is stable, every child
	// already anchored to it (intimation, deadline, docket_entry) remains correct, which
	// is the whole point of FIX B. It also serves the scheduler re-poll of an
	// already-graded record: the degree is unchanged there (the caller guards the
	// grade-mismatch case), so this just refreshes the authoritative fields. next_sync_at
	// is seeded only when the row still has none (first grade); an existing schedule — the
	// scheduler's own claim — is preserved via COALESCE, so the scheduler keeps owning the
	// re-poll cadence. case_id is never touched (the record keeps its Pasta). RETURNING
	// carries id + case_id for the caller. The (tenant, cnj, degree) UNIQUE requires the
	// caller to ensure no OTHER record already holds @degree (the merge path handles that).
	// lifecycle is derived from DATAJUD movimentos (lifecycleFromMovimentos in the parser):
	// CASE guards that an already-SUPERSEDED row is never downgraded — superseding is a
	// structural merge operation and must survive a scheduler re-poll. When @lifecycle is
	// empty (source does not carry movimentos) the existing lifecycle is preserved via the
	// NULLIF/COALESCE: NULLIF('', lifecycle) = NULL → COALESCE falls back to lifecycle.
	UpdateCourtRecordGrade(ctx context.Context, arg UpdateCourtRecordGradeParams) (UpdateCourtRecordGradeRow, error)
	// Close a sync run, but ONLY from RUNNING: the status guard makes this the single
	// winning transition (compare-and-swap), so a redelivery that resumes a run
	// another execution already closed affects zero rows. OK carries the item tallies
	// and a NULL error; FAILED carries the error jsonb and zero tallies. finished_at
	// is set by the caller's clock. RETURNING id lets the caller learn whether this
	// close won (a row) or lost the race (pgx.ErrNoRows) — the signal to publish the
	// terminal event exactly once. Mirrors FinalizeBackfillJob's RUNNING-only guard.
	UpdateSyncRun(ctx context.Context, arg UpdateSyncRunParams) (uuid.UUID, error)
	// acquisition slice queries (integration).
	// The upsert is keyed by (tenant_id, source) so re-activating a source is
	// idempotent at the row level; credential_ref is never written from here (it
	// stays NULL in v0) and is preserved across updates.
	// Activate (or re-activate) a tenant's subscription to a data source. On
	// conflict only scope/status/updated_at change — credential_ref is left intact.
	UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) (Integration, error)
}

var _ Querier = (*Queries)(nil)
