// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package acquisitiondb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Serialize the acquisition domain's WRITES per tenant. The sync and enrichment
	// write transactions take this transaction-scoped advisory lock as their FIRST
	// statement, so two concurrent slices never hold overlapping row/index locks on
	// court_record and thus never deadlock (40P01) — while their slow DJEN/DATAJUD
	// fetches (which run OUTSIDE the tx) still overlap freely. Postgres releases the
	// lock automatically at commit/rollback. The key is hashed from the tenant, so
	// different tenants never block each other; hashtext is int4, widened to the int8
	// pg_advisory_xact_lock expects.
	AcquireTenantWriteLock(ctx context.Context, tenantID string) error
	// backfill_job queries (acquisition slice).
	// The backfill listener reacts to integration_activated: on the FIRST activation
	// of an integration it creates one backfill_job and emits the sync slices. These
	// two queries are the job's first-activation guard (exists) and its insert; the
	// counters/completion (slices_ok, slices_error, final status) belong to the sync
	// slice, not here.
	// True when a backfill_job already exists for this integration (any status). The
	// listener uses it as the first-activation guard: a re-activation must not
	// re-dispatch a backfill.
	BackfillJobExistsByIntegration(ctx context.Context, integrationID uuid.UUID) (bool, error)
	// Create N fresh lides in one round-trip (v0: one case per new record). Returns the
	// N new ids; the caller pairs each with a new court_record.
	BatchInsertCourtCases(ctx context.Context, arg BatchInsertCourtCasesParams) ([]uuid.UUID, error)
	// Bulk create of first-seen records from a jsonb array of rows: folds the post-sync
	// fields (completeness/judging_body/next_sync_at) straight into the INSERT, so a NEW
	// record needs no separate MarkCourtRecordSynced. JSON null → SQL NULL naturally
	// (nullable class/subject/judging_body/sync_run_id). ON CONFLICT DO NOTHING keeps it
	// idempotent (a re-run of the window no-ops on rows it already created); RETURNING the
	// natural key lets the caller map ids back to input order. Under the per-tenant
	// advisory lock there is no concurrent same-tenant writer, so the conflict path only
	// fires on a genuine re-run, never a create race.
	BatchInsertCourtRecords(ctx context.Context, arg BatchInsertCourtRecordsParams) ([]BatchInsertCourtRecordsRow, error)
	// Bulk counterpart of InsertDocketEntry: insert MANY andamentos in ONE round-trip from
	// a jsonb array of rows, ON CONFLICT (court_record_id, hash) DO NOTHING (idempotent).
	// Only the rows that were ACTUALLY new are returned (DO NOTHING omits conflicts), so the
	// caller maps them back to build the observed events. This is what keeps the enrichment's
	// per-tenant write lock hold short even for a process with a long movimento history.
	BatchInsertDocketEntries(ctx context.Context, entries []byte) ([]BatchInsertDocketEntriesRow, error)
	// Bulk MarkCourtRecordSynced for reobserved (already-existing) records: refresh
	// completeness/next_sync_at and COALESCE judging_body (a sync that omits it keeps the
	// prior value) for MANY records in one round-trip, from a jsonb array of rows.
	BatchMarkCourtRecordsSynced(ctx context.Context, updates []byte) error
	// Bulk counterpart of InsertIntimation: upsert MANY intimações in one round-trip from
	// a jsonb array of rows. Same ON CONFLICT (tenant, case, hash) DO UPDATE as the single
	// version (a retracted publication re-arrives with the same hash carrying CANCELLED).
	// JSON handles it all: null → NULL (nullable dates/type/source_url), and recipients
	// (text[]) maps from a JSON array.
	//
	// The RETURNING is enriched so the producer can emit the right domain event per row,
	// in the SAME tx, without the deadline slice reading anything back:
	//   • inserted  ((xmax = 0)) — a FIRST insert → intimation.observed;
	//   • old_status — the status BEFORE this upsert, read by a correlated subquery on
	//     `intimation`. A data-modifying CTE and the main query share one snapshot, so
	//     the subquery cannot see `upserted`'s effect and returns the PRE-upsert row (a
	//     fresh insert has no prior row → NULL → ''). old_status <> 'CANCELLED' + new
	//     status = 'CANCELLED' on an UPDATE is the ACTIVE → CANCELLED transition →
	//     intimation.cancelled.
	//   • court — denormalized from the row's court_record (a join), so the producer
	//     derives uf via ufFromTribunal at emission.
	BatchUpsertIntimations(ctx context.Context, arg BatchUpsertIntimationsParams) ([]BatchUpsertIntimationsRow, error)
	// Push a record's next_sync_at forward as its re-poll is enqueued, so the next tick
	// does not re-enqueue it; if the resync never lands, it falls due again after the
	// interval (at-least-once).
	ClaimCourtRecordResync(ctx context.Context, arg ClaimCourtRecordResyncParams) error
	// Count the tenant's ACTIVE court records inside the caller's tx. The entitlement
	// gate reads this against the subscription's active_process_limit before creating a
	// BRAND-NEW record (the MISS path of FindOrCreateCourtRecord only — a reobservation
	// of an existing record is never gated). It runs in the SAME tx as the pending
	// INSERT so the count is consistent with what is about to be created. lifecycle is
	// the schema's process-liveness flag; only ACTIVE records count against the ceiling.
	CountActiveCourtRecordsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	// The "X de Y" total for the Andamentos tab: how many docket entries the process
	// holds. Tenant-scoped through the same court_record join as the list.
	CountAndamentosByProcesso(ctx context.Context, arg CountAndamentosByProcessoParams) (int64, error)
	// The "X de Y" total for the Intimações tab: how many intimations the process holds.
	// Scoped by the same court_record_id + tenant_id as the list; no court_record join is
	// needed (intimation carries tenant_id), unlike the andamentos count.
	CountIntimacoesByProcesso(ctx context.Context, arg CountIntimacoesByProcessoParams) (int64, error)
	// The filtered "X" of the intimations inbox's "X de Y" counter: how many intimations
	// whose court record's cnj_number matches the search term. Called only when ?search
	// is present; the unfiltered "Y" reuses CountIntimationsByTenant.
	CountIntimacoesMatchingSearch(ctx context.Context, arg CountIntimacoesMatchingSearchParams) (int64, error)
	// The reconciliations totals: how many intimations the tenant holds (paired with
	// CountActiveCourtRecordsByTenant for the processes side).
	CountIntimationsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	// The filtered "X" of the processes screen's "X de Y" counter: how many ACTIVE court
	// records match the search term (cnj_number ILIKE, trigram-indexed). Called only when
	// ?search is present; the unfiltered "Y" reuses CountActiveCourtRecordsByTenant.
	CountProcessosMatchingSearch(ctx context.Context, arg CountProcessosMatchingSearchParams) (int64, error)
	// Drop a court_case orphaned when a concurrent sync won the court_record create
	// race (our InsertCourtRecord hit ON CONFLICT DO NOTHING) — keeps cases 1:1 with
	// records (v0 has no consolidation).
	DeleteCourtCase(ctx context.Context, id uuid.UUID) error
	// watched_oab queries (acquisition slice). The per-tenant index of watched OABs the
	// national match joins against. Populated from the integration_activated event: the
	// use case replaces an integration's set (delete + insert) so a scope change is
	// reflected. Writes run per-tenant (RLS by app.tenant_id); the match reads system-wide.
	// Clear an integration's watched OABs before re-populating, so a removed OAB stops
	// matching. Scoped to the integration (the tenant is implied by the RLS tx).
	DeleteWatchedOABsByIntegration(ctx context.Context, integrationID uuid.UUID) error
	// scheduler (re-poll) queries (acquisition slice).
	// The re-poll scheduler runs system-scoped (DoSystem sets app.system='on', so the
	// court_record RLS system escape hatch from migration 0016 exposes every tenant's
	// rows). Each tick it finds records whose next_sync_at is due, enqueues a fresh
	// court_record_observed for each (the enrichment consumer refreshes the DATAJUD
	// movimentos), and claims them by pushing next_sync_at forward so a later tick does
	// not re-enqueue the same record before the resync lands.
	// Records due for a DATAJUD re-poll: ACTIVE only (SUPERSEDED placeholders and
	// archived processes drop out) with a past next_sync_at. Served by the partial
	// index on next_sync_at WHERE lifecycle='ACTIVE'.
	DueCourtRecordsForResync(ctx context.Context, limit int32) ([]DueCourtRecordsForResyncRow, error)
	// Flip the job to its terminal status, but ONLY from RUNNING: the WHERE guard
	// makes this the single winning transition, so a late or over-count delivery that
	// reaches here cannot re-finalize. Scoped by tenant_id (isolation barrier 1).
	FinalizeBackfillJob(ctx context.Context, arg FinalizeBackfillJobParams) error
	// Resolve the sync_run opened by a given sync_requested event, inside the caller's
	// (tenant-scoped) tx. On a re-delivery of an already-marked event, the sync use
	// case reads this to decide: a RUNNING run means a prior attempt died before
	// closing it (so the cycle resumes it), while a closed (OK/FAILED) run is a no-op
	// ack. A miss (pgx.ErrNoRows) is the typed ErrSyncRunNotFound.
	FindSyncRunByEventID(ctx context.Context, eventID *string) (FindSyncRunByEventIDRow, error)
	// Resolve a court record by its natural key inside the caller's tx. A miss
	// (pgx.ErrNoRows) is how FindOrCreateCourtRecord learns it must create one.
	GetCourtRecordByKey(ctx context.Context, arg GetCourtRecordByKeyParams) (GetCourtRecordByKeyRow, error)
	// Batch counterpart of GetCourtRecordByKey: resolve MANY records by their natural
	// keys in one round-trip, so a sync window partitions its whole result into existing
	// (reobservation → update) vs new (create) with ONE query instead of one GET per
	// record. Keys arrive as a jsonb array of {cnj_number, degree} — one scalar param,
	// so sqlc stays happy (it does not model multi-arg unnest).
	GetCourtRecordsByKeys(ctx context.Context, arg GetCourtRecordsByKeysParams) ([]GetCourtRecordsByKeysRow, error)
	GetIntegrationBySource(ctx context.Context, arg GetIntegrationBySourceParams) (Integration, error)
	// One intimation by id, for the FE deep-link into the inbox detail (an intimation not
	// on the loaded list page). SAME projection as ListIntimacoes — the record's
	// number/court/degree joined in — so it maps to the same IntimacaoView. Scoped by
	// tenant_id (barrier 1): a foreign or unknown id yields no row (→ typed 404 upstream,
	// never nil,nil). Read-only, off the write path.
	GetIntimacao(ctx context.Context, arg GetIntimacaoParams) (GetIntimacaoRow, error)
	// The tenant's most recent backfill job — status + tallies — for the import-status
	// read (the FE banner "importando seus processos…"). Newest job wins (a re-activation
	// opens a new job). No job ever → no row; the read use case maps that to NONE (not
	// importing). Scoped by tenant_id (isolation barrier 1; RLS is barrier 2).
	GetLatestBackfillStatus(ctx context.Context, tenantID uuid.UUID) (GetLatestBackfillStatusRow, error)
	// One import's reconciliação header (the detail screen), same shape/aggregation as
	// ListReconciliations but for a single backfill_job.
	GetReconciliation(ctx context.Context, arg GetReconciliationParams) (GetReconciliationRow, error)
	// Count one failed slice; same atomic lock-and-read-back contract as
	// IncrementBackfillSlicesOK. A job with any failed slice finalizes PARTIAL.
	IncrementBackfillSlicesError(ctx context.Context, arg IncrementBackfillSlicesErrorParams) (IncrementBackfillSlicesErrorRow, error)
	// Count one successful slice and read the job's tallies back atomically. The
	// UPDATE takes a row lock, so concurrent slice closes serialize and the counter
	// never loses a bump; the RETURNING lets the caller decide, in the same tx,
	// whether this was the last slice. Scoped by tenant_id (isolation barrier 1); a
	// non-matching row (wrong tenant / gone) affects zero rows and returns no row.
	IncrementBackfillSlicesOK(ctx context.Context, arg IncrementBackfillSlicesOKParams) (IncrementBackfillSlicesOKRow, error)
	// Create the onboarding backfill job. total_slices is precomputed by the use
	// case; the counters default to zero and status is passed explicitly so a
	// zero-slice horizon can land COMPLETED instead of RUNNING.
	InsertBackfillJob(ctx context.Context, arg InsertBackfillJobParams) (uuid.UUID, error)
	// Create the lide a first-seen court record hangs on. v0 has no consolidation
	// yet, so every new record gets its own case; merging is a later slice.
	InsertCourtCase(ctx context.Context, tenantID uuid.UUID) (uuid.UUID, error)
	// Create a court record under a case. The natural key (tenant, cnj, degree) is
	// UNIQUE; ON CONFLICT DO NOTHING makes a concurrent double-create idempotent (two
	// backfill windows discovering the same process at once) — the loser gets no row
	// (pgx.ErrNoRows) and the caller re-resolves the winner instead of a 23505 rollback.
	// judging_body (órgão julgador) comes from the source when disclosed (DJEN
	// nomeOrgao / DATAJUD orgaoJulgador), NULL when it does not.
	InsertCourtRecord(ctx context.Context, arg InsertCourtRecordParams) (uuid.UUID, error)
	// Append one andamento, idempotent on (court_record_id, hash). On conflict the
	// row is left untouched and no id is returned (pgx.ErrNoRows), which the caller
	// reads as "deduped" — so a re-sync emits no docket_entry_observed for it.
	// tpu_code (Tabela Processual Unificada) and complements are DATAJUD movimento
	// classification; NULL for sources that do not classify the entry.
	InsertDocketEntry(ctx context.Context, arg InsertDocketEntryParams) (uuid.UUID, error)
	// Append or reconcile one intimação, keyed on (tenant_id, case_id, hash). Unlike
	// docket entries, this is ON CONFLICT DO UPDATE (not DO NOTHING): when the DJEN
	// retracts a publication (data_cancelamento) the SAME hash re-arrives carrying
	// status=CANCELLED + cancelled_at/cancel_reason, and the existing row MUST be
	// updated so the deadline slice revokes the derived prazo — a DO NOTHING would
	// leave a phantom deadline. type/source_url are refreshed alongside. recipients is
	// written on insert and left untouched on update (the matched-OAB flag is stable
	// per hash). (xmax = 0) tells the caller whether THIS upsert inserted a fresh row
	// (true) or updated an existing one (false), so it can still tally new vs. deduped.
	InsertIntimation(ctx context.Context, arg InsertIntimationParams) (InsertIntimationRow, error)
	// publication store queries (acquisition slice). The national DJEN firehose: the
	// ingestion sweeps the diário by tribunal/day and lands every communication here,
	// to be matched to tenants' watched OABs locally. No tenant scope (national reference
	// data, like holiday), so no RLS and no tenant filter.
	// Land one national communication, idempotent on the DJEN hash (globally unique per
	// communication). The daily lookback re-fetches recent days, so ON CONFLICT (hash)
	// DO NOTHING makes a re-ingest a no-op: the loser gets no row (pgx.ErrNoRows), which
	// the caller reads as "already ingested" to tally new vs. deduped. recipient_oabs is
	// the normalized "NUMBER|UF" key set for the local OAB match; payload is the raw item.
	InsertPublication(ctx context.Context, arg InsertPublicationParams) (uuid.UUID, error)
	// sync cycle queries (acquisition slice).
	// The sync listener reacts to sync_requested: it opens a sync_run (RUNNING),
	// fetches+parses a window, then upserts the observed records/entries/intimations
	// and closes the run (OK/FAILED) — all keyed off the court_record's natural key
	// (tenant_id, cnj_number, degree). Idempotency lives in the schema: docket_entry
	// and intimation carry UNIQUE constraints, so a re-sync of the same window
	// inserts nothing new (ON CONFLICT DO NOTHING) and the RETURNING clause tells the
	// caller which rows were actually new.
	// Open a sync run. court_record_id is left NULL (OAB window discovery is not yet
	// tied to one record); finished_at/error stay NULL until the run closes. event_id
	// records the sync_requested event that opened it, so a re-delivery can find and
	// resume a run that never closed (FindSyncRunByEventID). window_from/to stamp the
	// slice's date window so the reconciliations read can show it (NULL when absent).
	InsertSyncRun(ctx context.Context, arg InsertSyncRunParams) (uuid.UUID, error)
	// Add one watched OAB for an integration, idempotent on (integration_id, oab_key):
	// a re-activation with the same scope is a no-op. oab_key is the normalized "NUMBER|UF".
	InsertWatchedOAB(ctx context.Context, arg InsertWatchedOABParams) error
	// The "Andamentos" tab of one process: the court record's docket entries, newest
	// first. Scoped by tenant via the court_record join (docket_entry has no tenant_id
	// of its own) so a foreign court_record.id passed as :id yields nothing. Descending
	// keyset on (occurred_at, id) — served by docket_entry(court_record_id, occurred_at)
	// — the first page passes the max sentinel ('9999-12-31T23:59:59Z', max-uuid).
	ListAndamentosByProcesso(ctx context.Context, arg ListAndamentosByProcessoParams) ([]ListAndamentosByProcessoRow, error)
	// All of a tenant's integrations, oldest first. tenant_id filter is isolation
	// barrier 1 (the app layer); RLS is barrier 2.
	ListIntegrations(ctx context.Context, tenantID uuid.UUID) ([]Integration, error)
	// The intimações inbox: the tenant's intimations, newest availability first, with
	// the court record's number/court/degree joined in. Descending keyset on
	// (made_available_at, id); the first page passes the max sentinel
	// ('9999-12-31', max-uuid).
	ListIntimacoes(ctx context.Context, arg ListIntimacoesParams) ([]ListIntimacoesRow, error)
	// The "Intimações" tab of one process: the intimations filed on this court record,
	// newest availability first, with the record's number/court/degree joined in (same
	// projection as ListIntimacoes). Scoped by both court_record_id (the :id) and
	// tenant_id (barrier 1) — intimation has its own tenant_id, so a foreign :id (another
	// tenant's record) matches nothing. Descending keyset on (made_available_at, id) —
	// served by intimation(court_record_id, made_available_at DESC) — the first page
	// passes the max sentinel ('9999-12-31', max-uuid).
	ListIntimacoesByProcesso(ctx context.Context, arg ListIntimacoesByProcessoParams) ([]ListIntimacoesByProcessoRow, error)
	// The intimations a window first discovered (collapse), newest availability first.
	ListIntimacoesBySyncRun(ctx context.Context, arg ListIntimacoesBySyncRunParams) ([]ListIntimacoesBySyncRunRow, error)
	// read-model queries (acquisition slice) — the screen reads, kept OFF the write
	// path (docs: "leitura de tela usa read model, DTO por query dedicada"). Each is
	// tenant-scoped (barrier 1) and keyset-paginated on a stable (sort_key, id) pair
	// so paging is offset-free and stable under concurrent inserts. The caller passes
	// a sentinel cursor for the first page, so there is no conditional WHERE.
	// The consolidated processes screen: the tenant's live court records (SUPERSEDED
	// placeholders drop out), each with its most recent andamento for the "last
	// movement" column. Ordered by cnj_number then id (ascending keyset): the first
	// page passes ('', zero-uuid).
	ListProcessos(ctx context.Context, arg ListProcessosParams) ([]ListProcessosRow, error)
	// The court records a window first discovered (collapse). Scoped by tenant (RLS +
	// filter) and the discovering sync_run_id; bounded defensively.
	ListProcessosBySyncRun(ctx context.Context, arg ListProcessosBySyncRunParams) ([]ListProcessosBySyncRunRow, error)
	// The reconciliations screen: one "reconciliação" per import (backfill_job), with
	// the processes/intimations its windows discovered summed up, the job's overall
	// date window (the janela de prazo geral) and slice tallies. finished_at is the
	// last window close once the job is no longer RUNNING (NULL while running).
	ListReconciliations(ctx context.Context, arg ListReconciliationsParams) ([]ListReconciliationsRow, error)
	// The windows (sync_runs) of one import, chronological, with the failure reason
	// lifted out of the error jsonb. Drives the detail screen's per-window table and
	// the collapse (each row's id feeds ListProcessos/IntimacoesBySyncRun).
	ListSyncRunsByJob(ctx context.Context, arg ListSyncRunsByJobParams) ([]ListSyncRunsByJobRow, error)
	// Record that a sync touched this court record: refresh its completeness and
	// schedule the next sweep (next_sync_at drives the scheduler slice later).
	// judging_body is COALESCEd, not overwritten: a sync that does not disclose the
	// órgão julgador (NULL) keeps the value a prior sync learned — DATAJUD reveals it
	// after a DJEN discovery landed the record without it (placeholder+merge).
	MarkCourtRecordSynced(ctx context.Context, arg MarkCourtRecordSyncedParams) error
	// match queries (acquisition slice). The join that turns the national publication
	// firehose into per-tenant work: a watched_oab key ∈ a publication's recipient_oabs.
	// Read system-wide (uow.DoSystem sets app.system='on' so the watched_oab RLS opens
	// across tenants); publication is national and unscoped.
	// Every (tenant, matched OAB, publication payload) for the communications made
	// available on a day. One publication watched by two OABs of the same tenant yields
	// two rows; the match use case groups by tenant and dedups the payloads. payload is
	// the raw DJEN item, re-parsed per matched tenant to create its court_record/intimação.
	MatchPublicationsByDay(ctx context.Context, madeAvailableAt pgtype.Date) ([]MatchPublicationsByDayRow, error)
	// One tenant's matches from a date forward — the onboarding history catch-up: a new
	// integration's watched OABs are matched against the publications ALREADY stored (the
	// 90-day bootstrap window), so the client sees its recent intimações immediately, with
	// ZERO per-OAB DJEN calls. The forward daily match (MatchPublicationsByDay) covers
	// everything from tomorrow on.
	MatchPublicationsForTenantSince(ctx context.Context, arg MatchPublicationsForTenantSinceParams) ([]MatchPublicationsForTenantSinceRow, error)
	// Merge-path only: move the placeholder's intimations onto a PRE-EXISTING graded
	// record when grading in place would violate the (tenant, cnj, degree) UNIQUE.
	// Unicidade de intimation é (tenant, case_id, hash), so swapping court_record_id never
	// breaks dedup (same case). Returns the number of rows moved.
	RepointIntimations(ctx context.Context, arg RepointIntimationsParams) (int64, error)
	// Merge-path only: retire the UNKNOWN placeholder after its intimations moved onto the
	// pre-existing graded record. It no longer represents a live process (the graded record
	// does), so it drops out of the ACTIVE count and the scheduler (next_sync_at NULL).
	SupersedeCourtRecord(ctx context.Context, arg SupersedeCourtRecordParams) error
	// enrichment cycle queries (acquisition slice).
	// DATAJUD enrichment reacts to court_record_observed for a DJEN placeholder
	// (degree=UNKNOWN): it fetches the process by number, reveals the grau, and GRADES
	// THE PLACEHOLDER IN PLACE — a single UPDATE that mutates the existing court_record
	// (ev.CourtRecordID) to the real degree + DATAJUD-authoritative fields on the SAME
	// id (UpdateCourtRecordGrade). Because the id never changes, the intimations,
	// deadlines and docket entries already anchored to it stay correct — no orphan, no
	// duplicate (FIX B). The (tenant, cnj, degree) UNIQUE means the ONE case that cannot
	// graduate in place is a rare pre-existing graded record at that grade: the use case
	// detects it first (GetCourtRecordByKey, sync.sql) and MERGES the placeholder into it
	// instead — RepointIntimations moves the placeholder's intimations onto the graded
	// record and SupersedeCourtRecord retires the placeholder (DJEN discovery produces no
	// docket entries, so the placeholder never has any to re-point).
	// Grade a court_record IN PLACE: mutate the row named by @court_record_id — the DJEN
	// UNKNOWN placeholder — to the DATAJUD-revealed degree and the fields DATAJUD is
	// authoritative for, keeping the SAME id. Because the id is stable, every child
	// already anchored to it (intimation, deadline, docket_entry) remains correct, which
	// is the whole point of FIX B. It also serves the scheduler re-poll of an
	// already-graded record: the degree is unchanged there (the caller guards the
	// grade-mismatch case), so this just refreshes the authoritative fields. next_sync_at
	// is seeded only when the row still has none (first grade); an existing schedule — the
	// scheduler's own claim — is preserved via COALESCE, so the scheduler keeps owning the
	// re-poll cadence. case_id is never touched (the record keeps its Pasta). RETURNING
	// carries id + case_id for the caller. The (tenant, cnj, degree) UNIQUE requires the
	// caller to ensure no OTHER record already holds @degree (the merge path handles that).
	UpdateCourtRecordGrade(ctx context.Context, arg UpdateCourtRecordGradeParams) (UpdateCourtRecordGradeRow, error)
	// Close a sync run, but ONLY from RUNNING: the status guard makes this the single
	// winning transition (compare-and-swap), so a redelivery that resumes a run
	// another execution already closed affects zero rows. OK carries the item tallies
	// and a NULL error; FAILED carries the error jsonb and zero tallies. finished_at
	// is set by the caller's clock. RETURNING id lets the caller learn whether this
	// close won (a row) or lost the race (pgx.ErrNoRows) — the signal to publish the
	// terminal event exactly once. Mirrors FinalizeBackfillJob's RUNNING-only guard.
	UpdateSyncRun(ctx context.Context, arg UpdateSyncRunParams) (uuid.UUID, error)
	// acquisition slice queries (integration).
	// The upsert is keyed by (tenant_id, source) so re-activating a source is
	// idempotent at the row level; credential_ref is never written from here (it
	// stays NULL in v0) and is preserved across updates.
	// Activate (or re-activate) a tenant's subscription to a data source. On
	// conflict only scope/status/updated_at change — credential_ref is left intact.
	UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) (Integration, error)
}

var _ Querier = (*Queries)(nil)
