// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read.sql

package acquisitiondb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countIntimationsByTenant = `-- name: CountIntimationsByTenant :one
SELECT count(*) FROM intimation WHERE tenant_id = $1
`

// The reconciliations totals: how many intimations the tenant holds (paired with
// CountActiveCourtRecordsByTenant for the processes side).
func (q *Queries) CountIntimationsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIntimationsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReconciliationUmbrella = `-- name: GetReconciliationUmbrella :one
SELECT b.id, i.source, b.status, b.window_from, b.window_to,
       b.total_slices, b.slices_ok, b.slices_error, b.created_at AS started_at,
       COALESCE(SUM(s.court_records_new), 0)::bigint AS processos,
       COALESCE(SUM(s.intimations_new), 0)::bigint AS intimacoes,
       (CASE WHEN b.status = 'RUNNING' THEN NULL ELSE MAX(s.finished_at) END)::timestamptz AS finished_at
FROM backfill_job b
JOIN integration i ON i.id = b.integration_id
LEFT JOIN sync_run s ON s.backfill_job_id = b.id
WHERE b.tenant_id = $1 AND b.id = $2
GROUP BY b.id, i.source
`

type GetReconciliationUmbrellaParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

type GetReconciliationUmbrellaRow struct {
	ID          uuid.UUID          `json:"id"`
	Source      string             `json:"source"`
	Status      string             `json:"status"`
	WindowFrom  pgtype.Date        `json:"window_from"`
	WindowTo    pgtype.Date        `json:"window_to"`
	TotalSlices int32              `json:"total_slices"`
	SlicesOk    int32              `json:"slices_ok"`
	SlicesError int32              `json:"slices_error"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	Processos   int64              `json:"processos"`
	Intimacoes  int64              `json:"intimacoes"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

// One import's guarda-chuva header (the detail screen), same shape/aggregation as
// ListReconciliationUmbrellas but for a single backfill_job.
func (q *Queries) GetReconciliationUmbrella(ctx context.Context, arg GetReconciliationUmbrellaParams) (GetReconciliationUmbrellaRow, error) {
	row := q.db.QueryRow(ctx, getReconciliationUmbrella, arg.TenantID, arg.ID)
	var i GetReconciliationUmbrellaRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Status,
		&i.WindowFrom,
		&i.WindowTo,
		&i.TotalSlices,
		&i.SlicesOk,
		&i.SlicesError,
		&i.StartedAt,
		&i.Processos,
		&i.Intimacoes,
		&i.FinishedAt,
	)
	return i, err
}

const listIntimacoes = `-- name: ListIntimacoes :many
SELECT i.id, i.made_available_at, i.published_at, i.deadline_start_at,
       i.content, i.type, i.status, i.source, i.source_url,
       cr.cnj_number, cr.court, cr.degree
FROM intimation i
JOIN court_record cr ON cr.id = i.court_record_id
WHERE i.tenant_id = $1
  AND (i.made_available_at, i.id) < ($3::date, $4::uuid)
ORDER BY i.made_available_at DESC, i.id DESC
LIMIT $2
`

type ListIntimacoesParams struct {
	TenantID          uuid.UUID   `json:"tenant_id"`
	Limit             int32       `json:"limit"`
	LastMadeAvailable pgtype.Date `json:"last_made_available"`
	LastID            uuid.UUID   `json:"last_id"`
}

type ListIntimacoesRow struct {
	ID              uuid.UUID   `json:"id"`
	MadeAvailableAt pgtype.Date `json:"made_available_at"`
	PublishedAt     pgtype.Date `json:"published_at"`
	DeadlineStartAt pgtype.Date `json:"deadline_start_at"`
	Content         string      `json:"content"`
	Type            *string     `json:"type"`
	Status          string      `json:"status"`
	Source          string      `json:"source"`
	SourceUrl       *string     `json:"source_url"`
	CnjNumber       string      `json:"cnj_number"`
	Court           string      `json:"court"`
	Degree          string      `json:"degree"`
}

// The intimações inbox: the tenant's intimations, newest availability first, with
// the court record's number/court/degree joined in. Descending keyset on
// (made_available_at, id); the first page passes the max sentinel
// ('9999-12-31', max-uuid).
func (q *Queries) ListIntimacoes(ctx context.Context, arg ListIntimacoesParams) ([]ListIntimacoesRow, error) {
	rows, err := q.db.Query(ctx, listIntimacoes,
		arg.TenantID,
		arg.Limit,
		arg.LastMadeAvailable,
		arg.LastID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIntimacoesRow
	for rows.Next() {
		var i ListIntimacoesRow
		if err := rows.Scan(
			&i.ID,
			&i.MadeAvailableAt,
			&i.PublishedAt,
			&i.DeadlineStartAt,
			&i.Content,
			&i.Type,
			&i.Status,
			&i.Source,
			&i.SourceUrl,
			&i.CnjNumber,
			&i.Court,
			&i.Degree,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntimacoesBySyncRun = `-- name: ListIntimacoesBySyncRun :many
SELECT i.id, i.made_available_at, i.type, i.status,
       cr.cnj_number, cr.court, cr.degree
FROM intimation i
JOIN court_record cr ON cr.id = i.court_record_id
WHERE i.tenant_id = $1 AND i.sync_run_id = $2
ORDER BY i.made_available_at DESC, i.id DESC
LIMIT 1000
`

type ListIntimacoesBySyncRunParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	SyncRunID pgtype.UUID `json:"sync_run_id"`
}

type ListIntimacoesBySyncRunRow struct {
	ID              uuid.UUID   `json:"id"`
	MadeAvailableAt pgtype.Date `json:"made_available_at"`
	Type            *string     `json:"type"`
	Status          string      `json:"status"`
	CnjNumber       string      `json:"cnj_number"`
	Court           string      `json:"court"`
	Degree          string      `json:"degree"`
}

// The intimations a window first discovered (collapse), newest availability first.
func (q *Queries) ListIntimacoesBySyncRun(ctx context.Context, arg ListIntimacoesBySyncRunParams) ([]ListIntimacoesBySyncRunRow, error) {
	rows, err := q.db.Query(ctx, listIntimacoesBySyncRun, arg.TenantID, arg.SyncRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIntimacoesBySyncRunRow
	for rows.Next() {
		var i ListIntimacoesBySyncRunRow
		if err := rows.Scan(
			&i.ID,
			&i.MadeAvailableAt,
			&i.Type,
			&i.Status,
			&i.CnjNumber,
			&i.Court,
			&i.Degree,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessos = `-- name: ListProcessos :many

SELECT cr.id, cr.case_id, cr.cnj_number, cr.court, cr.degree, cr.class, cr.subject,
       cr.judging_body, cr.filed_at, cr.secrecy, cr.lifecycle, cr.completeness,
       COALESCE(m.text, '') AS last_movement_text, m.occurred_at AS last_movement_at
FROM court_record cr
LEFT JOIN LATERAL (
    SELECT de.text, de.occurred_at
    FROM docket_entry de
    WHERE de.court_record_id = cr.id
    ORDER BY de.occurred_at DESC
    LIMIT 1
) m ON true
WHERE cr.tenant_id = $1
  AND cr.lifecycle = 'ACTIVE'
  AND (cr.cnj_number, cr.id) > ($3::text, $4::uuid)
ORDER BY cr.cnj_number, cr.id
LIMIT $2
`

type ListProcessosParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	LastCnj  string    `json:"last_cnj"`
	LastID   uuid.UUID `json:"last_id"`
}

type ListProcessosRow struct {
	ID               uuid.UUID          `json:"id"`
	CaseID           uuid.UUID          `json:"case_id"`
	CnjNumber        string             `json:"cnj_number"`
	Court            string             `json:"court"`
	Degree           string             `json:"degree"`
	Class            *string            `json:"class"`
	Subject          *string            `json:"subject"`
	JudgingBody      *string            `json:"judging_body"`
	FiledAt          pgtype.Date        `json:"filed_at"`
	Secrecy          string             `json:"secrecy"`
	Lifecycle        string             `json:"lifecycle"`
	Completeness     float32            `json:"completeness"`
	LastMovementText string             `json:"last_movement_text"`
	LastMovementAt   pgtype.Timestamptz `json:"last_movement_at"`
}

// read-model queries (acquisition slice) — the screen reads, kept OFF the write
// path (docs: "leitura de tela usa read model, DTO por query dedicada"). Each is
// tenant-scoped (barrier 1) and keyset-paginated on a stable (sort_key, id) pair
// so paging is offset-free and stable under concurrent inserts. The caller passes
// a sentinel cursor for the first page, so there is no conditional WHERE.
// The consolidated processes screen: the tenant's live court records (SUPERSEDED
// placeholders drop out), each with its most recent andamento for the "last
// movement" column. Ordered by cnj_number then id (ascending keyset): the first
// page passes (”, zero-uuid).
func (q *Queries) ListProcessos(ctx context.Context, arg ListProcessosParams) ([]ListProcessosRow, error) {
	rows, err := q.db.Query(ctx, listProcessos,
		arg.TenantID,
		arg.Limit,
		arg.LastCnj,
		arg.LastID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProcessosRow
	for rows.Next() {
		var i ListProcessosRow
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.CnjNumber,
			&i.Court,
			&i.Degree,
			&i.Class,
			&i.Subject,
			&i.JudgingBody,
			&i.FiledAt,
			&i.Secrecy,
			&i.Lifecycle,
			&i.Completeness,
			&i.LastMovementText,
			&i.LastMovementAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessosBySyncRun = `-- name: ListProcessosBySyncRun :many
SELECT cr.id, cr.cnj_number, cr.court, cr.degree, cr.class
FROM court_record cr
WHERE cr.tenant_id = $1 AND cr.sync_run_id = $2
ORDER BY cr.cnj_number
LIMIT 1000
`

type ListProcessosBySyncRunParams struct {
	TenantID  uuid.UUID   `json:"tenant_id"`
	SyncRunID pgtype.UUID `json:"sync_run_id"`
}

type ListProcessosBySyncRunRow struct {
	ID        uuid.UUID `json:"id"`
	CnjNumber string    `json:"cnj_number"`
	Court     string    `json:"court"`
	Degree    string    `json:"degree"`
	Class     *string   `json:"class"`
}

// The court records a window first discovered (collapse). Scoped by tenant (RLS +
// filter) and the discovering sync_run_id; bounded defensively.
func (q *Queries) ListProcessosBySyncRun(ctx context.Context, arg ListProcessosBySyncRunParams) ([]ListProcessosBySyncRunRow, error) {
	rows, err := q.db.Query(ctx, listProcessosBySyncRun, arg.TenantID, arg.SyncRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProcessosBySyncRunRow
	for rows.Next() {
		var i ListProcessosBySyncRunRow
		if err := rows.Scan(
			&i.ID,
			&i.CnjNumber,
			&i.Court,
			&i.Degree,
			&i.Class,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconciliationUmbrellas = `-- name: ListReconciliationUmbrellas :many
SELECT b.id, i.source, b.status, b.window_from, b.window_to,
       b.total_slices, b.slices_ok, b.slices_error, b.created_at AS started_at,
       COALESCE(SUM(s.court_records_new), 0)::bigint AS processos,
       COALESCE(SUM(s.intimations_new), 0)::bigint AS intimacoes,
       (CASE WHEN b.status = 'RUNNING' THEN NULL ELSE MAX(s.finished_at) END)::timestamptz AS finished_at
FROM backfill_job b
JOIN integration i ON i.id = b.integration_id
LEFT JOIN sync_run s ON s.backfill_job_id = b.id
WHERE b.tenant_id = $1
GROUP BY b.id, i.source
ORDER BY b.created_at DESC, b.id DESC
LIMIT $2
`

type ListReconciliationUmbrellasParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

type ListReconciliationUmbrellasRow struct {
	ID          uuid.UUID          `json:"id"`
	Source      string             `json:"source"`
	Status      string             `json:"status"`
	WindowFrom  pgtype.Date        `json:"window_from"`
	WindowTo    pgtype.Date        `json:"window_to"`
	TotalSlices int32              `json:"total_slices"`
	SlicesOk    int32              `json:"slices_ok"`
	SlicesError int32              `json:"slices_error"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	Processos   int64              `json:"processos"`
	Intimacoes  int64              `json:"intimacoes"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

// The reconciliations screen: one "guarda-chuva" per import (backfill_job), with
// the processes/intimations its windows discovered summed up, the job's overall
// date window (the janela de prazo geral) and slice tallies. finished_at is the
// last window close once the job is no longer RUNNING (NULL while running).
func (q *Queries) ListReconciliationUmbrellas(ctx context.Context, arg ListReconciliationUmbrellasParams) ([]ListReconciliationUmbrellasRow, error) {
	rows, err := q.db.Query(ctx, listReconciliationUmbrellas, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReconciliationUmbrellasRow
	for rows.Next() {
		var i ListReconciliationUmbrellasRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Status,
			&i.WindowFrom,
			&i.WindowTo,
			&i.TotalSlices,
			&i.SlicesOk,
			&i.SlicesError,
			&i.StartedAt,
			&i.Processos,
			&i.Intimacoes,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncRunsByJob = `-- name: ListSyncRunsByJob :many
SELECT s.id, i.source, s.window_from, s.window_to, s.status,
       s.court_records_new, s.intimations_new,
       COALESCE(s.error->>'message', '')::text AS error_message,
       s.started_at, s.finished_at
FROM sync_run s
JOIN integration i ON i.id = s.integration_id
WHERE s.tenant_id = $1 AND s.backfill_job_id = $2
ORDER BY s.window_from ASC, s.started_at ASC
`

type ListSyncRunsByJobParams struct {
	TenantID      uuid.UUID   `json:"tenant_id"`
	BackfillJobID pgtype.UUID `json:"backfill_job_id"`
}

type ListSyncRunsByJobRow struct {
	ID              uuid.UUID          `json:"id"`
	Source          string             `json:"source"`
	WindowFrom      pgtype.Date        `json:"window_from"`
	WindowTo        pgtype.Date        `json:"window_to"`
	Status          string             `json:"status"`
	CourtRecordsNew int32              `json:"court_records_new"`
	IntimationsNew  int32              `json:"intimations_new"`
	ErrorMessage    string             `json:"error_message"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
}

// The windows (sync_runs) of one import, chronological, with the failure reason
// lifted out of the error jsonb. Drives the detail screen's per-window table and
// the collapse (each row's id feeds ListProcessos/IntimacoesBySyncRun).
func (q *Queries) ListSyncRunsByJob(ctx context.Context, arg ListSyncRunsByJobParams) ([]ListSyncRunsByJobRow, error) {
	rows, err := q.db.Query(ctx, listSyncRunsByJob, arg.TenantID, arg.BackfillJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSyncRunsByJobRow
	for rows.Next() {
		var i ListSyncRunsByJobRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.WindowFrom,
			&i.WindowTo,
			&i.Status,
			&i.CourtRecordsNew,
			&i.IntimationsNew,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
