// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: responsible.sql

package acquisitiondb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appUserExistsInTenant = `-- name: AppUserExistsInTenant :one
SELECT EXISTS (
    SELECT 1 FROM app_user au
    WHERE au.id = $1 AND au.tenant_id = $2
) AS present
`

type AppUserExistsInTenantParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Membership guard for the assign write: is $1 an app_user of tenant $2? Used only when
// a non-null user_id is being assigned (desatribuir skips it). A false result → the
// typed "usuário não é membro do escritório" (→ 404/invalid) so a caller cannot pin a
// process on a user outside their escritório.
func (q *Queries) AppUserExistsInTenant(ctx context.Context, arg AppUserExistsInTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, appUserExistsInTenant, arg.ID, arg.TenantID)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const assignCaseResponsible = `-- name: AssignCaseResponsible :exec
UPDATE court_case
   SET assigned_user_id = $2
 WHERE id = $1 AND tenant_id = $3
`

type AssignCaseResponsibleParams struct {
	ID             uuid.UUID   `json:"id"`
	AssignedUserID pgtype.UUID `json:"assigned_user_id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
}

// Set (or clear, when $2 is NULL) the responsável on a court_case, tenant-scoped
// (barrier 1, with RLS as barrier 2). The case_id is the one resolved from the
// court_record above; the WHERE ties the write to the caller's own tenant so a mismatched
// (case, tenant) touches nothing. Idempotent — re-assigning the same user is a no-op write.
func (q *Queries) AssignCaseResponsible(ctx context.Context, arg AssignCaseResponsibleParams) error {
	_, err := q.db.Exec(ctx, assignCaseResponsible, arg.ID, arg.AssignedUserID, arg.TenantID)
	return err
}

const bulkAssignCaseResponsible = `-- name: BulkAssignCaseResponsible :execrows
UPDATE court_case
   SET assigned_user_id = $1::uuid
 WHERE tenant_id = $2::uuid
   AND id = ANY($3::uuid[])
`

type BulkAssignCaseResponsibleParams struct {
	AssigneeUserID pgtype.UUID `json:"assignee_user_id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
	CaseIds        []uuid.UUID `json:"case_ids"`
}

// Atribuição em massa do responsável para uma lista de court_case ids (já resolvida
// pelas duas queries acima), tenant-scoped (barrier 1, RLS barrier 2). NULL desatribui.
func (q *Queries) BulkAssignCaseResponsible(ctx context.Context, arg BulkAssignCaseResponsibleParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkAssignCaseResponsible, arg.AssigneeUserID, arg.TenantID, arg.CaseIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkCascadeCaseResponsibleToIntimations = `-- name: BulkCascadeCaseResponsibleToIntimations :execrows
UPDATE intimation i
   SET assignee_user_id = $1::uuid
  FROM court_record cr
 WHERE i.court_record_id = cr.id
   AND i.tenant_id = $2::uuid
   AND cr.case_id = ANY($3::uuid[])
`

type BulkCascadeCaseResponsibleToIntimationsParams struct {
	AssigneeUserID pgtype.UUID `json:"assignee_user_id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
	CaseIds        []uuid.UUID `json:"case_ids"`
}

// Gêmeo batchado de CascadeCaseResponsibleToIntimations: cascateia o mesmo
// responsável para as intimações filhas de TODOS os court_case em @case_ids, na
// MESMA tx do bulk assign acima. NULL desatribui (mesma semântica do pai).
func (q *Queries) BulkCascadeCaseResponsibleToIntimations(ctx context.Context, arg BulkCascadeCaseResponsibleToIntimationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkCascadeCaseResponsibleToIntimations, arg.AssigneeUserID, arg.TenantID, arg.CaseIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cascadeCaseResponsibleToIntimations = `-- name: CascadeCaseResponsibleToIntimations :execrows
UPDATE intimation i
   SET assignee_user_id = $1::uuid
  FROM court_record cr
 WHERE i.court_record_id = cr.id
   AND cr.case_id = $2::uuid
   AND i.tenant_id = $3::uuid
`

type CascadeCaseResponsibleToIntimationsParams struct {
	AssigneeUserID pgtype.UUID `json:"assignee_user_id"`
	CaseID         uuid.UUID   `json:"case_id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
}

// Cascateia o responsável do court_case para as intimações filhas, na MESMA tx do
// AssignResponsible. Filtra por court_record_id → court_record.case_id (não por
// intimation.case_id direto): é essa a coluna que todo READ do app usa para decidir
// "a qual processo esta intimação pertence". Um UPDATE ... FROM, O(1) statements
// independente de N filhas. NULL desatribui (mesma semântica do pai).
func (q *Queries) CascadeCaseResponsibleToIntimations(ctx context.Context, arg CascadeCaseResponsibleToIntimationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, cascadeCaseResponsibleToIntimations, arg.AssigneeUserID, arg.CaseID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCaseAssignedUser = `-- name: GetCaseAssignedUser :one
SELECT assigned_user_id FROM court_case WHERE id = $1::uuid AND tenant_id = $2::uuid
`

type GetCaseAssignedUserParams struct {
	CaseID   uuid.UUID `json:"case_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Lê o assigned_user_id vigente do court_case, dentro da tx do caller, tenant-scoped.
// Usado no merge de grade (gradeInTx) para re-sincronizar o responsável do case de
// DESTINO nas intimações repontadas, ANTES de cascatear.
func (q *Queries) GetCaseAssignedUser(ctx context.Context, arg GetCaseAssignedUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCaseAssignedUser, arg.CaseID, arg.TenantID)
	var assigned_user_id pgtype.UUID
	err := row.Scan(&assigned_user_id)
	return assigned_user_id, err
}

const getCaseIDByCourtRecord = `-- name: GetCaseIDByCourtRecord :one

SELECT cr.case_id
FROM court_record cr
WHERE cr.id = $1 AND cr.tenant_id = $2
`

type GetCaseIDByCourtRecordParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// responsável do processo (case-level) — the write path for PUT
// /v1/processos/:id/responsavel. All three run inside the caller's tx (UoW +
// SET LOCAL app.tenant_id), so RLS is a second barrier under the explicit
// tenant_id filters here. No outbox event yet — auditoria/evento is a future
// slice (there is no consumer), so this is a bare projection write.
// Resolve the court_case behind a court_record :id, tenant-scoped (barrier 1). The FE
// addresses a process by its court_record id (the same id /processos returns), but the
// responsável lives on court_case — so the write must hop record → case first. No row
// (unknown id or a foreign tenant's record) → pgx.ErrNoRows, mapped to ErrProcessoNotFound
// (→ 404) upstream, never nil,nil.
func (q *Queries) GetCaseIDByCourtRecord(ctx context.Context, arg GetCaseIDByCourtRecordParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCaseIDByCourtRecord, arg.ID, arg.TenantID)
	var case_id uuid.UUID
	err := row.Scan(&case_id)
	return case_id, err
}

const resolveCaseIDsByProcessosFilter = `-- name: ResolveCaseIDsByProcessosFilter :many
SELECT cr.id, cr.case_id
FROM court_record cr
LEFT JOIN court_case cc ON cc.id = cr.case_id
WHERE cr.tenant_id = $1::uuid
  AND ($2::text = '' OR cr.cnj_number ILIKE '%' || $2 || '%' ESCAPE '\')
  AND ($3::text = '' OR cr.court = $3::text)
  AND ($4::text = '' OR cr.degree = $4::text)
  AND ($5::text = '' OR cr.lifecycle = $5::text)
  AND ($5::text <> '' OR cr.lifecycle = 'ACTIVE')
  AND ($6::uuid IS NULL OR cc.assigned_user_id = $6::uuid)
`

type ResolveCaseIDsByProcessosFilterParams struct {
	TenantID   uuid.UUID   `json:"tenant_id"`
	Search     string      `json:"search"`
	Court      string      `json:"court"`
	Degree     string      `json:"degree"`
	Lifecycle  string      `json:"lifecycle"`
	AssigneeID pgtype.UUID `json:"assignee_id"`
}

type ResolveCaseIDsByProcessosFilterRow struct {
	ID     uuid.UUID `json:"id"`
	CaseID uuid.UUID `json:"case_id"`
}

// Gêmeo de ResolveCaseIDsByRecordIDs pro modo "all" do bulk: reusa EXATAMENTE a
// cláusula de filtro do ListProcessos (search/court/degree/lifecycle/assignee), de
// modo que "all" aplica a TODA a faixa filtrada, não só à página carregada.
func (q *Queries) ResolveCaseIDsByProcessosFilter(ctx context.Context, arg ResolveCaseIDsByProcessosFilterParams) ([]ResolveCaseIDsByProcessosFilterRow, error) {
	rows, err := q.db.Query(ctx, resolveCaseIDsByProcessosFilter,
		arg.TenantID,
		arg.Search,
		arg.Court,
		arg.Degree,
		arg.Lifecycle,
		arg.AssigneeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveCaseIDsByProcessosFilterRow
	for rows.Next() {
		var i ResolveCaseIDsByProcessosFilterRow
		if err := rows.Scan(&i.ID, &i.CaseID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveCaseIDsByRecordIDs = `-- name: ResolveCaseIDsByRecordIDs :many

SELECT cr.id, cr.case_id
FROM court_record cr
WHERE cr.tenant_id = $1::uuid
  AND cr.id = ANY($2::uuid[])
`

type ResolveCaseIDsByRecordIDsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Ids      []uuid.UUID `json:"ids"`
}

type ResolveCaseIDsByRecordIDsRow struct {
	ID     uuid.UUID `json:"id"`
	CaseID uuid.UUID `json:"case_id"`
}

// ── bulk (POST /v1/processos/bulk/responsavel) ──────────────────────────────────
// Twins batchados do fluxo acima (GetCaseIDByCourtRecord → AssignCaseResponsible →
// CascadeCaseResponsibleToIntimations), pra atribuir o responsável a vários
// processos numa tx só. A FE endereça processos pelo court_record :id (mesma
// granularidade do PUT single-item); o responsável vive no court_case (case-level,
// compartilhado entre graus) — então o write resolve ids/filtro para os court_case
// por trás e cascateia pras intimações filhas.
// Gêmeo batchado de GetCaseIDByCourtRecord, pro modo "por ids" do bulk: resolve os
// pares (record_id, case_id) para uma lista explícita, tenant-scoped (barrier 1).
// Ids desconhecidos ou de outro tenant simplesmente somem do resultado (sem erro) —
// o "affected" do caller é len(rows), mesma semântica de BulkAssignIntimacoesByIDs.
func (q *Queries) ResolveCaseIDsByRecordIDs(ctx context.Context, arg ResolveCaseIDsByRecordIDsParams) ([]ResolveCaseIDsByRecordIDsRow, error) {
	rows, err := q.db.Query(ctx, resolveCaseIDsByRecordIDs, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveCaseIDsByRecordIDsRow
	for rows.Next() {
		var i ResolveCaseIDsByRecordIDsRow
		if err := rows.Scan(&i.ID, &i.CaseID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
