// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resumo.sql

package acquisitiondb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getResumoActiveIntimations = `-- name: GetResumoActiveIntimations :many
SELECT i.type, i.content AS teor, d.days AS deadline_days
FROM intimation i
LEFT JOIN deadline d ON d.notification_id = i.id
WHERE i.court_record_id = $1
  AND i.tenant_id = $2
  AND i.status = 'ACTIVE'
ORDER BY i.made_available_at DESC
`

type GetResumoActiveIntimationsParams struct {
	CourtRecordID uuid.UUID `json:"court_record_id"`
	TenantID      uuid.UUID `json:"tenant_id"`
}

type GetResumoActiveIntimationsRow struct {
	Type         *string `json:"type"`
	Teor         string  `json:"teor"`
	DeadlineDays *int32  `json:"deadline_days"`
}

// The intimations with status = 'ACTIVE' (the DJEN cancellation lifecycle), each with
// the days of its derived deadline (deadline.days, via the 1:1 notification_id link;
// NULL when the intimação has no prazo yet). tenant-scoped.
func (q *Queries) GetResumoActiveIntimations(ctx context.Context, arg GetResumoActiveIntimationsParams) ([]GetResumoActiveIntimationsRow, error) {
	rows, err := q.db.Query(ctx, getResumoActiveIntimations, arg.CourtRecordID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResumoActiveIntimationsRow
	for rows.Next() {
		var i GetResumoActiveIntimationsRow
		if err := rows.Scan(&i.Type, &i.Teor, &i.DeadlineDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResumoContext = `-- name: GetResumoContext :one

SELECT
    cr.id,
    cr.cnj_number,
    cr.court,
    cr.degree,
    cr.class,
    cr.subject,
    cr.lifecycle,
    cr.filed_at,
    cr.judging_body,
    cr.ai_resume,
    cr.ai_resume_generated_at
FROM court_record cr
WHERE cr.id = $1 AND cr.tenant_id = $2
`

type GetResumoContextParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetResumoContextRow struct {
	ID                  uuid.UUID          `json:"id"`
	CnjNumber           string             `json:"cnj_number"`
	Court               string             `json:"court"`
	Degree              string             `json:"degree"`
	Class               *string            `json:"class"`
	Subject             *string            `json:"subject"`
	Lifecycle           string             `json:"lifecycle"`
	FiledAt             pgtype.Date        `json:"filed_at"`
	JudgingBody         *string            `json:"judging_body"`
	AiResume            []byte             `json:"ai_resume"`
	AiResumeGeneratedAt pgtype.Timestamptz `json:"ai_resume_generated_at"`
}

// resumo.sql — read-model queries for the AI process summary (GET /v1/processos/:id/resume).
// The context is assembled by the repository from four narrow queries (one base row +
// three :many reads) so sqlc types every column instead of a json_agg that would come
// back as an opaque interface{}. The write query persists the AI summary best-effort
// (WHERE ai_resume IS NULL makes it idempotent — a race between two first-opens is a
// safe no-op on the loser).
// One process's identification row plus the cached AI resume (if any). Scoped by
// tenant_id + court_record_id (barrier 1). A miss/foreign row → pgx.ErrNoRows →
// ErrProcessoNotFound (the same 404 semantics as GetProcesso).
func (q *Queries) GetResumoContext(ctx context.Context, arg GetResumoContextParams) (GetResumoContextRow, error) {
	row := q.db.QueryRow(ctx, getResumoContext, arg.ID, arg.TenantID)
	var i GetResumoContextRow
	err := row.Scan(
		&i.ID,
		&i.CnjNumber,
		&i.Court,
		&i.Degree,
		&i.Class,
		&i.Subject,
		&i.Lifecycle,
		&i.FiledAt,
		&i.JudgingBody,
		&i.AiResume,
		&i.AiResumeGeneratedAt,
	)
	return i, err
}

const getResumoMovements = `-- name: GetResumoMovements :many
SELECT de.occurred_at, de.text
FROM docket_entry de
JOIN court_record cr ON cr.id = de.court_record_id
WHERE de.court_record_id = $1
  AND cr.tenant_id = $2
ORDER BY de.occurred_at DESC
LIMIT 10
`

type GetResumoMovementsParams struct {
	CourtRecordID uuid.UUID `json:"court_record_id"`
	TenantID      uuid.UUID `json:"tenant_id"`
}

type GetResumoMovementsRow struct {
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Text       string             `json:"text"`
}

// The last 10 docket entries for the process, newest first. Scoped by tenant through
// the court_record join (docket_entry carries no tenant_id of its own).
func (q *Queries) GetResumoMovements(ctx context.Context, arg GetResumoMovementsParams) ([]GetResumoMovementsRow, error) {
	rows, err := q.db.Query(ctx, getResumoMovements, arg.CourtRecordID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResumoMovementsRow
	for rows.Next() {
		var i GetResumoMovementsRow
		if err := rows.Scan(&i.OccurredAt, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResumoOpenDeadlines = `-- name: GetResumoOpenDeadlines :many
SELECT d.kind, d.end_date, (d.end_date - CURRENT_DATE)::int AS days_left, d.counting
FROM deadline d
WHERE d.court_record_id = $1
  AND d.tenant_id = $2
  AND d.status IN ('OPEN', 'PENDING')
ORDER BY d.end_date ASC
`

type GetResumoOpenDeadlinesParams struct {
	CourtRecordID uuid.UUID `json:"court_record_id"`
	TenantID      uuid.UUID `json:"tenant_id"`
}

type GetResumoOpenDeadlinesRow struct {
	Kind     *string     `json:"kind"`
	EndDate  pgtype.Date `json:"end_date"`
	DaysLeft int32       `json:"days_left"`
	Counting string      `json:"counting"`
}

// The prazos that are not closed (OPEN or PENDING — a prazo born PENDING is a rule
// suggestion awaiting F2 confirmation, still relevant to the summary). days_left is
// computed as calendar days to end_date, mirroring the prazos screen read. tenant-scoped.
func (q *Queries) GetResumoOpenDeadlines(ctx context.Context, arg GetResumoOpenDeadlinesParams) ([]GetResumoOpenDeadlinesRow, error) {
	rows, err := q.db.Query(ctx, getResumoOpenDeadlines, arg.CourtRecordID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResumoOpenDeadlinesRow
	for rows.Next() {
		var i GetResumoOpenDeadlinesRow
		if err := rows.Scan(
			&i.Kind,
			&i.EndDate,
			&i.DaysLeft,
			&i.Counting,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCourtRecordAIResume = `-- name: SetCourtRecordAIResume :exec
UPDATE court_record
SET ai_resume = $1,
    ai_resume_generated_at = now()
WHERE id = $2
  AND tenant_id = $3
  AND ai_resume IS NULL
`

type SetCourtRecordAIResumeParams struct {
	AiResume []byte    `json:"ai_resume"`
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// Best-effort persist of the AI-generated resume. The WHERE ai_resume IS NULL makes
// the write idempotent at the DB layer — a race between two first-opens updates 0
// rows on the loser, which is NOT an error (write-once by design).
func (q *Queries) SetCourtRecordAIResume(ctx context.Context, arg SetCourtRecordAIResumeParams) error {
	_, err := q.db.Exec(ctx, setCourtRecordAIResume, arg.AiResume, arg.ID, arg.TenantID)
	return err
}
