// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduler.sql

package acquisitiondb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimCourtRecordResync = `-- name: ClaimCourtRecordResync :exec
UPDATE court_record
SET next_sync_at = $2
WHERE id = $1
`

type ClaimCourtRecordResyncParams struct {
	ID         uuid.UUID          `json:"id"`
	NextSyncAt pgtype.Timestamptz `json:"next_sync_at"`
}

// Push a record's next_sync_at forward as its re-poll is enqueued, so the next tick
// does not re-enqueue it; if the resync never lands, it falls due again after the
// interval (at-least-once).
func (q *Queries) ClaimCourtRecordResync(ctx context.Context, arg ClaimCourtRecordResyncParams) error {
	_, err := q.db.Exec(ctx, claimCourtRecordResync, arg.ID, arg.NextSyncAt)
	return err
}

const dueCourtRecordsForResync = `-- name: DueCourtRecordsForResync :many

SELECT id, tenant_id, case_id, cnj_number, degree, court
FROM court_record
WHERE lifecycle = 'ACTIVE' AND next_sync_at IS NOT NULL AND next_sync_at <= now()
ORDER BY next_sync_at
LIMIT $1
`

type DueCourtRecordsForResyncRow struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	CaseID    uuid.UUID `json:"case_id"`
	CnjNumber string    `json:"cnj_number"`
	Degree    string    `json:"degree"`
	Court     string    `json:"court"`
}

// scheduler (re-poll) queries (acquisition slice).
// The re-poll scheduler runs system-scoped (DoSystem sets app.system='on', so the
// court_record RLS system escape hatch from migration 0016 exposes every tenant's
// rows). Each tick it finds records whose next_sync_at is due, enqueues a fresh
// court_record_observed for each (the enrichment consumer refreshes the DATAJUD
// movimentos), and claims them by pushing next_sync_at forward so a later tick does
// not re-enqueue the same record before the resync lands.
// Records due for a DATAJUD re-poll: ACTIVE only (SUPERSEDED placeholders and
// archived processes drop out) with a past next_sync_at. Served by the partial
// index on next_sync_at WHERE lifecycle='ACTIVE'.
func (q *Queries) DueCourtRecordsForResync(ctx context.Context, limit int32) ([]DueCourtRecordsForResyncRow, error) {
	rows, err := q.db.Query(ctx, dueCourtRecordsForResync, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DueCourtRecordsForResyncRow
	for rows.Next() {
		var i DueCourtRecordsForResyncRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CaseID,
			&i.CnjNumber,
			&i.Degree,
			&i.Court,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
