// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package acquisitiondb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCourtRecordByKey = `-- name: GetCourtRecordByKey :one
SELECT id, case_id
FROM court_record
WHERE tenant_id = $1 AND cnj_number = $2 AND degree = $3
`

type GetCourtRecordByKeyParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	CnjNumber string    `json:"cnj_number"`
	Degree    string    `json:"degree"`
}

type GetCourtRecordByKeyRow struct {
	ID     uuid.UUID `json:"id"`
	CaseID uuid.UUID `json:"case_id"`
}

// Resolve a court record by its natural key inside the caller's tx. A miss
// (pgx.ErrNoRows) is how FindOrCreateCourtRecord learns it must create one.
func (q *Queries) GetCourtRecordByKey(ctx context.Context, arg GetCourtRecordByKeyParams) (GetCourtRecordByKeyRow, error) {
	row := q.db.QueryRow(ctx, getCourtRecordByKey, arg.TenantID, arg.CnjNumber, arg.Degree)
	var i GetCourtRecordByKeyRow
	err := row.Scan(&i.ID, &i.CaseID)
	return i, err
}

const insertCourtCase = `-- name: InsertCourtCase :one
INSERT INTO court_case (tenant_id)
VALUES ($1)
RETURNING id
`

// Create the lide a first-seen court record hangs on. v0 has no consolidation
// yet, so every new record gets its own case; merging is a later slice.
func (q *Queries) InsertCourtCase(ctx context.Context, tenantID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCourtCase, tenantID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertCourtRecord = `-- name: InsertCourtRecord :one
INSERT INTO court_record
    (tenant_id, case_id, cnj_number, degree, court, class, subject, completeness)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertCourtRecordParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	CaseID       uuid.UUID `json:"case_id"`
	CnjNumber    string    `json:"cnj_number"`
	Degree       string    `json:"degree"`
	Court        string    `json:"court"`
	Class        *string   `json:"class"`
	Subject      *string   `json:"subject"`
	Completeness float32   `json:"completeness"`
}

// Create a court record under a case. The natural key (tenant, cnj, degree) is
// UNIQUE, so a racing double-create fails loudly rather than duplicating.
func (q *Queries) InsertCourtRecord(ctx context.Context, arg InsertCourtRecordParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCourtRecord,
		arg.TenantID,
		arg.CaseID,
		arg.CnjNumber,
		arg.Degree,
		arg.Court,
		arg.Class,
		arg.Subject,
		arg.Completeness,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertDocketEntry = `-- name: InsertDocketEntry :one
INSERT INTO docket_entry
    (court_record_id, hash, occurred_at, observed_at, source, fidelity, text)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (court_record_id, hash) DO NOTHING
RETURNING id
`

type InsertDocketEntryParams struct {
	CourtRecordID uuid.UUID          `json:"court_record_id"`
	Hash          string             `json:"hash"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
	Source        string             `json:"source"`
	Fidelity      int32              `json:"fidelity"`
	Text          string             `json:"text"`
}

// Append one andamento, idempotent on (court_record_id, hash). On conflict the
// row is left untouched and no id is returned (pgx.ErrNoRows), which the caller
// reads as "deduped" — so a re-sync emits no docket_entry_observed for it.
func (q *Queries) InsertDocketEntry(ctx context.Context, arg InsertDocketEntryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertDocketEntry,
		arg.CourtRecordID,
		arg.Hash,
		arg.OccurredAt,
		arg.ObservedAt,
		arg.Source,
		arg.Fidelity,
		arg.Text,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertIntimation = `-- name: InsertIntimation :one
INSERT INTO intimation
    (tenant_id, case_id, court_record_id, hash, made_available_at, published_at, deadline_start_at, content, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (tenant_id, case_id, hash) DO NOTHING
RETURNING id
`

type InsertIntimationParams struct {
	TenantID        uuid.UUID   `json:"tenant_id"`
	CaseID          uuid.UUID   `json:"case_id"`
	CourtRecordID   uuid.UUID   `json:"court_record_id"`
	Hash            string      `json:"hash"`
	MadeAvailableAt pgtype.Date `json:"made_available_at"`
	PublishedAt     pgtype.Date `json:"published_at"`
	DeadlineStartAt pgtype.Date `json:"deadline_start_at"`
	Content         string      `json:"content"`
	Source          string      `json:"source"`
}

// Append one intimação, idempotent on (tenant_id, case_id, hash). Same
// conflict-as-dedup contract as docket entries; recipients defaults to '[]'.
func (q *Queries) InsertIntimation(ctx context.Context, arg InsertIntimationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertIntimation,
		arg.TenantID,
		arg.CaseID,
		arg.CourtRecordID,
		arg.Hash,
		arg.MadeAvailableAt,
		arg.PublishedAt,
		arg.DeadlineStartAt,
		arg.Content,
		arg.Source,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSyncRun = `-- name: InsertSyncRun :one

INSERT INTO sync_run
    (tenant_id, integration_id, connector_id, connector_version, started_at, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertSyncRunParams struct {
	TenantID         uuid.UUID          `json:"tenant_id"`
	IntegrationID    uuid.UUID          `json:"integration_id"`
	ConnectorID      string             `json:"connector_id"`
	ConnectorVersion string             `json:"connector_version"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	Status           string             `json:"status"`
}

// sync cycle queries (acquisition slice).
// The sync listener reacts to sync_requested: it opens a sync_run (RUNNING),
// fetches+parses a window, then upserts the observed records/entries/intimations
// and closes the run (OK/FAILED) — all keyed off the court_record's natural key
// (tenant_id, cnj_number, degree). Idempotency lives in the schema: docket_entry
// and intimation carry UNIQUE constraints, so a re-sync of the same window
// inserts nothing new (ON CONFLICT DO NOTHING) and the RETURNING clause tells the
// caller which rows were actually new.
// Open a sync run. court_record_id is left NULL (OAB window discovery is not yet
// tied to one record); finished_at/error stay NULL until the run closes.
func (q *Queries) InsertSyncRun(ctx context.Context, arg InsertSyncRunParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertSyncRun,
		arg.TenantID,
		arg.IntegrationID,
		arg.ConnectorID,
		arg.ConnectorVersion,
		arg.StartedAt,
		arg.Status,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markCourtRecordSynced = `-- name: MarkCourtRecordSynced :exec
UPDATE court_record
SET completeness = $2,
    next_sync_at = $3
WHERE id = $1
`

type MarkCourtRecordSyncedParams struct {
	ID           uuid.UUID          `json:"id"`
	Completeness float32            `json:"completeness"`
	NextSyncAt   pgtype.Timestamptz `json:"next_sync_at"`
}

// Record that a sync touched this court record: refresh its completeness and
// schedule the next sweep (next_sync_at drives the scheduler slice later).
func (q *Queries) MarkCourtRecordSynced(ctx context.Context, arg MarkCourtRecordSyncedParams) error {
	_, err := q.db.Exec(ctx, markCourtRecordSynced, arg.ID, arg.Completeness, arg.NextSyncAt)
	return err
}

const updateSyncRun = `-- name: UpdateSyncRun :exec
UPDATE sync_run
SET status = $2,
    items_new = $3,
    items_deduped = $4,
    finished_at = $5,
    error = $6
WHERE id = $1
`

type UpdateSyncRunParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       string             `json:"status"`
	ItemsNew     int32              `json:"items_new"`
	ItemsDeduped int32              `json:"items_deduped"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	Error        []byte             `json:"error"`
}

// Close a sync run: OK carries the item tallies and a NULL error; FAILED carries
// the error jsonb and zero tallies. finished_at is set by the caller's clock.
func (q *Queries) UpdateSyncRun(ctx context.Context, arg UpdateSyncRunParams) error {
	_, err := q.db.Exec(ctx, updateSyncRun,
		arg.ID,
		arg.Status,
		arg.ItemsNew,
		arg.ItemsDeduped,
		arg.FinishedAt,
		arg.Error,
	)
	return err
}
