// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: triage.sql

package acquisitiondb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignIntimationResponsaveis = `-- name: AssignIntimationResponsaveis :one
UPDATE intimation
   SET conductor_user_id = $3::uuid,
       reviewer_user_id  = $4::uuid
 WHERE id = $1 AND tenant_id = $2
RETURNING id
`

type AssignIntimationResponsaveisParams struct {
	ID              uuid.UUID   `json:"id"`
	TenantID        uuid.UUID   `json:"tenant_id"`
	ConductorUserID pgtype.UUID `json:"conductor_user_id"`
	ReviewerUserID  pgtype.UUID `json:"reviewer_user_id"`
}

// Set (or clear, via NULL) the conductor_user_id and reviewer_user_id on one intimation,
// tenant-scoped (barrier 1, RLS barrier 2). Both are nullable: passing NULL desatribui
// the role. The use case pre-validates membership (AppUserExistsInTenant) before calling
// this, so the FK is always satisfied when non-null. A zero-row result (unknown id or
// foreign tenant's row) surfaces as pgx.ErrNoRows → ErrIntimationNotFound (→ 404).
// Idempotent: re-assigning the same user re-writes the same value.
func (q *Queries) AssignIntimationResponsaveis(ctx context.Context, arg AssignIntimationResponsaveisParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, assignIntimationResponsaveis,
		arg.ID,
		arg.TenantID,
		arg.ConductorUserID,
		arg.ReviewerUserID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const bulkAssignConductorByFilter = `-- name: BulkAssignConductorByFilter :execrows
UPDATE intimation
   SET conductor_user_id = $1::uuid
 WHERE tenant_id = $2::uuid
   AND id IN (
     SELECT i.id
     FROM intimation i
     JOIN court_record cr ON cr.id = i.court_record_id
     LEFT JOIN deadline d ON d.notification_id = i.id AND d.tenant_id = i.tenant_id
     WHERE i.tenant_id = $2::uuid
       AND (
         $3::text = ''
         OR cr.cnj_number ILIKE '%' || $3 || '%' ESCAPE '\'
         OR cr.class ILIKE '%' || $3 || '%'
         OR cr.judging_body ILIKE '%' || $3 || '%'
       )
       AND ($4::text = '' OR i.type = $4::text)
       AND ($5::text = '' OR i.user_status = $5::text)
       AND ($6::text = '' OR cr.court = $6::text)
       AND (
         $7::uuid IS NULL
         OR i.conductor_user_id = $7::uuid
         OR i.reviewer_user_id = $7::uuid
       )
       AND (
         $8::text = ''
         OR ($8::text = 'atraso'             AND (d.end_date - CURRENT_DATE) < 0  AND d.status IN ('PENDING', 'OPEN'))
         OR ($8::text = 'hoje'               AND (d.end_date - CURRENT_DATE) = 0  AND d.status IN ('PENDING', 'OPEN'))
         OR ($8::text = 'proximos_dois_dias' AND (d.end_date - CURRENT_DATE) BETWEEN 1 AND 2 AND d.status IN ('PENDING', 'OPEN'))
         OR ($8::text = 'semana'             AND (d.end_date - CURRENT_DATE) BETWEEN 3 AND 7 AND d.status IN ('PENDING', 'OPEN'))
         OR ($8::text = 'mais_adiante'       AND (d.end_date - CURRENT_DATE) > 7   AND d.status IN ('PENDING', 'OPEN'))
         OR ($8::text = 'nao_confirmado'     AND d.status = 'PENDING')
         OR ($8::text = 'sem_providencia'    AND i.ai_analyzed_at IS NULL AND i.user_status NOT IN ('RESOLVED', 'IGNORED'))
       )
   )
`

type BulkAssignConductorByFilterParams struct {
	ConductorUserID pgtype.UUID `json:"conductor_user_id"`
	TenantID        uuid.UUID   `json:"tenant_id"`
	Search          string      `json:"search"`
	Type            string      `json:"type"`
	UserStatus      string      `json:"user_status"`
	Court           string      `json:"court"`
	AssigneeID      pgtype.UUID `json:"assignee_id"`
	Urgencia        string      `json:"urgencia"`
}

// Atribuição em massa do condutor para TODA a faixa/filtro atual (modo "todos" da UI —
// inclui as linhas ainda não paginadas). Reusa EXATAMENTE a cláusula de filtro do
// ListIntimacoes (search/type/user_status/court/assignee/urgencia) via subquery. SÓ toca
// conductor_user_id (preserva o revisor). tenant-scoped (barrier 1, RLS barrier 2).
func (q *Queries) BulkAssignConductorByFilter(ctx context.Context, arg BulkAssignConductorByFilterParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkAssignConductorByFilter,
		arg.ConductorUserID,
		arg.TenantID,
		arg.Search,
		arg.Type,
		arg.UserStatus,
		arg.Court,
		arg.AssigneeID,
		arg.Urgencia,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkAssignConductorByIDs = `-- name: BulkAssignConductorByIDs :execrows
UPDATE intimation
   SET conductor_user_id = $1::uuid
 WHERE tenant_id = $2::uuid
   AND id = ANY($3::uuid[])
`

type BulkAssignConductorByIDsParams struct {
	ConductorUserID pgtype.UUID `json:"conductor_user_id"`
	TenantID        uuid.UUID   `json:"tenant_id"`
	Ids             []uuid.UUID `json:"ids"`
}

// Atribuição em massa do condutor (SÓ conductor_user_id — preserva o revisor) para
// uma lista explícita de ids, tenant-scoped (barrier 1, RLS barrier 2). NULL desatribui.
func (q *Queries) BulkAssignConductorByIDs(ctx context.Context, arg BulkAssignConductorByIDsParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkAssignConductorByIDs, arg.ConductorUserID, arg.TenantID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setIntimationUserStatus = `-- name: SetIntimationUserStatus :one

UPDATE intimation
   SET user_status = $3
 WHERE id = $1 AND tenant_id = $2
RETURNING id
`

type SetIntimationUserStatusParams struct {
	ID         uuid.UUID `json:"id"`
	TenantID   uuid.UUID `json:"tenant_id"`
	UserStatus string    `json:"user_status"`
}

// triagem da intimação — the write path for POST /v1/intimacoes/:id/{resolve,
// ignore,reopen}. The user drives the intimation's workflow state (user_status,
// 0030), SEPARATE from the DJEN cancellation `status`. Runs inside the caller's tx
// (UoW + SET LOCAL app.tenant_id), so RLS is a second barrier under the explicit
// tenant_id filter. No outbox event yet — there is no consumer of a triagem fact —
// so this is a bare projection write (a future slice can emit in this same tx).
// Set the intimation's triagem state (user_status) to $3, tenant-scoped (barrier 1,
// RLS barrier 2). The three actions map to the three target states: resolve→RESOLVED,
// ignore→IGNORED, reopen→PENDING. Only user_status is touched — the DJEN `status`
// (ACTIVE/CANCELLED) is left alone. A zero-row result (unknown id or a foreign tenant's
// row) surfaces as pgx.ErrNoRows → ErrIntimationNotFound (→ 404), never nil,nil.
// Idempotent: re-resolving an already-RESOLVED row rewrites the same value.
func (q *Queries) SetIntimationUserStatus(ctx context.Context, arg SetIntimationUserStatusParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, setIntimationUserStatus, arg.ID, arg.TenantID, arg.UserStatus)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
