// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package billingdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Resolve the stored subscription (and thus its tenant) by Stripe customer id.
	// Used to recover the tenant for an invoice.payment_failed whose object carries no
	// tenant_id metadata — the customer→tenant mapping was persisted at subscription
	// creation. No row → typed not-found (the caller retries).
	FindByStripeCustomer(ctx context.Context, stripeCustomerID *string) (Subscription, error)
	// Read the tenant's own subscription projection (Stripe Customer = tenant, one row
	// per tenant). Backs the read-model endpoint (GET /v1/billing/subscription) and the
	// checkout/portal flows that need the stored stripe_customer_id. Scoped by tenant_id
	// (WHERE + RLS). No row → the caller maps pgx.ErrNoRows to a typed not-found.
	FindByTenant(ctx context.Context, tenantID uuid.UUID) (Subscription, error)
	// Flip only the lifecycle status (a customer.subscription.deleted → canceled, an
	// invoice.payment_failed → past_due). It leaves plan / active_process_limit /
	// current_period_end untouched: those events carry no catalog data, so a status-only
	// write must not wipe the projected entitlement. Scoped by tenant_id (WHERE + RLS).
	// No row (a status event racing ahead of subscription.created) → the caller maps
	// pgx.ErrNoRows to a typed not-found so Stripe retries.
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscription, error)
	// billing slice queries (subscription projection).
	// Writes are idempotent so the Stripe webhook (at-least-once) can replay safely;
	// the consumer-side dedup (processed_event, keyed by the Stripe event id) is the
	// authoritative guard, these upserts are the second line of defence.
	// Project the full subscription state from a customer.subscription.created/updated
	// webhook. Keyed on tenant_id (Stripe Customer = tenant, one row per tenant): the
	// first sighting inserts, every later one refreshes the mutable fields. plan and
	// active_process_limit come resolved from the price's Stripe product metadata.
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error)
}

var _ Querier = (*Queries)(nil)
