// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package onboardingdb

import (
	"context"
)

type Querier interface {
	// Upsert the caller's dismissal timestamp (PATCH /v1/onboarding/dismiss),
	// inside the caller's tx. Idempotent: a repeat dismiss just restamps
	// dismissed_at to now() — never an error.
	Dismiss(ctx context.Context, arg DismissParams) error
	// Read model for GET /v1/onboarding/progress: the tenant-wide activation
	// Steps (sources connected, team invited, first triagem, first análise, first
	// peça) plus the caller's OWN dismissal timestamp, in one round-trip. Every
	// step is an EXISTS subquery over another slice's table — cheap on an indexed
	// tenant_id/FK column, never NULL. Subquery tables are aliased and columns
	// qualified so the planner never confuses one sibling subquery's tenant_id
	// with another's. members_invited excludes the caller itself ($2) so a lone
	// admin does not read as "team invited". dismissed_at is scoped by
	// app_user_id ($2), not tenant_id — dismissal is per-user, so each teammate
	// sees their own widget state.
	GetProgress(ctx context.Context, arg GetProgressParams) (GetProgressRow, error)
}

var _ Querier = (*Queries)(nil)
