// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read.sql

package documentdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDocumentsByProcesso = `-- name: CountDocumentsByProcesso :one
SELECT count(*) FROM document d
WHERE d.court_record_id = $1::uuid
  AND d.tenant_id = $2::uuid
  AND d.deleted_at IS NULL
`

type CountDocumentsByProcessoParams struct {
	CourtRecordID uuid.UUID `json:"court_record_id"`
	TenantID      uuid.UUID `json:"tenant_id"`
}

// The "X de Y" total for the Documentos tab: how many live documents the process holds. Same
// tenant + court_record scoping (and deleted_at IS NULL filter) as the list.
func (q *Queries) CountDocumentsByProcesso(ctx context.Context, arg CountDocumentsByProcessoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByProcesso, arg.CourtRecordID, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDocument = `-- name: GetDocument :one
SELECT d.id, d.court_record_id, d.document_type, d.origin, d.title,
       d.original_filename, d.mime_type, d.size_bytes, d.pages, d.status,
       d.has_text_layer, d.checksum, d.created_at
FROM document d
WHERE d.id = $1::uuid AND d.tenant_id = $2::uuid AND d.deleted_at IS NULL
`

type GetDocumentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetDocumentRow struct {
	ID               uuid.UUID          `json:"id"`
	CourtRecordID    pgtype.UUID        `json:"court_record_id"`
	DocumentType     string             `json:"document_type"`
	Origin           string             `json:"origin"`
	Title            *string            `json:"title"`
	OriginalFilename *string            `json:"original_filename"`
	MimeType         *string            `json:"mime_type"`
	SizeBytes        *int64             `json:"size_bytes"`
	Pages            *int32             `json:"pages"`
	Status           string             `json:"status"`
	HasTextLayer     bool               `json:"has_text_layer"`
	Checksum         *string            `json:"checksum"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

// The detail view of one document (GET /v1/documentos/:id): every field the DocumentView
// carries. Tenant-scoped (barrier 1) and filtering deleted_at IS NULL: a foreign / unknown /
// soft-deleted id resolves to no row → pgx.ErrNoRows → typed ErrDocumentNotFound (404) at the
// repo, never (nil, nil). $1 = id, $2 = tenant_id (from the principal).
func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.TenantID)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.CourtRecordID,
		&i.DocumentType,
		&i.Origin,
		&i.Title,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Pages,
		&i.Status,
		&i.HasTextLayer,
		&i.Checksum,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentsByProcesso = `-- name: ListDocumentsByProcesso :many

SELECT d.id, d.court_record_id, d.document_type, d.origin, d.title,
       d.original_filename, d.mime_type, d.size_bytes, d.pages, d.status,
       d.has_text_layer, d.checksum, d.created_at
FROM document d
WHERE d.court_record_id = $1::uuid
  AND d.tenant_id = $2::uuid
  AND d.deleted_at IS NULL
  AND (d.created_at, d.id) < ($3::timestamptz, $4::uuid)
ORDER BY d.created_at DESC, d.id DESC
LIMIT $5
`

type ListDocumentsByProcessoParams struct {
	CourtRecordID uuid.UUID          `json:"court_record_id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	LastCreated   pgtype.Timestamptz `json:"last_created"`
	LastID        uuid.UUID          `json:"last_id"`
	PageLimit     int32              `json:"page_limit"`
}

type ListDocumentsByProcessoRow struct {
	ID               uuid.UUID          `json:"id"`
	CourtRecordID    pgtype.UUID        `json:"court_record_id"`
	DocumentType     string             `json:"document_type"`
	Origin           string             `json:"origin"`
	Title            *string            `json:"title"`
	OriginalFilename *string            `json:"original_filename"`
	MimeType         *string            `json:"mime_type"`
	SizeBytes        *int64             `json:"size_bytes"`
	Pages            *int32             `json:"pages"`
	Status           string             `json:"status"`
	HasTextLayer     bool               `json:"has_text_layer"`
	Checksum         *string            `json:"checksum"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

// read-model queries (document slice) — the Documentos SCREEN reads, kept OFF the write
// path (docs: "leitura de tela usa read model, DTO por query dedicada"). Each is tenant-scoped
// (barrier 1: an explicit tenant_id filter from the trusted principal, never the body) and,
// where paginated, keyset-paginated on a stable (created_at, id) pair — DESCENDING, since the
// aba lists newest-first. The caller passes a max sentinel cursor for the first page, so there
// is no conditional WHERE. Every list filters deleted_at IS NULL (a soft-deleted document is
// gone from the tela).
// The Documentos tab of one process (GET /v1/processos/:id/documentos): the documents anchored
// on the court_record, newest first. @court_record_id is the court_record id (the same id
// /processos returns). Descending keyset on (created_at, id); the first page passes the max
// sentinel. deleted_at IS NULL excludes soft-deleted documents.
func (q *Queries) ListDocumentsByProcesso(ctx context.Context, arg ListDocumentsByProcessoParams) ([]ListDocumentsByProcessoRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByProcesso,
		arg.CourtRecordID,
		arg.TenantID,
		arg.LastCreated,
		arg.LastID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByProcessoRow
	for rows.Next() {
		var i ListDocumentsByProcessoRow
		if err := rows.Scan(
			&i.ID,
			&i.CourtRecordID,
			&i.DocumentType,
			&i.Origin,
			&i.Title,
			&i.OriginalFilename,
			&i.MimeType,
			&i.SizeBytes,
			&i.Pages,
			&i.Status,
			&i.HasTextLayer,
			&i.Checksum,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
