// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: section.sql

package pieceprofiledb

import (
	"context"

	"github.com/google/uuid"
)

const deleteSection = `-- name: DeleteSection :execrows
DELETE FROM profile_section
WHERE id = $1
`

func (q *Queries) DeleteSection(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSectionsByProfile = `-- name: GetSectionsByProfile :many
SELECT id, piece_profile_key, key, titulo, ordem, obrigatoria, origem, aceita_teses, fonte_legal
FROM profile_section
WHERE piece_profile_key = $1
ORDER BY ordem
`

func (q *Queries) GetSectionsByProfile(ctx context.Context, pieceProfileKey string) ([]ProfileSection, error) {
	rows, err := q.db.Query(ctx, getSectionsByProfile, pieceProfileKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfileSection
	for rows.Next() {
		var i ProfileSection
		if err := rows.Scan(
			&i.ID,
			&i.PieceProfileKey,
			&i.Key,
			&i.Titulo,
			&i.Ordem,
			&i.Obrigatoria,
			&i.Origem,
			&i.AceitaTeses,
			&i.FonteLegal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSection = `-- name: InsertSection :one
INSERT INTO profile_section (piece_profile_key, key, titulo, ordem, obrigatoria, origem, aceita_teses, fonte_legal)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, piece_profile_key, key, titulo, ordem, obrigatoria, origem, aceita_teses, fonte_legal
`

type InsertSectionParams struct {
	PieceProfileKey string  `json:"piece_profile_key"`
	Key             string  `json:"key"`
	Titulo          string  `json:"titulo"`
	Ordem           int32   `json:"ordem"`
	Obrigatoria     string  `json:"obrigatoria"`
	Origem          string  `json:"origem"`
	AceitaTeses     bool    `json:"aceita_teses"`
	FonteLegal      *string `json:"fonte_legal"`
}

func (q *Queries) InsertSection(ctx context.Context, arg InsertSectionParams) (ProfileSection, error) {
	row := q.db.QueryRow(ctx, insertSection,
		arg.PieceProfileKey,
		arg.Key,
		arg.Titulo,
		arg.Ordem,
		arg.Obrigatoria,
		arg.Origem,
		arg.AceitaTeses,
		arg.FonteLegal,
	)
	var i ProfileSection
	err := row.Scan(
		&i.ID,
		&i.PieceProfileKey,
		&i.Key,
		&i.Titulo,
		&i.Ordem,
		&i.Obrigatoria,
		&i.Origem,
		&i.AceitaTeses,
		&i.FonteLegal,
	)
	return i, err
}

const updateSection = `-- name: UpdateSection :one
UPDATE profile_section
SET key = COALESCE(NULLIF($1::text, ''), key),
    titulo = COALESCE(NULLIF($2::text, ''), titulo),
    ordem = CASE WHEN $3::int = 0 THEN ordem ELSE $3::int END,
    obrigatoria = COALESCE(NULLIF($4::text, ''), obrigatoria),
    origem = COALESCE(NULLIF($5::text, ''), origem),
    aceita_teses = $6,
    fonte_legal = $7
WHERE id = $8
RETURNING id, piece_profile_key, key, titulo, ordem, obrigatoria, origem, aceita_teses, fonte_legal
`

type UpdateSectionParams struct {
	NewKey      string    `json:"new_key"`
	Titulo      string    `json:"titulo"`
	Ordem       int32     `json:"ordem"`
	Obrigatoria string    `json:"obrigatoria"`
	Origem      string    `json:"origem"`
	AceitaTeses bool      `json:"aceita_teses"`
	FonteLegal  *string   `json:"fonte_legal"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateSection(ctx context.Context, arg UpdateSectionParams) (ProfileSection, error) {
	row := q.db.QueryRow(ctx, updateSection,
		arg.NewKey,
		arg.Titulo,
		arg.Ordem,
		arg.Obrigatoria,
		arg.Origem,
		arg.AceitaTeses,
		arg.FonteLegal,
		arg.ID,
	)
	var i ProfileSection
	err := row.Scan(
		&i.ID,
		&i.PieceProfileKey,
		&i.Key,
		&i.Titulo,
		&i.Ordem,
		&i.Obrigatoria,
		&i.Origem,
		&i.AceitaTeses,
		&i.FonteLegal,
	)
	return i, err
}
