// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: version.sql

package pieceprofiledb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVersionByKeyAndVersion = `-- name: GetVersionByKeyAndVersion :one
SELECT id, piece_profile_key, version, vigente_desde, snapshot
FROM piece_profile_version
WHERE piece_profile_key = $1 AND version = $2
`

type GetVersionByKeyAndVersionParams struct {
	PieceProfileKey string `json:"piece_profile_key"`
	Version         string `json:"version"`
}

func (q *Queries) GetVersionByKeyAndVersion(ctx context.Context, arg GetVersionByKeyAndVersionParams) (PieceProfileVersion, error) {
	row := q.db.QueryRow(ctx, getVersionByKeyAndVersion, arg.PieceProfileKey, arg.Version)
	var i PieceProfileVersion
	err := row.Scan(
		&i.ID,
		&i.PieceProfileKey,
		&i.Version,
		&i.VigenteDesde,
		&i.Snapshot,
	)
	return i, err
}

const insertVersion = `-- name: InsertVersion :one
INSERT INTO piece_profile_version (piece_profile_key, version, vigente_desde, snapshot)
VALUES ($1, $2, $3, $4)
RETURNING id, piece_profile_key, version, vigente_desde, snapshot
`

type InsertVersionParams struct {
	PieceProfileKey string             `json:"piece_profile_key"`
	Version         string             `json:"version"`
	VigenteDesde    pgtype.Timestamptz `json:"vigente_desde"`
	Snapshot        []byte             `json:"snapshot"`
}

func (q *Queries) InsertVersion(ctx context.Context, arg InsertVersionParams) (PieceProfileVersion, error) {
	row := q.db.QueryRow(ctx, insertVersion,
		arg.PieceProfileKey,
		arg.Version,
		arg.VigenteDesde,
		arg.Snapshot,
	)
	var i PieceProfileVersion
	err := row.Scan(
		&i.ID,
		&i.PieceProfileKey,
		&i.Version,
		&i.VigenteDesde,
		&i.Snapshot,
	)
	return i, err
}
