// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_coverage_summary.sql

package thesisdb

import (
	"context"

	"github.com/google/uuid"
)

const getCoverageSummary = `-- name: GetCoverageSummary :one
SELECT
    COALESCE(SUM(CASE WHEN tc.resultado = 'coberta' THEN 1 ELSE 0 END), 0)::int AS coberta,
    COALESCE(SUM(CASE WHEN tc.resultado = 'divergente' THEN 1 ELSE 0 END), 0)::int AS divergente,
    COALESCE(SUM(CASE WHEN tc.resultado = 'ausente' THEN 1 ELSE 0 END), 0)::int AS ausente
FROM thesis t
LEFT JOIN thesis_coverage tc ON tc.thesis_id = t.id
WHERE t.tenant_id = $1 AND t.draft_id = $2
`

type GetCoverageSummaryParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	DraftID  uuid.UUID `json:"draft_id"`
}

type GetCoverageSummaryRow struct {
	Coberta    int32 `json:"coberta"`
	Divergente int32 `json:"divergente"`
	Ausente    int32 `json:"ausente"`
}

func (q *Queries) GetCoverageSummary(ctx context.Context, arg GetCoverageSummaryParams) (GetCoverageSummaryRow, error) {
	row := q.db.QueryRow(ctx, getCoverageSummary, arg.TenantID, arg.DraftID)
	var i GetCoverageSummaryRow
	err := row.Scan(&i.Coberta, &i.Divergente, &i.Ausente)
	return i, err
}
