// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_thesis_by_id.sql

package thesisdb

import (
	"context"

	"github.com/google/uuid"
)

const getThesisByID = `-- name: GetThesisByID :one
SELECT id, tenant_id, draft_id, piece_profile_key, notification_id, enunciado, forca, estado, created_at
FROM thesis
WHERE id = $1 AND tenant_id = $2
`

type GetThesisByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetThesisByID(ctx context.Context, arg GetThesisByIDParams) (Thesis, error) {
	row := q.db.QueryRow(ctx, getThesisByID, arg.ID, arg.TenantID)
	var i Thesis
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DraftID,
		&i.PieceProfileKey,
		&i.NotificationID,
		&i.Enunciado,
		&i.Forca,
		&i.Estado,
		&i.CreatedAt,
	)
	return i, err
}
