// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_thesis_coverage.sql

package thesisdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertThesisCoverage = `-- name: InsertThesisCoverage :one
INSERT INTO thesis_coverage (id, thesis_id, resultado, detalhe, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (thesis_id) DO UPDATE
SET resultado = EXCLUDED.resultado, detalhe = EXCLUDED.detalhe, created_at = EXCLUDED.created_at
RETURNING id, thesis_id, resultado, detalhe, created_at
`

type InsertThesisCoverageParams struct {
	ID        uuid.UUID          `json:"id"`
	ThesisID  uuid.UUID          `json:"thesis_id"`
	Resultado string             `json:"resultado"`
	Detalhe   *string            `json:"detalhe"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertThesisCoverage(ctx context.Context, arg InsertThesisCoverageParams) (ThesisCoverage, error) {
	row := q.db.QueryRow(ctx, insertThesisCoverage,
		arg.ID,
		arg.ThesisID,
		arg.Resultado,
		arg.Detalhe,
		arg.CreatedAt,
	)
	var i ThesisCoverage
	err := row.Scan(
		&i.ID,
		&i.ThesisID,
		&i.Resultado,
		&i.Detalhe,
		&i.CreatedAt,
	)
	return i, err
}
