// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_anchors_by_segment.sql

package thesisdb

import (
	"context"

	"github.com/google/uuid"
)

const listAnchorsBySegment = `-- name: ListAnchorsBySegment :many
SELECT id, draft_segment_id, thesis_anchor_id, status
FROM segment_anchor
WHERE draft_segment_id = $1
ORDER BY id ASC
`

func (q *Queries) ListAnchorsBySegment(ctx context.Context, draftSegmentID uuid.UUID) ([]SegmentAnchor, error) {
	rows, err := q.db.Query(ctx, listAnchorsBySegment, draftSegmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SegmentAnchor
	for rows.Next() {
		var i SegmentAnchor
		if err := rows.Scan(
			&i.ID,
			&i.DraftSegmentID,
			&i.ThesisAnchorID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
