// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list_segments_by_draft.sql

package thesisdb

import (
	"context"

	"github.com/google/uuid"
)

const listSegmentsByDraft = `-- name: ListSegmentsByDraft :many
SELECT id, tenant_id, draft_id, thesis_id, profile_section_id, conteudo, created_at
FROM draft_segment
WHERE tenant_id = $1 AND draft_id = $2
ORDER BY created_at ASC
`

type ListSegmentsByDraftParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	DraftID  uuid.UUID `json:"draft_id"`
}

func (q *Queries) ListSegmentsByDraft(ctx context.Context, arg ListSegmentsByDraftParams) ([]DraftSegment, error) {
	rows, err := q.db.Query(ctx, listSegmentsByDraft, arg.TenantID, arg.DraftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DraftSegment
	for rows.Next() {
		var i DraftSegment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DraftID,
			&i.ThesisID,
			&i.ProfileSectionID,
			&i.Conteudo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
