// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package thesisdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetCoverageSummary(ctx context.Context, arg GetCoverageSummaryParams) (GetCoverageSummaryRow, error)
	GetThesisByID(ctx context.Context, arg GetThesisByIDParams) (Thesis, error)
	InsertDraftSegment(ctx context.Context, arg InsertDraftSegmentParams) (DraftSegment, error)
	InsertSegmentAnchor(ctx context.Context, arg InsertSegmentAnchorParams) (SegmentAnchor, error)
	InsertThesis(ctx context.Context, arg InsertThesisParams) (Thesis, error)
	InsertThesisAnchor(ctx context.Context, arg InsertThesisAnchorParams) (ThesisAnchor, error)
	InsertThesisCoverage(ctx context.Context, arg InsertThesisCoverageParams) (ThesisCoverage, error)
	ListAnchorsBySegment(ctx context.Context, draftSegmentID uuid.UUID) ([]SegmentAnchor, error)
	ListAnchorsByThesis(ctx context.Context, thesisID uuid.UUID) ([]ThesisAnchor, error)
	ListCoverageByDraft(ctx context.Context, arg ListCoverageByDraftParams) ([]ThesisCoverage, error)
	ListSegmentsByDraft(ctx context.Context, arg ListSegmentsByDraftParams) ([]DraftSegment, error)
	ListThesesByDraft(ctx context.Context, arg ListThesesByDraftParams) ([]Thesis, error)
	UpdateThesisEstado(ctx context.Context, arg UpdateThesisEstadoParams) (Thesis, error)
}

var _ Querier = (*Queries)(nil)
