// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package notificationsdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AppUser struct {
	ID          uuid.UUID          `json:"id"`
	ClerkUserID string             `json:"clerk_user_id"`
	TenantID    uuid.UUID          `json:"tenant_id"`
	Email       string             `json:"email"`
	Name        *string            `json:"name"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Phone       *string            `json:"phone"`
}

type BackfillJob struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	IntegrationID uuid.UUID          `json:"integration_id"`
	WindowFrom    pgtype.Date        `json:"window_from"`
	WindowTo      pgtype.Date        `json:"window_to"`
	TotalSlices   int32              `json:"total_slices"`
	SlicesOk      int32              `json:"slices_ok"`
	SlicesError   int32              `json:"slices_error"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type CaseLink struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	FromCourtRecordID uuid.UUID          `json:"from_court_record_id"`
	ToCourtRecordID   uuid.UUID          `json:"to_court_record_id"`
	Type              string             `json:"type"`
	Confidence        string             `json:"confidence"`
	Source            *string            `json:"source"`
	Evidence          string             `json:"evidence"`
	ConfirmedBy       pgtype.UUID        `json:"confirmed_by"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
}

type Chunk struct {
	ID         uuid.UUID        `json:"id"`
	DocumentID uuid.UUID        `json:"document_id"`
	Page       int32            `json:"page"`
	Text       string           `json:"text"`
	Embedding  *pgvector.Vector `json:"embedding"`
}

type CourtCase struct {
	ID                   uuid.UUID          `json:"id"`
	TenantID             uuid.UUID          `json:"tenant_id"`
	Label                *string            `json:"label"`
	PrimaryCourtRecordID pgtype.UUID        `json:"primary_court_record_id"`
	MergedIntoID         pgtype.UUID        `json:"merged_into_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type CourtRecord struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	CaseID       uuid.UUID          `json:"case_id"`
	CnjNumber    string             `json:"cnj_number"`
	Degree       string             `json:"degree"`
	Court        string             `json:"court"`
	Class        *string            `json:"class"`
	Subject      *string            `json:"subject"`
	ClaimValue   pgtype.Numeric     `json:"claim_value"`
	Secrecy      string             `json:"secrecy"`
	Lifecycle    string             `json:"lifecycle"`
	Completeness float32            `json:"completeness"`
	SyncPolicy   []byte             `json:"sync_policy"`
	NextSyncAt   pgtype.Timestamptz `json:"next_sync_at"`
	LastSyncedAt []byte             `json:"last_synced_at"`
	JudgingBody  *string            `json:"judging_body"`
	FiledAt      pgtype.Date        `json:"filed_at"`
}

type Deadline struct {
	ID              uuid.UUID   `json:"id"`
	CourtRecordID   uuid.UUID   `json:"court_record_id"`
	NotificationID  uuid.UUID   `json:"notification_id"`
	StartDate       pgtype.Date `json:"start_date"`
	EndDate         pgtype.Date `json:"end_date"`
	Days            int32       `json:"days"`
	Counting        string      `json:"counting"`
	Doubled         bool        `json:"doubled"`
	HolidaysApplied []byte      `json:"holidays_applied"`
	Status          string      `json:"status"`
}

type DocketEntry struct {
	ID            uuid.UUID          `json:"id"`
	CourtRecordID uuid.UUID          `json:"court_record_id"`
	Hash          string             `json:"hash"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
	Source        string             `json:"source"`
	Fidelity      int32              `json:"fidelity"`
	TpuCode       *int32             `json:"tpu_code"`
	Complements   []byte             `json:"complements"`
	Text          string             `json:"text"`
	RetractedAt   pgtype.Timestamptz `json:"retracted_at"`
}

type Document struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	CourtRecordID    pgtype.UUID        `json:"court_record_id"`
	DocumentType     string             `json:"document_type"`
	Origin           string             `json:"origin"`
	StorageKey       *string            `json:"storage_key"`
	Pages            *int32             `json:"pages"`
	HasTextLayer     bool               `json:"has_text_layer"`
	ExtractedAt      pgtype.Timestamptz `json:"extracted_at"`
	ExtractorVersion *string            `json:"extractor_version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Draft struct {
	ID         uuid.UUID          `json:"id"`
	TenantID   uuid.UUID          `json:"tenant_id"`
	CaseID     pgtype.UUID        `json:"case_id"`
	PieceType  string             `json:"piece_type"`
	Status     string             `json:"status"`
	SagaState  string             `json:"saga_state"`
	StorageKey string             `json:"storage_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Holiday struct {
	ID      uuid.UUID   `json:"id"`
	Scope   string      `json:"scope"`
	ScopeID *string     `json:"scope_id"`
	Date    pgtype.Date `json:"date"`
	Name    string      `json:"name"`
}

type Integration struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	Source        string             `json:"source"`
	Scope         []byte             `json:"scope"`
	CredentialRef *string            `json:"credential_ref"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Intimation struct {
	ID              uuid.UUID   `json:"id"`
	TenantID        uuid.UUID   `json:"tenant_id"`
	CaseID          uuid.UUID   `json:"case_id"`
	CourtRecordID   uuid.UUID   `json:"court_record_id"`
	Hash            string      `json:"hash"`
	MadeAvailableAt pgtype.Date `json:"made_available_at"`
	PublishedAt     pgtype.Date `json:"published_at"`
	DeadlineStartAt pgtype.Date `json:"deadline_start_at"`
	Content         string      `json:"content"`
	Source          string      `json:"source"`
	Recipients      []byte      `json:"recipients"`
	Type            *string     `json:"type"`
	Status          string      `json:"status"`
	SourceUrl       *string     `json:"source_url"`
	CancelledAt     pgtype.Date `json:"cancelled_at"`
	CancelReason    *string     `json:"cancel_reason"`
}

type Membership struct {
	ID                uuid.UUID          `json:"id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	AppUserID         uuid.UUID          `json:"app_user_id"`
	ClerkMembershipID *string            `json:"clerk_membership_id"`
	Role              string             `json:"role"`
	Status            string             `json:"status"`
	JoinedAt          pgtype.Timestamptz `json:"joined_at"`
	RemovedAt         pgtype.Timestamptz `json:"removed_at"`
}

type Notification struct {
	ID              uuid.UUID          `json:"id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	RecipientUserID pgtype.UUID        `json:"recipient_user_id"`
	Type            string             `json:"type"`
	Payload         []byte             `json:"payload"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Title           *string            `json:"title"`
	Body            *string            `json:"body"`
	ReadAt          pgtype.Timestamptz `json:"read_at"`
}

type NotificationDelivery struct {
	ID                uuid.UUID          `json:"id"`
	NotificationID    uuid.UUID          `json:"notification_id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	Channel           string             `json:"channel"`
	Status            string             `json:"status"`
	ProviderMessageID *string            `json:"provider_message_id"`
	Error             *string            `json:"error"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Outbox struct {
	ID             int64              `json:"id"`
	AggregateType  string             `json:"aggregate_type"`
	AggregateID    uuid.UUID          `json:"aggregate_id"`
	Type           string             `json:"type"`
	Payload        []byte             `json:"payload"`
	IdempotencyKey *string            `json:"idempotency_key"`
	TraceContext   *string            `json:"trace_context"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
}

type Petition struct {
	ID             uuid.UUID          `json:"id"`
	DraftID        uuid.UUID          `json:"draft_id"`
	CourtRecordID  uuid.UUID          `json:"court_record_id"`
	FiledAt        pgtype.Timestamptz `json:"filed_at"`
	Receipt        []byte             `json:"receipt"`
	ObservedResult *string            `json:"observed_result"`
}

type ProcessedEvent struct {
	Consumer    string             `json:"consumer"`
	EventID     string             `json:"event_id"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type Review struct {
	ID           uuid.UUID          `json:"id"`
	DraftID      uuid.UUID          `json:"draft_id"`
	Findings     []byte             `json:"findings"`
	Coverage     []byte             `json:"coverage"`
	ModelVersion string             `json:"model_version"`
	RulesVersion string             `json:"rules_version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID                   uuid.UUID          `json:"id"`
	TenantID             uuid.UUID          `json:"tenant_id"`
	StripeCustomerID     *string            `json:"stripe_customer_id"`
	StripeSubscriptionID *string            `json:"stripe_subscription_id"`
	Status               string             `json:"status"`
	Plan                 *string            `json:"plan"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	ActiveProcessLimit   *int32             `json:"active_process_limit"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type SyncRun struct {
	ID               uuid.UUID          `json:"id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	CourtRecordID    pgtype.UUID        `json:"court_record_id"`
	IntegrationID    uuid.UUID          `json:"integration_id"`
	ConnectorID      string             `json:"connector_id"`
	ConnectorVersion string             `json:"connector_version"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
	Status           string             `json:"status"`
	ItemsNew         int32              `json:"items_new"`
	ItemsDeduped     int32              `json:"items_deduped"`
	RawPayloadRefs   []byte             `json:"raw_payload_refs"`
	Error            []byte             `json:"error"`
	EventID          *string            `json:"event_id"`
}

type Tenant struct {
	ID                    uuid.UUID          `json:"id"`
	ClerkOrgID            string             `json:"clerk_org_id"`
	Name                  string             `json:"name"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	Cnpj                  *string            `json:"cnpj"`
	LegalName             *string            `json:"legal_name"`
	TradeName             *string            `json:"trade_name"`
	Address               []byte             `json:"address"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
	Phone                 *string            `json:"phone"`
	Email                 *string            `json:"email"`
}
