// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package notificationsdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// The unread-badge count: how many avisos visible to the user carry no read receipt
	// from them. tenant_id ($1) is barrier 1; RLS is barrier 2.
	CountUnread(ctx context.Context, arg CountUnreadParams) (int64, error)
	// Locate a delivery by the provider's message id (the Resend email id), on the
	// pool. A provider bounce/complaint webhook carries no tenant, so this read crosses
	// tenants (the owner bypasses RLS) to recover the delivery AND its tenant; the
	// caller then scopes the status update to that tenant (barrier 2). No row → the
	// mapper maps pgx.ErrNoRows to a typed not-found (an unknown id the webhook acks).
	FindDeliveryByProviderMessageID(ctx context.Context, providerMessageID *string) (NotificationDelivery, error)
	// Resolve the recipient's saved channel override for (tenant, user, type), inside
	// the caller's tx — the routing check OnNotificationRequested makes before sending.
	// No row means "no override": the mapper turns pgx.ErrNoRows into a typed
	// not-found the use case reads as the default (every channel enabled), never a
	// silently-empty slice that would suppress every channel by accident.
	FindPreferenceChannels(ctx context.Context, arg FindPreferenceChannelsParams) ([]string, error)
	// Resolve the recipient's e-mail by internal app_user id, scoped to the tenant
	// (WHERE + RLS). No row → the mapper maps pgx.ErrNoRows to a typed not-found, and
	// the use case records a FAILED delivery rather than dropping the aviso.
	FindRecipientEmail(ctx context.Context, arg FindRecipientEmailParams) (string, error)
	// Report whether the tenant has a backfill_job still RUNNING. The in-app use case
	// suppresses a per-andamento aviso while the onboarding import is in flight (the
	// import_finished aviso covers that window). Runs inside the caller's tx, so RLS and
	// the explicit tenant_id are the two isolation barriers.
	HasRunningBackfillForTenant(ctx context.Context, tenantID uuid.UUID) (bool, error)
	// Open a per-channel delivery attempt for a notification, inside the caller's tx.
	// UNIQUE(notification_id, channel) is the idempotency floor: at most one delivery
	// per channel per notification. The consumer-side event dedup (processed_event)
	// already prevents re-processing, so a fresh notification never conflicts here.
	InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (NotificationDelivery, error)
	// notifications slice queries (the avisos domain: notification + delivery).
	// Writes participate in the use case's transaction (transactional outbox / dedup
	// commit together); the recipient read runs inside that same tx so RLS scopes it
	// to the event's tenant. Absence is a typed error at the mapper, never (nil, nil).
	// Record the aviso itself (the fact that a user should be told something), inside
	// the caller's tx. recipient_user_id is nullable (some avisos are tenant-level);
	// title/body are the materialized in-app text (NULL for EMAIL avisos, which render
	// at send); payload is the template data. status starts CREATED — the delivery rows
	// carry the per-channel lifecycle.
	InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error)
	// The in-app inbox for ONE user: the avisos visible to them — tenant-level
	// (recipient_user_id IS NULL) OR addressed to them — newest first, keyset-paginated
	// on (created_at, id) descending. `read` is per-user: EXISTS a receipt for THIS user
	// in notification_read. @unread_only filters to the ones this user has not read;
	// @type ('' = all) filters to one closed-set type. The caller passes the max sentinel
	// cursor ('9999-…', max-uuid) for the first page, so there is no conditional WHERE.
	// tenant_id ($1) is barrier 1; RLS is barrier 2.
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	// The caller's own saved overrides (GET /v1/notifications/preferences), on the
	// pool — a screen read, no tx. Types the user never touched are absent (the
	// default applies implicitly); the FE reconciles against its own static list of
	// notification types. tenant_id ($1) is barrier 1; RLS is barrier 2.
	ListPreferences(ctx context.Context, arg ListPreferencesParams) ([]NotificationPreference, error)
	// Record read receipts for every aviso visible to the user that they have not read
	// yet, in the caller's tx. Idempotent: a re-run inserts nothing (the NOT EXISTS
	// filter plus the ON CONFLICT floor).
	MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error
	// Record the user's read receipt for one aviso, in the caller's tx. Idempotent: a
	// second call is a no-op via the (notification_id, user_id) PK. Visibility is
	// asserted separately (NotificationVisibleTo), so an unknown/cross-tenant id 404s.
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	// Assert an aviso exists AND is visible to the user in the tenant (tenant-level or
	// addressed to them). mark-read uses it to 404 an id from another tenant / addressed
	// to someone else, distinct from the idempotent receipt insert below (which cannot
	// tell "unknown aviso" from "already read" on its own). Runs in the caller's tx.
	NotificationVisibleTo(ctx context.Context, arg NotificationVisibleToParams) (bool, error)
	// Record the outcome of a send: SENT with the provider's message id, or FAILED
	// with the reason. Scoped by id AND tenant_id (app-layer barrier) on top of RLS.
	// No row (a delivery from another tenant) → the mapper maps pgx.ErrNoRows to a
	// typed not-found.
	UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) (NotificationDelivery, error)
	// Save the caller's full enabled-channel set for one type (PUT
	// /v1/notifications/preferences), inside the caller's tx. Idempotent: a repeat PUT
	// with the same channels is a harmless no-op write; ON CONFLICT replaces the set
	// whole (channels is not a delta).
	UpsertPreference(ctx context.Context, arg UpsertPreferenceParams) (NotificationPreference, error)
}

var _ Querier = (*Queries)(nil)
