// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage_event.sql

package aiusagedb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertUsageEvent = `-- name: InsertUsageEvent :exec
INSERT INTO ai_usage_event (
  tenant_id, use_case, provider, model,
  prompt_tokens, completion_tokens, total_tokens, cached_tokens,
  cost_usd, latency_ms, trace_id
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8,
  $9, $10, $11
)
`

type InsertUsageEventParams struct {
	TenantID         uuid.UUID      `json:"tenant_id"`
	UseCase          string         `json:"use_case"`
	Provider         string         `json:"provider"`
	Model            string         `json:"model"`
	PromptTokens     int32          `json:"prompt_tokens"`
	CompletionTokens int32          `json:"completion_tokens"`
	TotalTokens      int32          `json:"total_tokens"`
	CachedTokens     int32          `json:"cached_tokens"`
	CostUsd          pgtype.Numeric `json:"cost_usd"`
	LatencyMs        int32          `json:"latency_ms"`
	TraceID          *string        `json:"trace_id"`
}

// Records one completed LLM call's cost/usage. Called best-effort by lib/llm's
// OpenRouterGenerator, OUTSIDE any domain transaction — a failure here must never roll
// back or fail the generation it describes (the caller logs-and-continues on error).
func (q *Queries) InsertUsageEvent(ctx context.Context, arg InsertUsageEventParams) error {
	_, err := q.db.Exec(ctx, insertUsageEvent,
		arg.TenantID,
		arg.UseCase,
		arg.Provider,
		arg.Model,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.CachedTokens,
		arg.CostUsd,
		arg.LatencyMs,
		arg.TraceID,
	)
	return err
}
