// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package portalcredentialdb

import (
	"context"
)

type Querier interface {
	// Removes the caller's own credential row. The use case deletes the pointed-at
	// tenant_secret row in the SAME tx (via DeleteTenantSecret), so no secret
	// material outlives the credential that referenced it.
	DeletePortalCredential(ctx context.Context, arg DeletePortalCredentialParams) error
	// Removes a sealed secret — called when a credential is reconfigured (drop the
	// OLD secret after the new one is written and portal_credential repointed) or
	// deleted outright (drop the secret alongside the portal_credential row).
	DeleteTenantSecret(ctx context.Context, arg DeleteTenantSecretParams) error
	// The caller's OWN credential for a portal — never another app_user's (tenant_id
	// + app_user_id + portal is the whole natural key). Used by GET and by the
	// reconfigure/delete flows to resolve the current credential_ref first.
	GetPortalCredential(ctx context.Context, arg GetPortalCredentialParams) (PortalCredential, error)
	// Reads one sealed secret back for lib/vault.Open, scoped by tenant (RLS is the
	// second barrier; this WHERE is the first, app-level one).
	GetTenantSecret(ctx context.Context, arg GetTenantSecretParams) (TenantSecret, error)
	// Persists one sealed secret (lib/vault.Sealed already encrypted it — this
	// statement never sees plaintext). Called once per Configure — a reconfigure
	// (new password) inserts a NEW row and the caller repoints portal_credential's
	// credential_ref at it; the old row is deleted by the same tx (see
	// DeleteTenantSecret), so no orphan accumulates.
	InsertTenantSecret(ctx context.Context, arg InsertTenantSecretParams) (TenantSecret, error)
	// One row per (tenant, app_user, portal). A reconfigure (same advogado, same
	// portal) overwrites login/credential_ref/status/last_error/last_verified_at —
	// the credential the advogado just tested is the one in effect, never merged
	// with the stale row.
	UpsertPortalCredential(ctx context.Context, arg UpsertPortalCredentialParams) (PortalCredential, error)
}

var _ Querier = (*Queries)(nil)
